specification: stripe-api.yml
outputDir: lib
packageName: stripeapi
moduleName: StripeAPI
logLevel: WARN
force: true
incremental: false
dryRun: false
doNotGenerateStackProject: false
generateNixFiles: false
omitAdditionalOperationFunctions: true
generateOptionalEmptyRequestBody: false
useNumberedVariantConstructors: false
useFloatWithArbitraryPrecision: false
useIntWithArbitraryPrecision: false
useDateTypesAsString: false
convertToCamelCase: true
propertyTypeSuffix: "'"
responseTypeSuffix: "Response"
responseBodyTypeSuffix: "ResponseBody"
requestBodyTypeSuffix: "RequestBody"
parametersTypeSuffix: "Parameters"
parameterQueryPrefix: "query"
parameterPathPrefix: "path"
parameterCookiePrefix: "cookie"
parameterHeaderPrefix: "header"
operationsToGenerate: [ PostCustomers, GetPrices, PostCheckoutSessions, GetSubscriptions, GetCheckoutSessionsSession, PostBillingPortalSessions, DeleteSubscriptionsSubscriptionExposedId ]
opaqueSchemas: []
whiteListedSchemas: []
