{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema AccountInvoicesSettings
module StripeAPI.Types.AccountInvoicesSettings where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.TaxId
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.account_invoices_settings@ in the specification.
data AccountInvoicesSettings = AccountInvoicesSettings
  { -- | default_account_tax_ids: The list of default Account Tax IDs to automatically include on invoices. Account Tax IDs get added when an invoice is finalized.
    accountInvoicesSettingsDefaultAccountTaxIds :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable [AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants])),
    -- | hosted_payment_method_save: Whether payment methods should be saved when a payment is completed for a one-time invoices on a hosted invoice page.
    accountInvoicesSettingsHostedPaymentMethodSave :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON AccountInvoicesSettings where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("default_account_tax_ids" Data.Aeson.Types.ToJSON..=)) (accountInvoicesSettingsDefaultAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("hosted_payment_method_save" Data.Aeson.Types.ToJSON..=)) (accountInvoicesSettingsHostedPaymentMethodSave obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("default_account_tax_ids" Data.Aeson.Types.ToJSON..=)) (accountInvoicesSettingsDefaultAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("hosted_payment_method_save" Data.Aeson.Types.ToJSON..=)) (accountInvoicesSettingsHostedPaymentMethodSave obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON AccountInvoicesSettings where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "AccountInvoicesSettings" (\obj -> (GHC.Base.pure AccountInvoicesSettings GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "default_account_tax_ids")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "hosted_payment_method_save"))

-- | Create a new 'AccountInvoicesSettings' with all required fields.
mkAccountInvoicesSettings :: AccountInvoicesSettings
mkAccountInvoicesSettings =
  AccountInvoicesSettings
    { accountInvoicesSettingsDefaultAccountTaxIds = GHC.Maybe.Nothing,
      accountInvoicesSettingsHostedPaymentMethodSave = GHC.Maybe.Nothing
    }

-- | Defines the oneOf schema located at @components.schemas.account_invoices_settings.properties.default_account_tax_ids.items.anyOf@ in the specification.
data AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants
  = AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableText Data.Text.Internal.Text
  | AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableTaxId TaxId
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants where
  toJSON (AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableText a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableTaxId a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants where
  parseJSON val = case (AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
    Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
    Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a

-- | Defines the enum schema located at @components.schemas.account_invoices_settings.properties.hosted_payment_method_save@ in the specification.
--
-- Whether payment methods should be saved when a payment is completed for a one-time invoices on a hosted invoice page.
data AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableOther Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableTyped Data.Text.Internal.Text
  | -- | Represents the JSON value @"always"@
    AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumAlways
  | -- | Represents the JSON value @"never"@
    AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumNever
  | -- | Represents the JSON value @"offer"@
    AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumOffer
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable where
  toJSON (AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableOther val) = val
  toJSON (AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumAlways) = "always"
  toJSON (AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumNever) = "never"
  toJSON (AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumOffer) = "offer"

instance Data.Aeson.Types.FromJSON.FromJSON AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "always" -> AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumAlways
          | val GHC.Classes.== "never" -> AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumNever
          | val GHC.Classes.== "offer" -> AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableEnumOffer
          | GHC.Base.otherwise -> AccountInvoicesSettingsHostedPaymentMethodSave'NonNullableOther val
      )
