module StripeAPI.Types.AccountUnificationAccountControllerStripeDashboard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data AccountUnificationAccountControllerStripeDashboard
instance Show AccountUnificationAccountControllerStripeDashboard
instance Eq AccountUnificationAccountControllerStripeDashboard
instance Data.Aeson.FromJSON AccountUnificationAccountControllerStripeDashboard
instance Data.Aeson.ToJSON AccountUnificationAccountControllerStripeDashboard
data AccountUnificationAccountControllerStripeDashboardType'
instance Show AccountUnificationAccountControllerStripeDashboardType'
instance Eq AccountUnificationAccountControllerStripeDashboardType'
instance Data.Aeson.FromJSON AccountUnificationAccountControllerStripeDashboardType'
instance Data.Aeson.ToJSON AccountUnificationAccountControllerStripeDashboardType'
