module StripeAPI.Types.AccountInvoicesSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data AccountInvoicesSettings
instance Show AccountInvoicesSettings
instance Eq AccountInvoicesSettings
instance Data.Aeson.FromJSON AccountInvoicesSettings
instance Data.Aeson.ToJSON AccountInvoicesSettings
data AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants
instance Show AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants
instance Eq AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants
instance Data.Aeson.FromJSON AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants
instance Data.Aeson.ToJSON AccountInvoicesSettingsDefaultAccountTaxIds'NonNullableVariants
data AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable
instance Show AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable
instance Eq AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable
instance Data.Aeson.FromJSON AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable
instance Data.Aeson.ToJSON AccountInvoicesSettingsHostedPaymentMethodSave'NonNullable
