module StripeAPI.Types.AccountSepaDebitPaymentsSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data AccountSepaDebitPaymentsSettings
instance Show AccountSepaDebitPaymentsSettings
instance Eq AccountSepaDebitPaymentsSettings
instance Data.Aeson.FromJSON AccountSepaDebitPaymentsSettings
instance Data.Aeson.ToJSON AccountSepaDebitPaymentsSettings
