module StripeAPI.Types.AccountBusinessProfile where
import qualified Data.Aeson
import qualified StripeAPI.Common
data AccountBusinessProfile
instance Show AccountBusinessProfile
instance Eq AccountBusinessProfile
instance Data.Aeson.FromJSON AccountBusinessProfile
instance Data.Aeson.ToJSON AccountBusinessProfile
data AccountBusinessProfileAnnualRevenue'NonNullable
instance Show AccountBusinessProfileAnnualRevenue'NonNullable
instance Eq AccountBusinessProfileAnnualRevenue'NonNullable
instance Data.Aeson.FromJSON AccountBusinessProfileAnnualRevenue'NonNullable
instance Data.Aeson.ToJSON AccountBusinessProfileAnnualRevenue'NonNullable
data AccountBusinessProfileMinorityOwnedBusinessDesignation'NonNullable
instance Show AccountBusinessProfileMinorityOwnedBusinessDesignation'NonNullable
instance Eq AccountBusinessProfileMinorityOwnedBusinessDesignation'NonNullable
instance Data.Aeson.FromJSON AccountBusinessProfileMinorityOwnedBusinessDesignation'NonNullable
instance Data.Aeson.ToJSON AccountBusinessProfileMinorityOwnedBusinessDesignation'NonNullable
data AccountBusinessProfileSupportAddress'NonNullable
instance Show AccountBusinessProfileSupportAddress'NonNullable
instance Eq AccountBusinessProfileSupportAddress'NonNullable
instance Data.Aeson.FromJSON AccountBusinessProfileSupportAddress'NonNullable
instance Data.Aeson.ToJSON AccountBusinessProfileSupportAddress'NonNullable
