module StripeAPI.Types.AccountUnificationAccountController where
import qualified Data.Aeson
import qualified StripeAPI.Common
data AccountUnificationAccountController
instance Show AccountUnificationAccountController
instance Eq AccountUnificationAccountController
instance Data.Aeson.FromJSON AccountUnificationAccountController
instance Data.Aeson.ToJSON AccountUnificationAccountController
data AccountUnificationAccountControllerRequirementCollection'
instance Show AccountUnificationAccountControllerRequirementCollection'
instance Eq AccountUnificationAccountControllerRequirementCollection'
instance Data.Aeson.FromJSON AccountUnificationAccountControllerRequirementCollection'
instance Data.Aeson.ToJSON AccountUnificationAccountControllerRequirementCollection'
data AccountUnificationAccountControllerType'
instance Show AccountUnificationAccountControllerType'
instance Eq AccountUnificationAccountControllerType'
instance Data.Aeson.FromJSON AccountUnificationAccountControllerType'
instance Data.Aeson.ToJSON AccountUnificationAccountControllerType'
