module StripeAPI.Types.AccountUnificationAccountControllerLosses where
import qualified Data.Aeson
import qualified StripeAPI.Common
data AccountUnificationAccountControllerLosses
instance Show AccountUnificationAccountControllerLosses
instance Eq AccountUnificationAccountControllerLosses
instance Data.Aeson.FromJSON AccountUnificationAccountControllerLosses
instance Data.Aeson.ToJSON AccountUnificationAccountControllerLosses
data AccountUnificationAccountControllerLossesPayments'
instance Show AccountUnificationAccountControllerLossesPayments'
instance Eq AccountUnificationAccountControllerLossesPayments'
instance Data.Aeson.FromJSON AccountUnificationAccountControllerLossesPayments'
instance Data.Aeson.ToJSON AccountUnificationAccountControllerLossesPayments'
