{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema AccountUnificationAccountControllerStripeDashboard
module StripeAPI.Types.AccountUnificationAccountControllerStripeDashboard where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.account_unification_account_controller_stripe_dashboard@ in the specification.
data AccountUnificationAccountControllerStripeDashboard = AccountUnificationAccountControllerStripeDashboard
  { -- | type: A value indicating the Stripe dashboard this account has access to independent of the Connect application.
    accountUnificationAccountControllerStripeDashboardType :: AccountUnificationAccountControllerStripeDashboardType'
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON AccountUnificationAccountControllerStripeDashboard where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["type" Data.Aeson.Types.ToJSON..= accountUnificationAccountControllerStripeDashboardType obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["type" Data.Aeson.Types.ToJSON..= accountUnificationAccountControllerStripeDashboardType obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON AccountUnificationAccountControllerStripeDashboard where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "AccountUnificationAccountControllerStripeDashboard" (\obj -> GHC.Base.pure AccountUnificationAccountControllerStripeDashboard GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))

-- | Create a new 'AccountUnificationAccountControllerStripeDashboard' with all required fields.
mkAccountUnificationAccountControllerStripeDashboard ::
  -- | 'accountUnificationAccountControllerStripeDashboardType'
  AccountUnificationAccountControllerStripeDashboardType' ->
  AccountUnificationAccountControllerStripeDashboard
mkAccountUnificationAccountControllerStripeDashboard accountUnificationAccountControllerStripeDashboardType = AccountUnificationAccountControllerStripeDashboard {accountUnificationAccountControllerStripeDashboardType = accountUnificationAccountControllerStripeDashboardType}

-- | Defines the enum schema located at @components.schemas.account_unification_account_controller_stripe_dashboard.properties.type@ in the specification.
--
-- A value indicating the Stripe dashboard this account has access to independent of the Connect application.
data AccountUnificationAccountControllerStripeDashboardType'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    AccountUnificationAccountControllerStripeDashboardType'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    AccountUnificationAccountControllerStripeDashboardType'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"express"@
    AccountUnificationAccountControllerStripeDashboardType'EnumExpress
  | -- | Represents the JSON value @"full"@
    AccountUnificationAccountControllerStripeDashboardType'EnumFull
  | -- | Represents the JSON value @"none"@
    AccountUnificationAccountControllerStripeDashboardType'EnumNone
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON AccountUnificationAccountControllerStripeDashboardType' where
  toJSON (AccountUnificationAccountControllerStripeDashboardType'Other val) = val
  toJSON (AccountUnificationAccountControllerStripeDashboardType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (AccountUnificationAccountControllerStripeDashboardType'EnumExpress) = "express"
  toJSON (AccountUnificationAccountControllerStripeDashboardType'EnumFull) = "full"
  toJSON (AccountUnificationAccountControllerStripeDashboardType'EnumNone) = "none"

instance Data.Aeson.Types.FromJSON.FromJSON AccountUnificationAccountControllerStripeDashboardType' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "express" -> AccountUnificationAccountControllerStripeDashboardType'EnumExpress
          | val GHC.Classes.== "full" -> AccountUnificationAccountControllerStripeDashboardType'EnumFull
          | val GHC.Classes.== "none" -> AccountUnificationAccountControllerStripeDashboardType'EnumNone
          | GHC.Base.otherwise -> AccountUnificationAccountControllerStripeDashboardType'Other val
      )
