module StripeAPI.Types.AmazonPayUnderlyingPaymentMethodFundingDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data AmazonPayUnderlyingPaymentMethodFundingDetails
instance Show AmazonPayUnderlyingPaymentMethodFundingDetails
instance Eq AmazonPayUnderlyingPaymentMethodFundingDetails
instance Data.Aeson.FromJSON AmazonPayUnderlyingPaymentMethodFundingDetails
instance Data.Aeson.ToJSON AmazonPayUnderlyingPaymentMethodFundingDetails
data AmazonPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
instance Show AmazonPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
instance Eq AmazonPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
instance Data.Aeson.FromJSON AmazonPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
instance Data.Aeson.ToJSON AmazonPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
