module StripeAPI.Types.BillingBillResourceInvoicingParentsInvoiceParent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingParentsInvoiceParent
instance Show BillingBillResourceInvoicingParentsInvoiceParent
instance Eq BillingBillResourceInvoicingParentsInvoiceParent
instance Data.Aeson.FromJSON BillingBillResourceInvoicingParentsInvoiceParent
instance Data.Aeson.ToJSON BillingBillResourceInvoicingParentsInvoiceParent
data BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable
instance Show BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable
instance Eq BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable
data BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable
instance Show BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable
instance Eq BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable
data BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants
instance Show BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants
instance Eq BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants
instance Data.Aeson.FromJSON BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants
instance Data.Aeson.ToJSON BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants
data BillingBillResourceInvoicingParentsInvoiceParentType'
instance Show BillingBillResourceInvoicingParentsInvoiceParentType'
instance Eq BillingBillResourceInvoicingParentsInvoiceParentType'
instance Data.Aeson.FromJSON BillingBillResourceInvoicingParentsInvoiceParentType'
instance Data.Aeson.ToJSON BillingBillResourceInvoicingParentsInvoiceParentType'
