module StripeAPI.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable
