module StripeAPI.Types.BillingBillResourceInvoicingTaxesTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingTaxesTax
instance Show BillingBillResourceInvoicingTaxesTax
instance Eq BillingBillResourceInvoicingTaxesTax
instance Data.Aeson.FromJSON BillingBillResourceInvoicingTaxesTax
instance Data.Aeson.ToJSON BillingBillResourceInvoicingTaxesTax
data BillingBillResourceInvoicingTaxesTaxTaxBehavior'
instance Show BillingBillResourceInvoicingTaxesTaxTaxBehavior'
instance Eq BillingBillResourceInvoicingTaxesTaxTaxBehavior'
instance Data.Aeson.FromJSON BillingBillResourceInvoicingTaxesTaxTaxBehavior'
instance Data.Aeson.ToJSON BillingBillResourceInvoicingTaxesTaxTaxBehavior'
data BillingBillResourceInvoicingTaxesTaxTaxRateDetails'NonNullable
instance Show BillingBillResourceInvoicingTaxesTaxTaxRateDetails'NonNullable
instance Eq BillingBillResourceInvoicingTaxesTaxTaxRateDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingTaxesTaxTaxRateDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingTaxesTaxTaxRateDetails'NonNullable
data BillingBillResourceInvoicingTaxesTaxTaxabilityReason'
instance Show BillingBillResourceInvoicingTaxesTaxTaxabilityReason'
instance Eq BillingBillResourceInvoicingTaxesTaxTaxabilityReason'
instance Data.Aeson.FromJSON BillingBillResourceInvoicingTaxesTaxTaxabilityReason'
instance Data.Aeson.ToJSON BillingBillResourceInvoicingTaxesTaxTaxabilityReason'
