module StripeAPI.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParent
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParent
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParent
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParent
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParent
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullable
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullableCreditedItems'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullableCreditedItems'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullableCreditedItems'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullableCreditedItems'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParentProrationDetails'NonNullableCreditedItems'NonNullable
