{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema BillingBillResourceInvoicingParentsInvoiceParent
module StripeAPI.Types.BillingBillResourceInvoicingParentsInvoiceParent where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingParentsInvoiceQuoteParent
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingParentsInvoiceSubscriptionParent
import {-# SOURCE #-} StripeAPI.Types.Subscription
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_parents_invoice_parent@ in the specification.
data BillingBillResourceInvoicingParentsInvoiceParent = BillingBillResourceInvoicingParentsInvoiceParent
  { -- | quote_details: Details about the quote that generated this invoice
    billingBillResourceInvoicingParentsInvoiceParentQuoteDetails :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable)),
    -- | subscription_details: Details about the subscription that generated this invoice
    billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable)),
    -- | type: The type of parent that generated this invoice
    billingBillResourceInvoicingParentsInvoiceParentType :: BillingBillResourceInvoicingParentsInvoiceParentType'
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingParentsInvoiceParent where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("quote_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentQuoteDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails obj) : ["type" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingParentsInvoiceParentType obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("quote_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentQuoteDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails obj) : ["type" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingParentsInvoiceParentType obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingParentsInvoiceParent where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingParentsInvoiceParent" (\obj -> ((GHC.Base.pure BillingBillResourceInvoicingParentsInvoiceParent GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "quote_details")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription_details")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))

-- | Create a new 'BillingBillResourceInvoicingParentsInvoiceParent' with all required fields.
mkBillingBillResourceInvoicingParentsInvoiceParent ::
  -- | 'billingBillResourceInvoicingParentsInvoiceParentType'
  BillingBillResourceInvoicingParentsInvoiceParentType' ->
  BillingBillResourceInvoicingParentsInvoiceParent
mkBillingBillResourceInvoicingParentsInvoiceParent billingBillResourceInvoicingParentsInvoiceParentType =
  BillingBillResourceInvoicingParentsInvoiceParent
    { billingBillResourceInvoicingParentsInvoiceParentQuoteDetails = GHC.Maybe.Nothing,
      billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails = GHC.Maybe.Nothing,
      billingBillResourceInvoicingParentsInvoiceParentType = billingBillResourceInvoicingParentsInvoiceParentType
    }

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_parents_invoice_parent.properties.quote_details.anyOf@ in the specification.
--
-- Details about the quote that generated this invoice
data BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable = BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable
  { -- | quote: The quote that generated this invoice
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullableQuote :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("quote" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullableQuote obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("quote" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullableQuote obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable" (\obj -> GHC.Base.pure BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "quote"))

-- | Create a new 'BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable' with all required fields.
mkBillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable :: BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable
mkBillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable = BillingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullable {billingBillResourceInvoicingParentsInvoiceParentQuoteDetails'NonNullableQuote = GHC.Maybe.Nothing}

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_parents_invoice_parent.properties.subscription_details.anyOf@ in the specification.
--
-- Details about the subscription that generated this invoice
data BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable = BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable
  { -- | metadata: Set of [key-value pairs](https:\/\/stripe.com\/docs\/api\/metadata) defined as subscription metadata when an invoice is created. Becomes an immutable snapshot of the subscription metadata at the time of invoice finalization.
    --  *Note: This attribute is populated only for invoices created on or after June 29, 2023.*
    billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableMetadata :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Aeson.Types.Internal.Object)),
    -- | subscription: The subscription that generated this invoice
    billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription :: (GHC.Maybe.Maybe BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants),
    -- | subscription_proration_date: Only set for upcoming invoices that preview prorations. The time used to calculate prorations.
    billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscriptionProrationDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_proration_date" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscriptionProrationDate obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_proration_date" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscriptionProrationDate obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable" (\obj -> ((GHC.Base.pure BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "metadata")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription_proration_date"))

-- | Create a new 'BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable' with all required fields.
mkBillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable :: BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable
mkBillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable =
  BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullable
    { billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableMetadata = GHC.Maybe.Nothing,
      billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription = GHC.Maybe.Nothing,
      billingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscriptionProrationDate = GHC.Maybe.Nothing
    }

-- | Defines the oneOf schema located at @components.schemas.billing_bill_resource_invoicing_parents_invoice_parent.properties.subscription_details.anyOf.properties.subscription.anyOf@ in the specification.
--
-- The subscription that generated this invoice
data BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants
  = BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Text Data.Text.Internal.Text
  | BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Subscription Subscription
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants where
  toJSON (BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Text a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Subscription a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Variants where
  parseJSON val = case (BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((BillingBillResourceInvoicingParentsInvoiceParentSubscriptionDetails'NonNullableSubscription'Subscription Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
    Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
    Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a

-- | Defines the enum schema located at @components.schemas.billing_bill_resource_invoicing_parents_invoice_parent.properties.type@ in the specification.
--
-- The type of parent that generated this invoice
data BillingBillResourceInvoicingParentsInvoiceParentType'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    BillingBillResourceInvoicingParentsInvoiceParentType'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    BillingBillResourceInvoicingParentsInvoiceParentType'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"quote_details"@
    BillingBillResourceInvoicingParentsInvoiceParentType'EnumQuoteDetails
  | -- | Represents the JSON value @"subscription_details"@
    BillingBillResourceInvoicingParentsInvoiceParentType'EnumSubscriptionDetails
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingParentsInvoiceParentType' where
  toJSON (BillingBillResourceInvoicingParentsInvoiceParentType'Other val) = val
  toJSON (BillingBillResourceInvoicingParentsInvoiceParentType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (BillingBillResourceInvoicingParentsInvoiceParentType'EnumQuoteDetails) = "quote_details"
  toJSON (BillingBillResourceInvoicingParentsInvoiceParentType'EnumSubscriptionDetails) = "subscription_details"

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingParentsInvoiceParentType' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "quote_details" -> BillingBillResourceInvoicingParentsInvoiceParentType'EnumQuoteDetails
          | val GHC.Classes.== "subscription_details" -> BillingBillResourceInvoicingParentsInvoiceParentType'EnumSubscriptionDetails
          | GHC.Base.otherwise -> BillingBillResourceInvoicingParentsInvoiceParentType'Other val
      )
