{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema BillingCreditGrantsResourceBalanceCreditsApplied
module StripeAPI.Types.BillingCreditGrantsResourceBalanceCreditsApplied where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Invoice
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.billing_credit_grants_resource_balance_credits_applied@ in the specification.
data BillingCreditGrantsResourceBalanceCreditsApplied = BillingCreditGrantsResourceBalanceCreditsApplied
  { -- | invoice: The invoice to which the billing credits were applied.
    billingCreditGrantsResourceBalanceCreditsAppliedInvoice :: BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants,
    -- | invoice_line_item: The invoice line item to which the billing credits were applied.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingCreditGrantsResourceBalanceCreditsAppliedInvoiceLineItem :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingCreditGrantsResourceBalanceCreditsApplied where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["invoice" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceBalanceCreditsAppliedInvoice obj] : ["invoice_line_item" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceBalanceCreditsAppliedInvoiceLineItem obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["invoice" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceBalanceCreditsAppliedInvoice obj] : ["invoice_line_item" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceBalanceCreditsAppliedInvoiceLineItem obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingCreditGrantsResourceBalanceCreditsApplied where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingCreditGrantsResourceBalanceCreditsApplied" (\obj -> (GHC.Base.pure BillingCreditGrantsResourceBalanceCreditsApplied GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "invoice")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "invoice_line_item"))

-- | Create a new 'BillingCreditGrantsResourceBalanceCreditsApplied' with all required fields.
mkBillingCreditGrantsResourceBalanceCreditsApplied ::
  -- | 'billingCreditGrantsResourceBalanceCreditsAppliedInvoice'
  BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants ->
  -- | 'billingCreditGrantsResourceBalanceCreditsAppliedInvoiceLineItem'
  Data.Text.Internal.Text ->
  BillingCreditGrantsResourceBalanceCreditsApplied
mkBillingCreditGrantsResourceBalanceCreditsApplied billingCreditGrantsResourceBalanceCreditsAppliedInvoice billingCreditGrantsResourceBalanceCreditsAppliedInvoiceLineItem =
  BillingCreditGrantsResourceBalanceCreditsApplied
    { billingCreditGrantsResourceBalanceCreditsAppliedInvoice = billingCreditGrantsResourceBalanceCreditsAppliedInvoice,
      billingCreditGrantsResourceBalanceCreditsAppliedInvoiceLineItem = billingCreditGrantsResourceBalanceCreditsAppliedInvoiceLineItem
    }

-- | Defines the oneOf schema located at @components.schemas.billing_credit_grants_resource_balance_credits_applied.properties.invoice.anyOf@ in the specification.
--
-- The invoice to which the billing credits were applied.
data BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants
  = BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Text Data.Text.Internal.Text
  | BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Invoice Invoice
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants where
  toJSON (BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Text a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Invoice a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants where
  parseJSON val = case (BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Invoice Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
    Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
    Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a
