module StripeAPI.Types.BillingBillResourceInvoicingParentsInvoiceSubscriptionParent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingParentsInvoiceSubscriptionParent
instance Show BillingBillResourceInvoicingParentsInvoiceSubscriptionParent
instance Eq BillingBillResourceInvoicingParentsInvoiceSubscriptionParent
instance Data.Aeson.FromJSON BillingBillResourceInvoicingParentsInvoiceSubscriptionParent
instance Data.Aeson.ToJSON BillingBillResourceInvoicingParentsInvoiceSubscriptionParent
data BillingBillResourceInvoicingParentsInvoiceSubscriptionParentSubscription'Variants
instance Show BillingBillResourceInvoicingParentsInvoiceSubscriptionParentSubscription'Variants
instance Eq BillingBillResourceInvoicingParentsInvoiceSubscriptionParentSubscription'Variants
instance Data.Aeson.FromJSON BillingBillResourceInvoicingParentsInvoiceSubscriptionParentSubscription'Variants
instance Data.Aeson.ToJSON BillingBillResourceInvoicingParentsInvoiceSubscriptionParentSubscription'Variants
