module StripeAPI.Types.BillingCreditGrantsResourceBalanceCreditsApplied where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingCreditGrantsResourceBalanceCreditsApplied
instance Show BillingCreditGrantsResourceBalanceCreditsApplied
instance Eq BillingCreditGrantsResourceBalanceCreditsApplied
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceCreditsApplied
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceCreditsApplied
data BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants
instance Show BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants
instance Eq BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceCreditsAppliedInvoice'Variants
