{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
module StripeAPI.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingLinesCommonCreditedItems
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingLinesCommonProrationDetails
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParent
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent@ in the specification.
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
  { -- | invoice_item_details: Details about the invoice item that generated this line item
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable)),
    -- | subscription_item_details: Details about the subscription item that generated this line item
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable)),
    -- | type: The type of parent that generated this line item
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentType :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_item_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_item_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails obj) : ["type" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingLinesParentsInvoiceLineItemParentType obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_item_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_item_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails obj) : ["type" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingLinesParentsInvoiceLineItemParentType obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent" (\obj -> ((GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_item_details")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription_item_details")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParent ::
  -- | 'billingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType' ->
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParent billingBillResourceInvoicingLinesParentsInvoiceLineItemParentType =
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
    { billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentType = billingBillResourceInvoicingLinesParentsInvoiceLineItemParentType
    }

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent.properties.invoice_item_details.anyOf@ in the specification.
--
-- Details about the invoice item that generated this line item
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable
  { -- | invoice_item: The invoice item that generated this line item
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableInvoiceItem :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | proration: Whether this is a proration
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProration :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | proration_details: Additional details for proration line items
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable)),
    -- | subscription: The subscription that the invoice item belongs to
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableSubscription :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_item" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableInvoiceItem obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProration obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableSubscription obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_item" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableInvoiceItem obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProration obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableSubscription obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable" (\obj -> (((GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_item")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "proration")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "proration_details")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable =
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable
    { billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableInvoiceItem = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProration = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableSubscription = GHC.Maybe.Nothing
    }

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent.properties.invoice_item_details.anyOf.properties.proration_details.anyOf@ in the specification.
--
-- Additional details for proration line items
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable
  { -- | credited_items: For a credit proration \`line_item\`, the original debit line_items to which the credit proration applies.
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("credited_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("credited_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable" (\obj -> GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "credited_items"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable {billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems = GHC.Maybe.Nothing}

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent.properties.invoice_item_details.anyOf.properties.proration_details.anyOf.properties.credited_items.anyOf@ in the specification.
--
-- For a credit proration \\\`line_item\\\`, the original debit line_items to which the credit proration applies.
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
  { -- | invoice: Invoice containing the credited invoice line items
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoice :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | invoice_line_items: Credited invoice line items
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems :: (GHC.Maybe.Maybe [Data.Text.Internal.Text])
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable" (\obj -> (GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_line_items"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable =
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
    { billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoice = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems = GHC.Maybe.Nothing
    }

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent.properties.subscription_item_details.anyOf@ in the specification.
--
-- Details about the subscription item that generated this line item
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable
  { -- | invoice_item: The invoice item that generated this line item
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableInvoiceItem :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | proration: Whether this is a proration
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProration :: (GHC.Maybe.Maybe GHC.Types.Bool),
    -- | proration_details: Additional details for proration line items
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable)),
    -- | subscription: The subscription that the subscription item belongs to
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableSubscription :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | subscription_item: The subscription item that generated this line item
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableSubscriptionItem :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_item" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableInvoiceItem obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProration obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableSubscription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_item" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableSubscriptionItem obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_item" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableInvoiceItem obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProration obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableSubscription obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_item" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableSubscriptionItem obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable" (\obj -> ((((GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_item")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "proration")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "proration_details")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription_item"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable =
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable
    { billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableInvoiceItem = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProration = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableSubscription = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableSubscriptionItem = GHC.Maybe.Nothing
    }

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent.properties.subscription_item_details.anyOf.properties.proration_details.anyOf@ in the specification.
--
-- Additional details for proration line items
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable
  { -- | credited_items: For a credit proration \`line_item\`, the original debit line_items to which the credit proration applies.
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("credited_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("credited_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable" (\obj -> GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "credited_items"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable {billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems = GHC.Maybe.Nothing}

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent.properties.subscription_item_details.anyOf.properties.proration_details.anyOf.properties.credited_items.anyOf@ in the specification.
--
-- For a credit proration \\\`line_item\\\`, the original debit line_items to which the credit proration applies.
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
  { -- | invoice: Invoice containing the credited invoice line items
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoice :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | invoice_line_items: Credited invoice line items
    billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems :: (GHC.Maybe.Maybe [Data.Text.Internal.Text])
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable" (\obj -> (GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_line_items"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable =
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
    { billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoice = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems = GHC.Maybe.Nothing
    }

-- | Defines the enum schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent.properties.type@ in the specification.
--
-- The type of parent that generated this line item
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"invoice_item_details"@
    BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'EnumInvoiceItemDetails
  | -- | Represents the JSON value @"subscription_item_details"@
    BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'EnumSubscriptionItemDetails
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType' where
  toJSON (BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'Other val) = val
  toJSON (BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'EnumInvoiceItemDetails) = "invoice_item_details"
  toJSON (BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'EnumSubscriptionItemDetails) = "subscription_item_details"

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "invoice_item_details" -> BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'EnumInvoiceItemDetails
          | val GHC.Classes.== "subscription_item_details" -> BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'EnumSubscriptionItemDetails
          | GHC.Base.otherwise -> BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'Other val
      )
