{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema BillingCreditGrantsResourceBalanceCredit
module StripeAPI.Types.BillingCreditGrantsResourceBalanceCredit where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.BillingCreditGrantsResourceAmount
import {-# SOURCE #-} StripeAPI.Types.BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided
import {-# SOURCE #-} StripeAPI.Types.Invoice
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.billing_credit_grants_resource_balance_credit@ in the specification.
data BillingCreditGrantsResourceBalanceCredit = BillingCreditGrantsResourceBalanceCredit
  { -- | amount:
    billingCreditGrantsResourceBalanceCreditAmount :: BillingCreditGrantsResourceAmount,
    -- | credits_application_invoice_voided: Details of the invoice to which the reinstated credits were originally applied. Only present if \`type\` is \`credits_application_invoice_voided\`.
    billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable)),
    -- | type: The type of credit transaction.
    billingCreditGrantsResourceBalanceCreditType :: BillingCreditGrantsResourceBalanceCreditType'
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingCreditGrantsResourceBalanceCredit where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["amount" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceBalanceCreditAmount obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("credits_application_invoice_voided" Data.Aeson.Types.ToJSON..=)) (billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided obj) : ["type" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceBalanceCreditType obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["amount" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceBalanceCreditAmount obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("credits_application_invoice_voided" Data.Aeson.Types.ToJSON..=)) (billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided obj) : ["type" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceBalanceCreditType obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingCreditGrantsResourceBalanceCredit where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingCreditGrantsResourceBalanceCredit" (\obj -> ((GHC.Base.pure BillingCreditGrantsResourceBalanceCredit GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "amount")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "credits_application_invoice_voided")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))

-- | Create a new 'BillingCreditGrantsResourceBalanceCredit' with all required fields.
mkBillingCreditGrantsResourceBalanceCredit ::
  -- | 'billingCreditGrantsResourceBalanceCreditAmount'
  BillingCreditGrantsResourceAmount ->
  -- | 'billingCreditGrantsResourceBalanceCreditType'
  BillingCreditGrantsResourceBalanceCreditType' ->
  BillingCreditGrantsResourceBalanceCredit
mkBillingCreditGrantsResourceBalanceCredit billingCreditGrantsResourceBalanceCreditAmount billingCreditGrantsResourceBalanceCreditType =
  BillingCreditGrantsResourceBalanceCredit
    { billingCreditGrantsResourceBalanceCreditAmount = billingCreditGrantsResourceBalanceCreditAmount,
      billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided = GHC.Maybe.Nothing,
      billingCreditGrantsResourceBalanceCreditType = billingCreditGrantsResourceBalanceCreditType
    }

-- | Defines the object schema located at @components.schemas.billing_credit_grants_resource_balance_credit.properties.credits_application_invoice_voided.anyOf@ in the specification.
--
-- Details of the invoice to which the reinstated credits were originally applied. Only present if \\\`type\\\` is \\\`credits_application_invoice_voided\\\`.
data BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable = BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable
  { -- | invoice: The invoice to which the reinstated billing credits were originally applied.
    billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice :: (GHC.Maybe.Maybe BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants),
    -- | invoice_line_item: The invoice line item to which the reinstated billing credits were originally applied.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoiceLineItem :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice" Data.Aeson.Types.ToJSON..=)) (billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_item" Data.Aeson.Types.ToJSON..=)) (billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoiceLineItem obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice" Data.Aeson.Types.ToJSON..=)) (billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_item" Data.Aeson.Types.ToJSON..=)) (billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoiceLineItem obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable" (\obj -> (GHC.Base.pure BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_line_item"))

-- | Create a new 'BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable' with all required fields.
mkBillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable :: BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable
mkBillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable =
  BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable
    { billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice = GHC.Maybe.Nothing,
      billingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoiceLineItem = GHC.Maybe.Nothing
    }

-- | Defines the oneOf schema located at @components.schemas.billing_credit_grants_resource_balance_credit.properties.credits_application_invoice_voided.anyOf.properties.invoice.anyOf@ in the specification.
--
-- The invoice to which the reinstated billing credits were originally applied.
data BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants
  = BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Text Data.Text.Internal.Text
  | BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Invoice Invoice
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants where
  toJSON (BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Text a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Invoice a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants where
  parseJSON val = case (BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Text Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Invoice Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
    Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
    Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a

-- | Defines the enum schema located at @components.schemas.billing_credit_grants_resource_balance_credit.properties.type@ in the specification.
--
-- The type of credit transaction.
data BillingCreditGrantsResourceBalanceCreditType'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    BillingCreditGrantsResourceBalanceCreditType'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    BillingCreditGrantsResourceBalanceCreditType'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"credits_application_invoice_voided"@
    BillingCreditGrantsResourceBalanceCreditType'EnumCreditsApplicationInvoiceVoided
  | -- | Represents the JSON value @"credits_granted"@
    BillingCreditGrantsResourceBalanceCreditType'EnumCreditsGranted
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON BillingCreditGrantsResourceBalanceCreditType' where
  toJSON (BillingCreditGrantsResourceBalanceCreditType'Other val) = val
  toJSON (BillingCreditGrantsResourceBalanceCreditType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (BillingCreditGrantsResourceBalanceCreditType'EnumCreditsApplicationInvoiceVoided) = "credits_application_invoice_voided"
  toJSON (BillingCreditGrantsResourceBalanceCreditType'EnumCreditsGranted) = "credits_granted"

instance Data.Aeson.Types.FromJSON.FromJSON BillingCreditGrantsResourceBalanceCreditType' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "credits_application_invoice_voided" -> BillingCreditGrantsResourceBalanceCreditType'EnumCreditsApplicationInvoiceVoided
          | val GHC.Classes.== "credits_granted" -> BillingCreditGrantsResourceBalanceCreditType'EnumCreditsGranted
          | GHC.Base.otherwise -> BillingCreditGrantsResourceBalanceCreditType'Other val
      )
