module StripeAPI.Types.BillingBillResourceInvoicingLinesCommonProrationDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingLinesCommonProrationDetails
instance Show BillingBillResourceInvoicingLinesCommonProrationDetails
instance Eq BillingBillResourceInvoicingLinesCommonProrationDetails
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesCommonProrationDetails
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesCommonProrationDetails
data BillingBillResourceInvoicingLinesCommonProrationDetailsCreditedItems'NonNullable
instance Show BillingBillResourceInvoicingLinesCommonProrationDetailsCreditedItems'NonNullable
instance Eq BillingBillResourceInvoicingLinesCommonProrationDetailsCreditedItems'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesCommonProrationDetailsCreditedItems'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesCommonProrationDetailsCreditedItems'NonNullable
