module StripeAPI.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullable
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullable
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentInvoiceItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullable
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullable
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentSubscriptionItemDetails'NonNullableProrationDetails'NonNullableCreditedItems'NonNullable
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'
instance Show BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'
instance Eq BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemParentType'
