module StripeAPI.Types.BillingBillResourceInvoicingLinesCommonCreditedItems where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingLinesCommonCreditedItems
instance Show BillingBillResourceInvoicingLinesCommonCreditedItems
instance Eq BillingBillResourceInvoicingLinesCommonCreditedItems
instance Data.Aeson.FromJSON BillingBillResourceInvoicingLinesCommonCreditedItems
instance Data.Aeson.ToJSON BillingBillResourceInvoicingLinesCommonCreditedItems
