module StripeAPI.Types.BillingCreditGrantsResourceBalanceCredit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingCreditGrantsResourceBalanceCredit
instance Show BillingCreditGrantsResourceBalanceCredit
instance Eq BillingCreditGrantsResourceBalanceCredit
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceCredit
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceCredit
data BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable
instance Show BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable
instance Eq BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullable
data BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants
instance Show BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants
instance Eq BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided'NonNullableInvoice'Variants
data BillingCreditGrantsResourceBalanceCreditType'
instance Show BillingCreditGrantsResourceBalanceCreditType'
instance Eq BillingCreditGrantsResourceBalanceCreditType'
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceCreditType'
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceCreditType'
