module StripeAPI.Types.BillingBillResourceInvoicingParentsInvoiceQuoteParent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingParentsInvoiceQuoteParent
instance Show BillingBillResourceInvoicingParentsInvoiceQuoteParent
instance Eq BillingBillResourceInvoicingParentsInvoiceQuoteParent
instance Data.Aeson.FromJSON BillingBillResourceInvoicingParentsInvoiceQuoteParent
instance Data.Aeson.ToJSON BillingBillResourceInvoicingParentsInvoiceQuoteParent
