module StripeAPI.Types.BillingClocksResourceStatusDetailsAdvancingStatusDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingClocksResourceStatusDetailsAdvancingStatusDetails
instance Show BillingClocksResourceStatusDetailsAdvancingStatusDetails
instance Eq BillingClocksResourceStatusDetailsAdvancingStatusDetails
instance Data.Aeson.FromJSON BillingClocksResourceStatusDetailsAdvancingStatusDetails
instance Data.Aeson.ToJSON BillingClocksResourceStatusDetailsAdvancingStatusDetails
