{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema BillingBillResourceInvoicingPricingPricingPriceDetails
module StripeAPI.Types.BillingBillResourceInvoicingPricingPricingPriceDetails where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_pricing_pricing_price_details@ in the specification.
data BillingBillResourceInvoicingPricingPricingPriceDetails = BillingBillResourceInvoicingPricingPricingPriceDetails
  { -- | price: The ID of the price this item is associated with.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingPricingPricingPriceDetailsPrice :: Data.Text.Internal.Text,
    -- | product: The ID of the product this item is associated with.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingPricingPricingPriceDetailsProduct :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingPricingPricingPriceDetails where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["price" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingPricingPricingPriceDetailsPrice obj] : ["product" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingPricingPricingPriceDetailsProduct obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["price" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingPricingPricingPriceDetailsPrice obj] : ["product" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingPricingPricingPriceDetailsProduct obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingPricingPricingPriceDetails where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingPricingPricingPriceDetails" (\obj -> (GHC.Base.pure BillingBillResourceInvoicingPricingPricingPriceDetails GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "price")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "product"))

-- | Create a new 'BillingBillResourceInvoicingPricingPricingPriceDetails' with all required fields.
mkBillingBillResourceInvoicingPricingPricingPriceDetails ::
  -- | 'billingBillResourceInvoicingPricingPricingPriceDetailsPrice'
  Data.Text.Internal.Text ->
  -- | 'billingBillResourceInvoicingPricingPricingPriceDetailsProduct'
  Data.Text.Internal.Text ->
  BillingBillResourceInvoicingPricingPricingPriceDetails
mkBillingBillResourceInvoicingPricingPricingPriceDetails billingBillResourceInvoicingPricingPricingPriceDetailsPrice billingBillResourceInvoicingPricingPricingPriceDetailsProduct =
  BillingBillResourceInvoicingPricingPricingPriceDetails
    { billingBillResourceInvoicingPricingPricingPriceDetailsPrice = billingBillResourceInvoicingPricingPricingPriceDetailsPrice,
      billingBillResourceInvoicingPricingPricingPriceDetailsProduct = billingBillResourceInvoicingPricingPricingPriceDetailsProduct
    }
