module StripeAPI.Types.BillingBillResourceInvoicingPricingPricingPriceDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingBillResourceInvoicingPricingPricingPriceDetails
instance Show BillingBillResourceInvoicingPricingPricingPriceDetails
instance Eq BillingBillResourceInvoicingPricingPricingPriceDetails
instance Data.Aeson.FromJSON BillingBillResourceInvoicingPricingPricingPriceDetails
instance Data.Aeson.ToJSON BillingBillResourceInvoicingPricingPricingPriceDetails
