module StripeAPI.Types.BillingCreditGrantsResourceBalanceDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingCreditGrantsResourceBalanceDebit
instance Show BillingCreditGrantsResourceBalanceDebit
instance Eq BillingCreditGrantsResourceBalanceDebit
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceDebit
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceDebit
data BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullable
instance Show BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullable
instance Eq BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullable
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullable
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullable
data BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullableInvoice'Variants
instance Show BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullableInvoice'Variants
instance Eq BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullableInvoice'Variants
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullableInvoice'Variants
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceDebitCreditsApplied'NonNullableInvoice'Variants
data BillingCreditGrantsResourceBalanceDebitType'
instance Show BillingCreditGrantsResourceBalanceDebitType'
instance Eq BillingCreditGrantsResourceBalanceDebitType'
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceDebitType'
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceDebitType'
