{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema BillingCreditGrantsResourceMonetaryAmount
module StripeAPI.Types.BillingCreditGrantsResourceMonetaryAmount where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.billing_credit_grants_resource_monetary_amount@ in the specification.
data BillingCreditGrantsResourceMonetaryAmount = BillingCreditGrantsResourceMonetaryAmount
  { -- | currency: Three-letter [ISO currency code](https:\/\/www.iso.org\/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https:\/\/stripe.com\/docs\/currencies).
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingCreditGrantsResourceMonetaryAmountCurrency :: Data.Text.Internal.Text,
    -- | value: A positive integer representing the amount.
    billingCreditGrantsResourceMonetaryAmountValue :: GHC.Types.Int
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingCreditGrantsResourceMonetaryAmount where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["currency" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceMonetaryAmountCurrency obj] : ["value" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceMonetaryAmountValue obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["currency" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceMonetaryAmountCurrency obj] : ["value" Data.Aeson.Types.ToJSON..= billingCreditGrantsResourceMonetaryAmountValue obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingCreditGrantsResourceMonetaryAmount where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingCreditGrantsResourceMonetaryAmount" (\obj -> (GHC.Base.pure BillingCreditGrantsResourceMonetaryAmount GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "currency")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "value"))

-- | Create a new 'BillingCreditGrantsResourceMonetaryAmount' with all required fields.
mkBillingCreditGrantsResourceMonetaryAmount ::
  -- | 'billingCreditGrantsResourceMonetaryAmountCurrency'
  Data.Text.Internal.Text ->
  -- | 'billingCreditGrantsResourceMonetaryAmountValue'
  GHC.Types.Int ->
  BillingCreditGrantsResourceMonetaryAmount
mkBillingCreditGrantsResourceMonetaryAmount billingCreditGrantsResourceMonetaryAmountCurrency billingCreditGrantsResourceMonetaryAmountValue =
  BillingCreditGrantsResourceMonetaryAmount
    { billingCreditGrantsResourceMonetaryAmountCurrency = billingCreditGrantsResourceMonetaryAmountCurrency,
      billingCreditGrantsResourceMonetaryAmountValue = billingCreditGrantsResourceMonetaryAmountValue
    }
