{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
module StripeAPI.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingLinesCommonCreditedItems
import {-# SOURCE #-} StripeAPI.Types.BillingBillResourceInvoicingLinesCommonProrationDetails
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parent@ in the specification.
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent = BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
  { -- | invoice_item: The invoice item that generated this line item
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentInvoiceItem :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | proration: Whether this is a proration
    billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProration :: GHC.Types.Bool,
    -- | proration_details: Additional details for proration line items
    billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable)),
    -- | subscription: The subscription that the subscription item belongs to
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscription :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable Data.Text.Internal.Text)),
    -- | subscription_item: The subscription item that generated this line item
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscriptionItem :: Data.Text.Internal.Text
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_item" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentInvoiceItem obj) : ["proration" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProration obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscription obj) : ["subscription_item" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscriptionItem obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_item" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentInvoiceItem obj) : ["proration" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProration obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("proration_details" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscription obj) : ["subscription_item" Data.Aeson.Types.ToJSON..= billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscriptionItem obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent" (\obj -> ((((GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_item")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "proration")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "proration_details")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "subscription_item"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent ::
  -- | 'billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProration'
  GHC.Types.Bool ->
  -- | 'billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscriptionItem'
  Data.Text.Internal.Text ->
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProration billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscriptionItem =
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent
    { billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentInvoiceItem = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProration = billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProration,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscription = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscriptionItem = billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentSubscriptionItem
    }

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parent.properties.proration_details.anyOf@ in the specification.
--
-- Additional details for proration line items
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable
  { -- | credited_items: For a credit proration \`line_item\`, the original debit line_items to which the credit proration applies.
    billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("credited_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("credited_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable" (\obj -> GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "credited_items"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullable {billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems = GHC.Maybe.Nothing}

-- | Defines the object schema located at @components.schemas.billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parent.properties.proration_details.anyOf.properties.credited_items.anyOf@ in the specification.
--
-- For a credit proration \\\`line_item\\\`, the original debit line_items to which the credit proration applies.
data BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable = BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable
  { -- | invoice: Invoice containing the credited invoice line items
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullableInvoice :: (GHC.Maybe.Maybe Data.Text.Internal.Text),
    -- | invoice_line_items: Credited invoice line items
    billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems :: (GHC.Maybe.Maybe [Data.Text.Internal.Text])
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullableInvoice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullableInvoice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("invoice_line_items" Data.Aeson.Types.ToJSON..=)) (billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable" (\obj -> (GHC.Base.pure BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "invoice_line_items"))

-- | Create a new 'BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable' with all required fields.
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable :: BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable
mkBillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable =
  BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullable
    { billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullableInvoice = GHC.Maybe.Nothing,
      billingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParentProrationDetails'NonNullableCreditedItems'NonNullableInvoiceLineItems = GHC.Maybe.Nothing
    }
