module StripeAPI.Types.BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided where
import qualified Data.Aeson
import qualified StripeAPI.Common
data BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided
instance Show BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided
instance Eq BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided
data BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice'Variants
instance Show BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice'Variants
instance Eq BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice'Variants
instance Data.Aeson.FromJSON BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice'Variants
instance Data.Aeson.ToJSON BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice'Variants
