module StripeAPI.Types.CheckoutSepaDebitPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutSepaDebitPaymentMethodOptions
instance Show CheckoutSepaDebitPaymentMethodOptions
instance Eq CheckoutSepaDebitPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutSepaDebitPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutSepaDebitPaymentMethodOptions
data CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutSepaDebitPaymentMethodOptionsSetupFutureUsage'
