module StripeAPI.Types.CheckoutBacsDebitPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutBacsDebitPaymentMethodOptions
instance Show CheckoutBacsDebitPaymentMethodOptions
instance Eq CheckoutBacsDebitPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutBacsDebitPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutBacsDebitPaymentMethodOptions
data CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutBacsDebitPaymentMethodOptionsSetupFutureUsage'
