module StripeAPI.Types.CheckoutRevolutPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutRevolutPayPaymentMethodOptions
instance Show CheckoutRevolutPayPaymentMethodOptions
instance Eq CheckoutRevolutPayPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutRevolutPayPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutRevolutPayPaymentMethodOptions
data CheckoutRevolutPayPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutRevolutPayPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutRevolutPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutRevolutPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutRevolutPayPaymentMethodOptionsSetupFutureUsage'
