module StripeAPI.Types.CheckoutAcssDebitPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutAcssDebitPaymentMethodOptions
instance Show CheckoutAcssDebitPaymentMethodOptions
instance Eq CheckoutAcssDebitPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutAcssDebitPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutAcssDebitPaymentMethodOptions
data CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance Show CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance Eq CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance Data.Aeson.FromJSON CheckoutAcssDebitPaymentMethodOptionsCurrency'
instance Data.Aeson.ToJSON CheckoutAcssDebitPaymentMethodOptionsCurrency'
data CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutAcssDebitPaymentMethodOptionsSetupFutureUsage'
data CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance Show CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance Eq CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance Data.Aeson.FromJSON CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
instance Data.Aeson.ToJSON CheckoutAcssDebitPaymentMethodOptionsVerificationMethod'
