module StripeAPI.Types.CheckoutCashappPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutCashappPaymentMethodOptions
instance Show CheckoutCashappPaymentMethodOptions
instance Eq CheckoutCashappPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutCashappPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutCashappPaymentMethodOptions
data CheckoutCashappPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutCashappPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutCashappPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutCashappPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutCashappPaymentMethodOptionsSetupFutureUsage'
