module StripeAPI.Types.CheckoutSamsungPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutSamsungPayPaymentMethodOptions
instance Show CheckoutSamsungPayPaymentMethodOptions
instance Eq CheckoutSamsungPayPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutSamsungPayPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutSamsungPayPaymentMethodOptions
data CheckoutSamsungPayPaymentMethodOptionsCaptureMethod'
instance Show CheckoutSamsungPayPaymentMethodOptionsCaptureMethod'
instance Eq CheckoutSamsungPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON CheckoutSamsungPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON CheckoutSamsungPayPaymentMethodOptionsCaptureMethod'
