module StripeAPI.Types.CheckoutCustomerBalancePaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutCustomerBalancePaymentMethodOptions
instance Show CheckoutCustomerBalancePaymentMethodOptions
instance Eq CheckoutCustomerBalancePaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutCustomerBalancePaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutCustomerBalancePaymentMethodOptions
data CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
instance Show CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
instance Eq CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
instance Data.Aeson.FromJSON CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
instance Data.Aeson.ToJSON CheckoutCustomerBalancePaymentMethodOptionsFundingType'NonNullable
data CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutCustomerBalancePaymentMethodOptionsSetupFutureUsage'
