module StripeAPI.Types.CheckoutPaymentMethodOptionsMandateOptionsBacsDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutPaymentMethodOptionsMandateOptionsBacsDebit
instance Show CheckoutPaymentMethodOptionsMandateOptionsBacsDebit
instance Eq CheckoutPaymentMethodOptionsMandateOptionsBacsDebit
instance Data.Aeson.FromJSON CheckoutPaymentMethodOptionsMandateOptionsBacsDebit
instance Data.Aeson.ToJSON CheckoutPaymentMethodOptionsMandateOptionsBacsDebit
