module StripeAPI.Types.CheckoutAcssDebitMandateOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutAcssDebitMandateOptions
instance Show CheckoutAcssDebitMandateOptions
instance Eq CheckoutAcssDebitMandateOptions
instance Data.Aeson.FromJSON CheckoutAcssDebitMandateOptions
instance Data.Aeson.ToJSON CheckoutAcssDebitMandateOptions
data CheckoutAcssDebitMandateOptionsDefaultFor'
instance Show CheckoutAcssDebitMandateOptionsDefaultFor'
instance Eq CheckoutAcssDebitMandateOptionsDefaultFor'
instance Data.Aeson.FromJSON CheckoutAcssDebitMandateOptionsDefaultFor'
instance Data.Aeson.ToJSON CheckoutAcssDebitMandateOptionsDefaultFor'
data CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
instance Show CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
instance Eq CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
instance Data.Aeson.FromJSON CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
instance Data.Aeson.ToJSON CheckoutAcssDebitMandateOptionsPaymentSchedule'NonNullable
data CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
instance Show CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
instance Eq CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
instance Data.Aeson.FromJSON CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
instance Data.Aeson.ToJSON CheckoutAcssDebitMandateOptionsTransactionType'NonNullable
