module StripeAPI.Types.CheckoutPaymentMethodOptionsMandateOptionsSepaDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutPaymentMethodOptionsMandateOptionsSepaDebit
instance Show CheckoutPaymentMethodOptionsMandateOptionsSepaDebit
instance Eq CheckoutPaymentMethodOptionsMandateOptionsSepaDebit
instance Data.Aeson.FromJSON CheckoutPaymentMethodOptionsMandateOptionsSepaDebit
instance Data.Aeson.ToJSON CheckoutPaymentMethodOptionsMandateOptionsSepaDebit
