{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema CheckoutPaycoPaymentMethodOptions
module StripeAPI.Types.CheckoutPaycoPaymentMethodOptions where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.checkout_payco_payment_method_options@ in the specification.
data CheckoutPaycoPaymentMethodOptions = CheckoutPaycoPaymentMethodOptions
  { -- | capture_method: Controls when the funds will be captured from the customer\'s account.
    checkoutPaycoPaymentMethodOptionsCaptureMethod :: (GHC.Maybe.Maybe CheckoutPaycoPaymentMethodOptionsCaptureMethod')
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON CheckoutPaycoPaymentMethodOptions where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("capture_method" Data.Aeson.Types.ToJSON..=)) (checkoutPaycoPaymentMethodOptionsCaptureMethod obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("capture_method" Data.Aeson.Types.ToJSON..=)) (checkoutPaycoPaymentMethodOptionsCaptureMethod obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON CheckoutPaycoPaymentMethodOptions where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "CheckoutPaycoPaymentMethodOptions" (\obj -> GHC.Base.pure CheckoutPaycoPaymentMethodOptions GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "capture_method"))

-- | Create a new 'CheckoutPaycoPaymentMethodOptions' with all required fields.
mkCheckoutPaycoPaymentMethodOptions :: CheckoutPaycoPaymentMethodOptions
mkCheckoutPaycoPaymentMethodOptions = CheckoutPaycoPaymentMethodOptions {checkoutPaycoPaymentMethodOptionsCaptureMethod = GHC.Maybe.Nothing}

-- | Defines the enum schema located at @components.schemas.checkout_payco_payment_method_options.properties.capture_method@ in the specification.
--
-- Controls when the funds will be captured from the customer\'s account.
data CheckoutPaycoPaymentMethodOptionsCaptureMethod'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    CheckoutPaycoPaymentMethodOptionsCaptureMethod'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    CheckoutPaycoPaymentMethodOptionsCaptureMethod'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"manual"@
    CheckoutPaycoPaymentMethodOptionsCaptureMethod'EnumManual
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON CheckoutPaycoPaymentMethodOptionsCaptureMethod' where
  toJSON (CheckoutPaycoPaymentMethodOptionsCaptureMethod'Other val) = val
  toJSON (CheckoutPaycoPaymentMethodOptionsCaptureMethod'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (CheckoutPaycoPaymentMethodOptionsCaptureMethod'EnumManual) = "manual"

instance Data.Aeson.Types.FromJSON.FromJSON CheckoutPaycoPaymentMethodOptionsCaptureMethod' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "manual" -> CheckoutPaycoPaymentMethodOptionsCaptureMethod'EnumManual
          | GHC.Base.otherwise -> CheckoutPaycoPaymentMethodOptionsCaptureMethod'Other val
      )
