module StripeAPI.Types.CheckoutPaypalPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutPaypalPaymentMethodOptions
instance Show CheckoutPaypalPaymentMethodOptions
instance Eq CheckoutPaypalPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutPaypalPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutPaypalPaymentMethodOptions
data CheckoutPaypalPaymentMethodOptionsCaptureMethod'
instance Show CheckoutPaypalPaymentMethodOptionsCaptureMethod'
instance Eq CheckoutPaypalPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON CheckoutPaypalPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON CheckoutPaypalPaymentMethodOptionsCaptureMethod'
data CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutPaypalPaymentMethodOptionsSetupFutureUsage'
