module StripeAPI.Types.CheckoutAuBecsDebitPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutAuBecsDebitPaymentMethodOptions
instance Show CheckoutAuBecsDebitPaymentMethodOptions
instance Eq CheckoutAuBecsDebitPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutAuBecsDebitPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutAuBecsDebitPaymentMethodOptions
data CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutAuBecsDebitPaymentMethodOptionsSetupFutureUsage'
