module StripeAPI.Types.CheckoutCardPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutCardPaymentMethodOptions
instance Show CheckoutCardPaymentMethodOptions
instance Eq CheckoutCardPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutCardPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutCardPaymentMethodOptions
data CheckoutCardPaymentMethodOptionsRequestExtendedAuthorization'
instance Show CheckoutCardPaymentMethodOptionsRequestExtendedAuthorization'
instance Eq CheckoutCardPaymentMethodOptionsRequestExtendedAuthorization'
instance Data.Aeson.FromJSON CheckoutCardPaymentMethodOptionsRequestExtendedAuthorization'
instance Data.Aeson.ToJSON CheckoutCardPaymentMethodOptionsRequestExtendedAuthorization'
data CheckoutCardPaymentMethodOptionsRequestIncrementalAuthorization'
instance Show CheckoutCardPaymentMethodOptionsRequestIncrementalAuthorization'
instance Eq CheckoutCardPaymentMethodOptionsRequestIncrementalAuthorization'
instance Data.Aeson.FromJSON CheckoutCardPaymentMethodOptionsRequestIncrementalAuthorization'
instance Data.Aeson.ToJSON CheckoutCardPaymentMethodOptionsRequestIncrementalAuthorization'
data CheckoutCardPaymentMethodOptionsRequestMulticapture'
instance Show CheckoutCardPaymentMethodOptionsRequestMulticapture'
instance Eq CheckoutCardPaymentMethodOptionsRequestMulticapture'
instance Data.Aeson.FromJSON CheckoutCardPaymentMethodOptionsRequestMulticapture'
instance Data.Aeson.ToJSON CheckoutCardPaymentMethodOptionsRequestMulticapture'
data CheckoutCardPaymentMethodOptionsRequestOvercapture'
instance Show CheckoutCardPaymentMethodOptionsRequestOvercapture'
instance Eq CheckoutCardPaymentMethodOptionsRequestOvercapture'
instance Data.Aeson.FromJSON CheckoutCardPaymentMethodOptionsRequestOvercapture'
instance Data.Aeson.ToJSON CheckoutCardPaymentMethodOptionsRequestOvercapture'
data CheckoutCardPaymentMethodOptionsRequestThreeDSecure'
instance Show CheckoutCardPaymentMethodOptionsRequestThreeDSecure'
instance Eq CheckoutCardPaymentMethodOptionsRequestThreeDSecure'
instance Data.Aeson.FromJSON CheckoutCardPaymentMethodOptionsRequestThreeDSecure'
instance Data.Aeson.ToJSON CheckoutCardPaymentMethodOptionsRequestThreeDSecure'
data CheckoutCardPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutCardPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutCardPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutCardPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutCardPaymentMethodOptionsSetupFutureUsage'
