module StripeAPI.Types.CheckoutPixPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutPixPaymentMethodOptions
instance Show CheckoutPixPaymentMethodOptions
instance Eq CheckoutPixPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutPixPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutPixPaymentMethodOptions
data CheckoutPixPaymentMethodOptionsAmountIncludesIof'
instance Show CheckoutPixPaymentMethodOptionsAmountIncludesIof'
instance Eq CheckoutPixPaymentMethodOptionsAmountIncludesIof'
instance Data.Aeson.FromJSON CheckoutPixPaymentMethodOptionsAmountIncludesIof'
instance Data.Aeson.ToJSON CheckoutPixPaymentMethodOptionsAmountIncludesIof'
data CheckoutPixPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutPixPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutPixPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutPixPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutPixPaymentMethodOptionsSetupFutureUsage'
