module StripeAPI.Types.CheckoutCustomerBalanceBankTransferPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutCustomerBalanceBankTransferPaymentMethodOptions
instance Show CheckoutCustomerBalanceBankTransferPaymentMethodOptions
instance Eq CheckoutCustomerBalanceBankTransferPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptions
data CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
instance Show CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
instance Eq CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
instance Data.Aeson.FromJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
instance Data.Aeson.ToJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptionsRequestedAddressTypes'
data CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
instance Show CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
instance Eq CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
instance Data.Aeson.FromJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
instance Data.Aeson.ToJSON CheckoutCustomerBalanceBankTransferPaymentMethodOptionsType'NonNullable
