module StripeAPI.Types.CheckoutBancontactPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutBancontactPaymentMethodOptions
instance Show CheckoutBancontactPaymentMethodOptions
instance Eq CheckoutBancontactPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutBancontactPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutBancontactPaymentMethodOptions
data CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutBancontactPaymentMethodOptionsSetupFutureUsage'
