module StripeAPI.Types.CheckoutKrCardPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutKrCardPaymentMethodOptions
instance Show CheckoutKrCardPaymentMethodOptions
instance Eq CheckoutKrCardPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutKrCardPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutKrCardPaymentMethodOptions
data CheckoutKrCardPaymentMethodOptionsCaptureMethod'
instance Show CheckoutKrCardPaymentMethodOptionsCaptureMethod'
instance Eq CheckoutKrCardPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON CheckoutKrCardPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON CheckoutKrCardPaymentMethodOptionsCaptureMethod'
data CheckoutKrCardPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutKrCardPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutKrCardPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutKrCardPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutKrCardPaymentMethodOptionsSetupFutureUsage'
