module StripeAPI.Types.CheckoutAfterpayClearpayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutAfterpayClearpayPaymentMethodOptions
instance Show CheckoutAfterpayClearpayPaymentMethodOptions
instance Eq CheckoutAfterpayClearpayPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutAfterpayClearpayPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutAfterpayClearpayPaymentMethodOptions
data CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutAfterpayClearpayPaymentMethodOptionsSetupFutureUsage'
