module StripeAPI.Types.CheckoutUsBankAccountPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutUsBankAccountPaymentMethodOptions
instance Show CheckoutUsBankAccountPaymentMethodOptions
instance Eq CheckoutUsBankAccountPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutUsBankAccountPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutUsBankAccountPaymentMethodOptions
data CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutUsBankAccountPaymentMethodOptionsSetupFutureUsage'
data CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
instance Show CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
instance Eq CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
instance Data.Aeson.FromJSON CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
instance Data.Aeson.ToJSON CheckoutUsBankAccountPaymentMethodOptionsVerificationMethod'
