module StripeAPI.Types.CheckoutMultibancoPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutMultibancoPaymentMethodOptions
instance Show CheckoutMultibancoPaymentMethodOptions
instance Eq CheckoutMultibancoPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutMultibancoPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutMultibancoPaymentMethodOptions
data CheckoutMultibancoPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutMultibancoPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutMultibancoPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutMultibancoPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutMultibancoPaymentMethodOptionsSetupFutureUsage'
