module StripeAPI.Types.CheckoutMobilepayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutMobilepayPaymentMethodOptions
instance Show CheckoutMobilepayPaymentMethodOptions
instance Eq CheckoutMobilepayPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutMobilepayPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutMobilepayPaymentMethodOptions
data CheckoutMobilepayPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutMobilepayPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutMobilepayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutMobilepayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutMobilepayPaymentMethodOptionsSetupFutureUsage'
