module StripeAPI.Types.CheckoutKakaoPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutKakaoPayPaymentMethodOptions
instance Show CheckoutKakaoPayPaymentMethodOptions
instance Eq CheckoutKakaoPayPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutKakaoPayPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutKakaoPayPaymentMethodOptions
data CheckoutKakaoPayPaymentMethodOptionsCaptureMethod'
instance Show CheckoutKakaoPayPaymentMethodOptionsCaptureMethod'
instance Eq CheckoutKakaoPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON CheckoutKakaoPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON CheckoutKakaoPayPaymentMethodOptionsCaptureMethod'
data CheckoutKakaoPayPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutKakaoPayPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutKakaoPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutKakaoPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutKakaoPayPaymentMethodOptionsSetupFutureUsage'
