module StripeAPI.Types.CheckoutNaverPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutNaverPayPaymentMethodOptions
instance Show CheckoutNaverPayPaymentMethodOptions
instance Eq CheckoutNaverPayPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutNaverPayPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutNaverPayPaymentMethodOptions
data CheckoutNaverPayPaymentMethodOptionsCaptureMethod'
instance Show CheckoutNaverPayPaymentMethodOptionsCaptureMethod'
instance Eq CheckoutNaverPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON CheckoutNaverPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON CheckoutNaverPayPaymentMethodOptionsCaptureMethod'
data CheckoutNaverPayPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutNaverPayPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutNaverPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutNaverPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutNaverPayPaymentMethodOptionsSetupFutureUsage'
