module StripeAPI.Types.CheckoutAmazonPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CheckoutAmazonPayPaymentMethodOptions
instance Show CheckoutAmazonPayPaymentMethodOptions
instance Eq CheckoutAmazonPayPaymentMethodOptions
instance Data.Aeson.FromJSON CheckoutAmazonPayPaymentMethodOptions
instance Data.Aeson.ToJSON CheckoutAmazonPayPaymentMethodOptions
data CheckoutAmazonPayPaymentMethodOptionsSetupFutureUsage'
instance Show CheckoutAmazonPayPaymentMethodOptionsSetupFutureUsage'
instance Eq CheckoutAmazonPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON CheckoutAmazonPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON CheckoutAmazonPayPaymentMethodOptionsSetupFutureUsage'
