module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft
data CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftBalanceTransaction'Variants
data CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraftLinkedTransaction'Variants
