module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
instance Show CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransfer
data CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
instance Show CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransactionResourceBankTransferType'
