module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
instance Show CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction
