module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
instance Show CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance
data CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalanceBalanceTransaction'Variants
