module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
instance Show CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction
data CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransactionRefund'Variants
