module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
instance Show CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction
data CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransactionPaymentIntent'Variants
