module StripeAPI.Types.CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransaction
data CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
instance Show CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
instance Eq CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
instance Data.Aeson.FromJSON CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
instance Data.Aeson.ToJSON CustomerBalanceResourceCashBalanceTransactionResourceAppliedToPaymentTransactionPaymentIntent'Variants
