module StripeAPI.Types.CustomerBalanceCustomerBalanceSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data CustomerBalanceCustomerBalanceSettings
instance Show CustomerBalanceCustomerBalanceSettings
instance Eq CustomerBalanceCustomerBalanceSettings
instance Data.Aeson.FromJSON CustomerBalanceCustomerBalanceSettings
instance Data.Aeson.ToJSON CustomerBalanceCustomerBalanceSettings
data CustomerBalanceCustomerBalanceSettingsReconciliationMode'
instance Show CustomerBalanceCustomerBalanceSettingsReconciliationMode'
instance Eq CustomerBalanceCustomerBalanceSettingsReconciliationMode'
instance Data.Aeson.FromJSON CustomerBalanceCustomerBalanceSettingsReconciliationMode'
instance Data.Aeson.ToJSON CustomerBalanceCustomerBalanceSettingsReconciliationMode'
