module StripeAPI.Types.DiscountsResourceStackableDiscount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DiscountsResourceStackableDiscount
instance Show DiscountsResourceStackableDiscount
instance Eq DiscountsResourceStackableDiscount
instance Data.Aeson.FromJSON DiscountsResourceStackableDiscount
instance Data.Aeson.ToJSON DiscountsResourceStackableDiscount
data DiscountsResourceStackableDiscountCoupon'NonNullableVariants
instance Show DiscountsResourceStackableDiscountCoupon'NonNullableVariants
instance Eq DiscountsResourceStackableDiscountCoupon'NonNullableVariants
instance Data.Aeson.FromJSON DiscountsResourceStackableDiscountCoupon'NonNullableVariants
instance Data.Aeson.ToJSON DiscountsResourceStackableDiscountCoupon'NonNullableVariants
data DiscountsResourceStackableDiscountDiscount'NonNullableVariants
instance Show DiscountsResourceStackableDiscountDiscount'NonNullableVariants
instance Eq DiscountsResourceStackableDiscountDiscount'NonNullableVariants
instance Data.Aeson.FromJSON DiscountsResourceStackableDiscountDiscount'NonNullableVariants
instance Data.Aeson.ToJSON DiscountsResourceStackableDiscountDiscount'NonNullableVariants
data DiscountsResourceStackableDiscountPromotionCode'NonNullableVariants
instance Show DiscountsResourceStackableDiscountPromotionCode'NonNullableVariants
instance Eq DiscountsResourceStackableDiscountPromotionCode'NonNullableVariants
instance Data.Aeson.FromJSON DiscountsResourceStackableDiscountPromotionCode'NonNullableVariants
instance Data.Aeson.ToJSON DiscountsResourceStackableDiscountPromotionCode'NonNullableVariants
