module StripeAPI.Types.DisputePaymentMethodDetailsAmazonPay where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DisputePaymentMethodDetailsAmazonPay
instance Show DisputePaymentMethodDetailsAmazonPay
instance Eq DisputePaymentMethodDetailsAmazonPay
instance Data.Aeson.FromJSON DisputePaymentMethodDetailsAmazonPay
instance Data.Aeson.ToJSON DisputePaymentMethodDetailsAmazonPay
data DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable
instance Show DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable
instance Eq DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable
instance Data.Aeson.FromJSON DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable
instance Data.Aeson.ToJSON DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable
