{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema DisputeEnhancedEligibilityVisaCompliance
module StripeAPI.Types.DisputeEnhancedEligibilityVisaCompliance where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.dispute_enhanced_eligibility_visa_compliance@ in the specification.
data DisputeEnhancedEligibilityVisaCompliance = DisputeEnhancedEligibilityVisaCompliance
  { -- | status: Visa compliance eligibility status.
    disputeEnhancedEligibilityVisaComplianceStatus :: DisputeEnhancedEligibilityVisaComplianceStatus'
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON DisputeEnhancedEligibilityVisaCompliance where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["status" Data.Aeson.Types.ToJSON..= disputeEnhancedEligibilityVisaComplianceStatus obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["status" Data.Aeson.Types.ToJSON..= disputeEnhancedEligibilityVisaComplianceStatus obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON DisputeEnhancedEligibilityVisaCompliance where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "DisputeEnhancedEligibilityVisaCompliance" (\obj -> GHC.Base.pure DisputeEnhancedEligibilityVisaCompliance GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "status"))

-- | Create a new 'DisputeEnhancedEligibilityVisaCompliance' with all required fields.
mkDisputeEnhancedEligibilityVisaCompliance ::
  -- | 'disputeEnhancedEligibilityVisaComplianceStatus'
  DisputeEnhancedEligibilityVisaComplianceStatus' ->
  DisputeEnhancedEligibilityVisaCompliance
mkDisputeEnhancedEligibilityVisaCompliance disputeEnhancedEligibilityVisaComplianceStatus = DisputeEnhancedEligibilityVisaCompliance {disputeEnhancedEligibilityVisaComplianceStatus = disputeEnhancedEligibilityVisaComplianceStatus}

-- | Defines the enum schema located at @components.schemas.dispute_enhanced_eligibility_visa_compliance.properties.status@ in the specification.
--
-- Visa compliance eligibility status.
data DisputeEnhancedEligibilityVisaComplianceStatus'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    DisputeEnhancedEligibilityVisaComplianceStatus'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    DisputeEnhancedEligibilityVisaComplianceStatus'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"fee_acknowledged"@
    DisputeEnhancedEligibilityVisaComplianceStatus'EnumFeeAcknowledged
  | -- | Represents the JSON value @"requires_fee_acknowledgement"@
    DisputeEnhancedEligibilityVisaComplianceStatus'EnumRequiresFeeAcknowledgement
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON DisputeEnhancedEligibilityVisaComplianceStatus' where
  toJSON (DisputeEnhancedEligibilityVisaComplianceStatus'Other val) = val
  toJSON (DisputeEnhancedEligibilityVisaComplianceStatus'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (DisputeEnhancedEligibilityVisaComplianceStatus'EnumFeeAcknowledged) = "fee_acknowledged"
  toJSON (DisputeEnhancedEligibilityVisaComplianceStatus'EnumRequiresFeeAcknowledgement) = "requires_fee_acknowledgement"

instance Data.Aeson.Types.FromJSON.FromJSON DisputeEnhancedEligibilityVisaComplianceStatus' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "fee_acknowledged" -> DisputeEnhancedEligibilityVisaComplianceStatus'EnumFeeAcknowledged
          | val GHC.Classes.== "requires_fee_acknowledgement" -> DisputeEnhancedEligibilityVisaComplianceStatus'EnumRequiresFeeAcknowledgement
          | GHC.Base.otherwise -> DisputeEnhancedEligibilityVisaComplianceStatus'Other val
      )
