module StripeAPI.Types.DisputeVisaCompellingEvidence3DisputedTransaction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DisputeVisaCompellingEvidence3DisputedTransaction
instance Show DisputeVisaCompellingEvidence3DisputedTransaction
instance Eq DisputeVisaCompellingEvidence3DisputedTransaction
instance Data.Aeson.FromJSON DisputeVisaCompellingEvidence3DisputedTransaction
instance Data.Aeson.ToJSON DisputeVisaCompellingEvidence3DisputedTransaction
data DisputeVisaCompellingEvidence3DisputedTransactionMerchandiseOrServices'NonNullable
instance Show DisputeVisaCompellingEvidence3DisputedTransactionMerchandiseOrServices'NonNullable
instance Eq DisputeVisaCompellingEvidence3DisputedTransactionMerchandiseOrServices'NonNullable
instance Data.Aeson.FromJSON DisputeVisaCompellingEvidence3DisputedTransactionMerchandiseOrServices'NonNullable
instance Data.Aeson.ToJSON DisputeVisaCompellingEvidence3DisputedTransactionMerchandiseOrServices'NonNullable
data DisputeVisaCompellingEvidence3DisputedTransactionShippingAddress'NonNullable
instance Show DisputeVisaCompellingEvidence3DisputedTransactionShippingAddress'NonNullable
instance Eq DisputeVisaCompellingEvidence3DisputedTransactionShippingAddress'NonNullable
instance Data.Aeson.FromJSON DisputeVisaCompellingEvidence3DisputedTransactionShippingAddress'NonNullable
instance Data.Aeson.ToJSON DisputeVisaCompellingEvidence3DisputedTransactionShippingAddress'NonNullable
