{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema DisputePaymentMethodDetailsAmazonPay
module StripeAPI.Types.DisputePaymentMethodDetailsAmazonPay where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.dispute_payment_method_details_amazon_pay@ in the specification.
data DisputePaymentMethodDetailsAmazonPay = DisputePaymentMethodDetailsAmazonPay
  { -- | dispute_type: The AmazonPay dispute type, chargeback or claim
    disputePaymentMethodDetailsAmazonPayDisputeType :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON DisputePaymentMethodDetailsAmazonPay where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("dispute_type" Data.Aeson.Types.ToJSON..=)) (disputePaymentMethodDetailsAmazonPayDisputeType obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("dispute_type" Data.Aeson.Types.ToJSON..=)) (disputePaymentMethodDetailsAmazonPayDisputeType obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON DisputePaymentMethodDetailsAmazonPay where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "DisputePaymentMethodDetailsAmazonPay" (\obj -> GHC.Base.pure DisputePaymentMethodDetailsAmazonPay GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "dispute_type"))

-- | Create a new 'DisputePaymentMethodDetailsAmazonPay' with all required fields.
mkDisputePaymentMethodDetailsAmazonPay :: DisputePaymentMethodDetailsAmazonPay
mkDisputePaymentMethodDetailsAmazonPay = DisputePaymentMethodDetailsAmazonPay {disputePaymentMethodDetailsAmazonPayDisputeType = GHC.Maybe.Nothing}

-- | Defines the enum schema located at @components.schemas.dispute_payment_method_details_amazon_pay.properties.dispute_type@ in the specification.
--
-- The AmazonPay dispute type, chargeback or claim
data DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableOther Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableTyped Data.Text.Internal.Text
  | -- | Represents the JSON value @"chargeback"@
    DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableEnumChargeback
  | -- | Represents the JSON value @"claim"@
    DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableEnumClaim
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable where
  toJSON (DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableOther val) = val
  toJSON (DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableEnumChargeback) = "chargeback"
  toJSON (DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableEnumClaim) = "claim"

instance Data.Aeson.Types.FromJSON.FromJSON DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullable where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "chargeback" -> DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableEnumChargeback
          | val GHC.Classes.== "claim" -> DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableEnumClaim
          | GHC.Base.otherwise -> DisputePaymentMethodDetailsAmazonPayDisputeType'NonNullableOther val
      )
