module StripeAPI.Types.DisputeEnhancedEligibilityVisaCompellingEvidence3 where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DisputeEnhancedEligibilityVisaCompellingEvidence3
instance Show DisputeEnhancedEligibilityVisaCompellingEvidence3
instance Eq DisputeEnhancedEligibilityVisaCompellingEvidence3
instance Data.Aeson.FromJSON DisputeEnhancedEligibilityVisaCompellingEvidence3
instance Data.Aeson.ToJSON DisputeEnhancedEligibilityVisaCompellingEvidence3
data DisputeEnhancedEligibilityVisaCompellingEvidence3RequiredActions'
instance Show DisputeEnhancedEligibilityVisaCompellingEvidence3RequiredActions'
instance Eq DisputeEnhancedEligibilityVisaCompellingEvidence3RequiredActions'
instance Data.Aeson.FromJSON DisputeEnhancedEligibilityVisaCompellingEvidence3RequiredActions'
instance Data.Aeson.ToJSON DisputeEnhancedEligibilityVisaCompellingEvidence3RequiredActions'
data DisputeEnhancedEligibilityVisaCompellingEvidence3Status'
instance Show DisputeEnhancedEligibilityVisaCompellingEvidence3Status'
instance Eq DisputeEnhancedEligibilityVisaCompellingEvidence3Status'
instance Data.Aeson.FromJSON DisputeEnhancedEligibilityVisaCompellingEvidence3Status'
instance Data.Aeson.ToJSON DisputeEnhancedEligibilityVisaCompellingEvidence3Status'
