module StripeAPI.Types.DisputeEnhancedEvidenceVisaCompellingEvidence3 where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DisputeEnhancedEvidenceVisaCompellingEvidence3
instance Show DisputeEnhancedEvidenceVisaCompellingEvidence3
instance Eq DisputeEnhancedEvidenceVisaCompellingEvidence3
instance Data.Aeson.FromJSON DisputeEnhancedEvidenceVisaCompellingEvidence3
instance Data.Aeson.ToJSON DisputeEnhancedEvidenceVisaCompellingEvidence3
data DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullable
instance Show DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullable
instance Eq DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullable
instance Data.Aeson.FromJSON DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullable
instance Data.Aeson.ToJSON DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullable
data DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableMerchandiseOrServices'NonNullable
instance Show DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableMerchandiseOrServices'NonNullable
instance Eq DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableMerchandiseOrServices'NonNullable
instance Data.Aeson.FromJSON DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableMerchandiseOrServices'NonNullable
instance Data.Aeson.ToJSON DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableMerchandiseOrServices'NonNullable
data DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableShippingAddress'NonNullable
instance Show DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableShippingAddress'NonNullable
instance Eq DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableShippingAddress'NonNullable
instance Data.Aeson.FromJSON DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableShippingAddress'NonNullable
instance Data.Aeson.ToJSON DisputeEnhancedEvidenceVisaCompellingEvidence3DisputedTransaction'NonNullableShippingAddress'NonNullable
