module StripeAPI.Types.DisputeVisaCompellingEvidence3PriorUndisputedTransaction where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DisputeVisaCompellingEvidence3PriorUndisputedTransaction
instance Show DisputeVisaCompellingEvidence3PriorUndisputedTransaction
instance Eq DisputeVisaCompellingEvidence3PriorUndisputedTransaction
instance Data.Aeson.FromJSON DisputeVisaCompellingEvidence3PriorUndisputedTransaction
instance Data.Aeson.ToJSON DisputeVisaCompellingEvidence3PriorUndisputedTransaction
data DisputeVisaCompellingEvidence3PriorUndisputedTransactionShippingAddress'NonNullable
instance Show DisputeVisaCompellingEvidence3PriorUndisputedTransactionShippingAddress'NonNullable
instance Eq DisputeVisaCompellingEvidence3PriorUndisputedTransactionShippingAddress'NonNullable
instance Data.Aeson.FromJSON DisputeVisaCompellingEvidence3PriorUndisputedTransactionShippingAddress'NonNullable
instance Data.Aeson.ToJSON DisputeVisaCompellingEvidence3PriorUndisputedTransactionShippingAddress'NonNullable
