module StripeAPI.Types.DisputeEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data DisputeEvidence
instance Show DisputeEvidence
instance Eq DisputeEvidence
instance Data.Aeson.FromJSON DisputeEvidence
instance Data.Aeson.ToJSON DisputeEvidence
data DisputeEvidenceCancellationPolicy'NonNullableVariants
instance Show DisputeEvidenceCancellationPolicy'NonNullableVariants
instance Eq DisputeEvidenceCancellationPolicy'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceCancellationPolicy'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceCancellationPolicy'NonNullableVariants
data DisputeEvidenceCustomerCommunication'NonNullableVariants
instance Show DisputeEvidenceCustomerCommunication'NonNullableVariants
instance Eq DisputeEvidenceCustomerCommunication'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceCustomerCommunication'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceCustomerCommunication'NonNullableVariants
data DisputeEvidenceCustomerSignature'NonNullableVariants
instance Show DisputeEvidenceCustomerSignature'NonNullableVariants
instance Eq DisputeEvidenceCustomerSignature'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceCustomerSignature'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceCustomerSignature'NonNullableVariants
data DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
instance Show DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
instance Eq DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceDuplicateChargeDocumentation'NonNullableVariants
data DisputeEvidenceReceipt'NonNullableVariants
instance Show DisputeEvidenceReceipt'NonNullableVariants
instance Eq DisputeEvidenceReceipt'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceReceipt'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceReceipt'NonNullableVariants
data DisputeEvidenceRefundPolicy'NonNullableVariants
instance Show DisputeEvidenceRefundPolicy'NonNullableVariants
instance Eq DisputeEvidenceRefundPolicy'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceRefundPolicy'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceRefundPolicy'NonNullableVariants
data DisputeEvidenceServiceDocumentation'NonNullableVariants
instance Show DisputeEvidenceServiceDocumentation'NonNullableVariants
instance Eq DisputeEvidenceServiceDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceServiceDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceServiceDocumentation'NonNullableVariants
data DisputeEvidenceShippingDocumentation'NonNullableVariants
instance Show DisputeEvidenceShippingDocumentation'NonNullableVariants
instance Eq DisputeEvidenceShippingDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceShippingDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceShippingDocumentation'NonNullableVariants
data DisputeEvidenceUncategorizedFile'NonNullableVariants
instance Show DisputeEvidenceUncategorizedFile'NonNullableVariants
instance Eq DisputeEvidenceUncategorizedFile'NonNullableVariants
instance Data.Aeson.FromJSON DisputeEvidenceUncategorizedFile'NonNullableVariants
instance Data.Aeson.ToJSON DisputeEvidenceUncategorizedFile'NonNullableVariants
