module StripeAPI.Types.FundingInstructionsBankTransferFinancialAddress where
import qualified Data.Aeson
import qualified StripeAPI.Common
data FundingInstructionsBankTransferFinancialAddress
instance Show FundingInstructionsBankTransferFinancialAddress
instance Eq FundingInstructionsBankTransferFinancialAddress
instance Data.Aeson.FromJSON FundingInstructionsBankTransferFinancialAddress
instance Data.Aeson.ToJSON FundingInstructionsBankTransferFinancialAddress
data FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
instance Show FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
instance Eq FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
instance Data.Aeson.FromJSON FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
instance Data.Aeson.ToJSON FundingInstructionsBankTransferFinancialAddressSupportedNetworks'
data FundingInstructionsBankTransferFinancialAddressType'
instance Show FundingInstructionsBankTransferFinancialAddressType'
instance Eq FundingInstructionsBankTransferFinancialAddressType'
instance Data.Aeson.FromJSON FundingInstructionsBankTransferFinancialAddressType'
instance Data.Aeson.ToJSON FundingInstructionsBankTransferFinancialAddressType'
