module StripeAPI.Types.InvoicePaymentMethodOptionsCustomerBalanceBankTransfer where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
instance Show InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
instance Eq InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
