module StripeAPI.Types.InvoicesPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicesPaymentMethodOptions
instance Show InvoicesPaymentMethodOptions
instance Eq InvoicesPaymentMethodOptions
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptions
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptions
data InvoicesPaymentMethodOptionsAcssDebit'NonNullable
instance Show InvoicesPaymentMethodOptionsAcssDebit'NonNullable
instance Eq InvoicesPaymentMethodOptionsAcssDebit'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsAcssDebit'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsAcssDebit'NonNullable
data InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Show InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Eq InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
data InvoicesPaymentMethodOptionsBancontact'NonNullable
instance Show InvoicesPaymentMethodOptionsBancontact'NonNullable
instance Eq InvoicesPaymentMethodOptionsBancontact'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsBancontact'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsBancontact'NonNullable
data InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Show InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Eq InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
data InvoicesPaymentMethodOptionsCard'NonNullable
instance Show InvoicesPaymentMethodOptionsCard'NonNullable
instance Eq InvoicesPaymentMethodOptionsCard'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsCard'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsCard'NonNullable
data InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Show InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Eq InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
data InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
instance Show InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
instance Eq InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsCustomerBalance'NonNullable
data InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Show InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Eq InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
data InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
instance Show InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
instance Eq InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsUsBankAccount'NonNullable
data InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Show InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Eq InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Data.Aeson.FromJSON InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Data.Aeson.ToJSON InvoicesPaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
