module StripeAPI.Types.InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
instance Show InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
instance Eq InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer
data InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
instance Show InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
instance Eq InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransferCountry'
