module StripeAPI.Types.InvoicePaymentMethodOptionsUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsUsBankAccount
instance Show InvoicePaymentMethodOptionsUsBankAccount
instance Eq InvoicePaymentMethodOptionsUsBankAccount
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsUsBankAccount
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsUsBankAccount
data InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
instance Show InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
instance Eq InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsUsBankAccountVerificationMethod'
