{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema InvoiceSettingSubscriptionScheduleSetting
module StripeAPI.Types.InvoiceSettingSubscriptionScheduleSetting where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.ConnectAccountReference
import {-# SOURCE #-} StripeAPI.Types.DeletedTaxId
import {-# SOURCE #-} StripeAPI.Types.TaxId
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.invoice_setting_subscription_schedule_setting@ in the specification.
data InvoiceSettingSubscriptionScheduleSetting = InvoiceSettingSubscriptionScheduleSetting
  { -- | account_tax_ids: The account tax IDs associated with the subscription schedule. Will be set on invoices generated by the subscription schedule.
    invoiceSettingSubscriptionScheduleSettingAccountTaxIds :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable [InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants])),
    -- | days_until_due: Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be \`null\` for subscription schedules where \`billing=charge_automatically\`.
    invoiceSettingSubscriptionScheduleSettingDaysUntilDue :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable GHC.Types.Int)),
    -- | issuer:
    invoiceSettingSubscriptionScheduleSettingIssuer :: ConnectAccountReference
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON InvoiceSettingSubscriptionScheduleSetting where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account_tax_ids" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionScheduleSettingAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("days_until_due" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionScheduleSettingDaysUntilDue obj) : ["issuer" Data.Aeson.Types.ToJSON..= invoiceSettingSubscriptionScheduleSettingIssuer obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("account_tax_ids" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionScheduleSettingAccountTaxIds obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("days_until_due" Data.Aeson.Types.ToJSON..=)) (invoiceSettingSubscriptionScheduleSettingDaysUntilDue obj) : ["issuer" Data.Aeson.Types.ToJSON..= invoiceSettingSubscriptionScheduleSettingIssuer obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON InvoiceSettingSubscriptionScheduleSetting where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "InvoiceSettingSubscriptionScheduleSetting" (\obj -> ((GHC.Base.pure InvoiceSettingSubscriptionScheduleSetting GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "account_tax_ids")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "days_until_due")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "issuer"))

-- | Create a new 'InvoiceSettingSubscriptionScheduleSetting' with all required fields.
mkInvoiceSettingSubscriptionScheduleSetting ::
  -- | 'invoiceSettingSubscriptionScheduleSettingIssuer'
  ConnectAccountReference ->
  InvoiceSettingSubscriptionScheduleSetting
mkInvoiceSettingSubscriptionScheduleSetting invoiceSettingSubscriptionScheduleSettingIssuer =
  InvoiceSettingSubscriptionScheduleSetting
    { invoiceSettingSubscriptionScheduleSettingAccountTaxIds = GHC.Maybe.Nothing,
      invoiceSettingSubscriptionScheduleSettingDaysUntilDue = GHC.Maybe.Nothing,
      invoiceSettingSubscriptionScheduleSettingIssuer = invoiceSettingSubscriptionScheduleSettingIssuer
    }

-- | Defines the oneOf schema located at @components.schemas.invoice_setting_subscription_schedule_setting.properties.account_tax_ids.items.anyOf@ in the specification.
data InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants
  = InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableText Data.Text.Internal.Text
  | InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableTaxId TaxId
  | InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableDeletedTaxId DeletedTaxId
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants where
  toJSON (InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableText a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableTaxId a) = Data.Aeson.Types.ToJSON.toJSON a
  toJSON (InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableDeletedTaxId a) = Data.Aeson.Types.ToJSON.toJSON a

instance Data.Aeson.Types.FromJSON.FromJSON InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants where
  parseJSON val = case (InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableDeletedTaxId Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched")) of
    Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a
    Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a
