module StripeAPI.Types.InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFilters where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFilters
instance Show InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFilters
instance Eq InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFilters
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFilters
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFilters
data InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFiltersAccountSubcategories'
instance Show InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFiltersAccountSubcategories'
instance Eq InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFiltersAccountSubcategories'
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFiltersAccountSubcategories'
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFiltersAccountSubcategories'
