module StripeAPI.Types.InvoicePaymentMethodOptionsBancontact where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsBancontact
instance Show InvoicePaymentMethodOptionsBancontact
instance Eq InvoicePaymentMethodOptionsBancontact
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsBancontact
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsBancontact
data InvoicePaymentMethodOptionsBancontactPreferredLanguage'
instance Show InvoicePaymentMethodOptionsBancontactPreferredLanguage'
instance Eq InvoicePaymentMethodOptionsBancontactPreferredLanguage'
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsBancontactPreferredLanguage'
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsBancontactPreferredLanguage'
