module StripeAPI.Types.InvoicePaymentMethodOptionsCustomerBalance where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsCustomerBalance
instance Show InvoicePaymentMethodOptionsCustomerBalance
instance Eq InvoicePaymentMethodOptionsCustomerBalance
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsCustomerBalance
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsCustomerBalance
data InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Show InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Eq InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsCustomerBalanceFundingType'NonNullable
