module StripeAPI.Types.InvoicesPaymentSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicesPaymentSettings
instance Show InvoicesPaymentSettings
instance Eq InvoicesPaymentSettings
instance Data.Aeson.FromJSON InvoicesPaymentSettings
instance Data.Aeson.ToJSON InvoicesPaymentSettings
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
data InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Show InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Eq InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
data InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
instance Show InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
instance Eq InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
instance Data.Aeson.FromJSON InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
instance Data.Aeson.ToJSON InvoicesPaymentSettingsPaymentMethodTypes'NonNullable
