module StripeAPI.Types.InvoiceSettingSubscriptionScheduleSetting where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoiceSettingSubscriptionScheduleSetting
instance Show InvoiceSettingSubscriptionScheduleSetting
instance Eq InvoiceSettingSubscriptionScheduleSetting
instance Data.Aeson.FromJSON InvoiceSettingSubscriptionScheduleSetting
instance Data.Aeson.ToJSON InvoiceSettingSubscriptionScheduleSetting
data InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants
instance Show InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants
instance Eq InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants
instance Data.Aeson.FromJSON InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants
instance Data.Aeson.ToJSON InvoiceSettingSubscriptionScheduleSettingAccountTaxIds'NonNullableVariants
