module StripeAPI.Types.InvoicesResourceInvoiceRendering where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicesResourceInvoiceRendering
instance Show InvoicesResourceInvoiceRendering
instance Eq InvoicesResourceInvoiceRendering
instance Data.Aeson.FromJSON InvoicesResourceInvoiceRendering
instance Data.Aeson.ToJSON InvoicesResourceInvoiceRendering
data InvoicesResourceInvoiceRenderingPdf'NonNullable
instance Show InvoicesResourceInvoiceRenderingPdf'NonNullable
instance Eq InvoicesResourceInvoiceRenderingPdf'NonNullable
instance Data.Aeson.FromJSON InvoicesResourceInvoiceRenderingPdf'NonNullable
instance Data.Aeson.ToJSON InvoicesResourceInvoiceRenderingPdf'NonNullable
data InvoicesResourceInvoiceRenderingPdf'NonNullablePageSize'NonNullable
instance Show InvoicesResourceInvoiceRenderingPdf'NonNullablePageSize'NonNullable
instance Eq InvoicesResourceInvoiceRenderingPdf'NonNullablePageSize'NonNullable
instance Data.Aeson.FromJSON InvoicesResourceInvoiceRenderingPdf'NonNullablePageSize'NonNullable
instance Data.Aeson.ToJSON InvoicesResourceInvoiceRenderingPdf'NonNullablePageSize'NonNullable
