module StripeAPI.Types.InvoicePaymentMethodOptionsAcssDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsAcssDebit
instance Show InvoicePaymentMethodOptionsAcssDebit
instance Eq InvoicePaymentMethodOptionsAcssDebit
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsAcssDebit
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsAcssDebit
data InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
instance Show InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
instance Eq InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsAcssDebitVerificationMethod'
