module StripeAPI.Types.InvoicesPaymentsInvoicePaymentAssociatedPayment where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicesPaymentsInvoicePaymentAssociatedPayment
instance Show InvoicesPaymentsInvoicePaymentAssociatedPayment
instance Eq InvoicesPaymentsInvoicePaymentAssociatedPayment
instance Data.Aeson.FromJSON InvoicesPaymentsInvoicePaymentAssociatedPayment
instance Data.Aeson.ToJSON InvoicesPaymentsInvoicePaymentAssociatedPayment
data InvoicesPaymentsInvoicePaymentAssociatedPaymentCharge'Variants
instance Show InvoicesPaymentsInvoicePaymentAssociatedPaymentCharge'Variants
instance Eq InvoicesPaymentsInvoicePaymentAssociatedPaymentCharge'Variants
instance Data.Aeson.FromJSON InvoicesPaymentsInvoicePaymentAssociatedPaymentCharge'Variants
instance Data.Aeson.ToJSON InvoicesPaymentsInvoicePaymentAssociatedPaymentCharge'Variants
data InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent'Variants
instance Show InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent'Variants
instance Eq InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent'Variants
instance Data.Aeson.FromJSON InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent'Variants
instance Data.Aeson.ToJSON InvoicesPaymentsInvoicePaymentAssociatedPaymentPaymentIntent'Variants
data InvoicesPaymentsInvoicePaymentAssociatedPaymentType'
instance Show InvoicesPaymentsInvoicePaymentAssociatedPaymentType'
instance Eq InvoicesPaymentsInvoicePaymentAssociatedPaymentType'
instance Data.Aeson.FromJSON InvoicesPaymentsInvoicePaymentAssociatedPaymentType'
instance Data.Aeson.ToJSON InvoicesPaymentsInvoicePaymentAssociatedPaymentType'
