module StripeAPI.Types.InvoiceItemThresholdReason where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoiceItemThresholdReason
instance Show InvoiceItemThresholdReason
instance Eq InvoiceItemThresholdReason
instance Data.Aeson.FromJSON InvoiceItemThresholdReason
instance Data.Aeson.ToJSON InvoiceItemThresholdReason
