module StripeAPI.Types.InvoicePaymentMethodOptionsAcssDebitMandateOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance Show InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance Eq InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsAcssDebitMandateOptions
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsAcssDebitMandateOptions
data InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
instance Show InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
instance Eq InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsAcssDebitMandateOptionsTransactionType'NonNullable
