module StripeAPI.Types.InvoiceSettingCustomerSetting where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoiceSettingCustomerSetting
instance Show InvoiceSettingCustomerSetting
instance Eq InvoiceSettingCustomerSetting
instance Data.Aeson.FromJSON InvoiceSettingCustomerSetting
instance Data.Aeson.ToJSON InvoiceSettingCustomerSetting
data InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
instance Show InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
instance Eq InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
instance Data.Aeson.FromJSON InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
instance Data.Aeson.ToJSON InvoiceSettingCustomerSettingDefaultPaymentMethod'NonNullableVariants
data InvoiceSettingCustomerSettingRenderingOptions'NonNullable
instance Show InvoiceSettingCustomerSettingRenderingOptions'NonNullable
instance Eq InvoiceSettingCustomerSettingRenderingOptions'NonNullable
instance Data.Aeson.FromJSON InvoiceSettingCustomerSettingRenderingOptions'NonNullable
instance Data.Aeson.ToJSON InvoiceSettingCustomerSettingRenderingOptions'NonNullable
