module StripeAPI.Types.InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
instance Show InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
instance Eq InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptions
data InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
instance Show InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
instance Eq InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPermissions'
data InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
instance Show InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
instance Eq InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
instance Data.Aeson.FromJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
instance Data.Aeson.ToJSON InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsPrefetch'NonNullable
