module StripeAPI.Types.InvoiceSettingSubscriptionSchedulePhaseSetting where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoiceSettingSubscriptionSchedulePhaseSetting
instance Show InvoiceSettingSubscriptionSchedulePhaseSetting
instance Eq InvoiceSettingSubscriptionSchedulePhaseSetting
instance Data.Aeson.FromJSON InvoiceSettingSubscriptionSchedulePhaseSetting
instance Data.Aeson.ToJSON InvoiceSettingSubscriptionSchedulePhaseSetting
data InvoiceSettingSubscriptionSchedulePhaseSettingAccountTaxIds'NonNullableVariants
instance Show InvoiceSettingSubscriptionSchedulePhaseSettingAccountTaxIds'NonNullableVariants
instance Eq InvoiceSettingSubscriptionSchedulePhaseSettingAccountTaxIds'NonNullableVariants
instance Data.Aeson.FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingAccountTaxIds'NonNullableVariants
instance Data.Aeson.ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingAccountTaxIds'NonNullableVariants
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
instance Show InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
instance Eq InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
instance Data.Aeson.FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
instance Data.Aeson.ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullable
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
instance Show InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
instance Eq InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
instance Data.Aeson.FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
instance Data.Aeson.ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableAccount'Variants
data InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
instance Show InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
instance Eq InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
instance Data.Aeson.FromJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
instance Data.Aeson.ToJSON InvoiceSettingSubscriptionSchedulePhaseSettingIssuer'NonNullableType'
