module StripeAPI.Types.InvoicesResourcePretaxCreditAmount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data InvoicesResourcePretaxCreditAmount
instance Show InvoicesResourcePretaxCreditAmount
instance Eq InvoicesResourcePretaxCreditAmount
instance Data.Aeson.FromJSON InvoicesResourcePretaxCreditAmount
instance Data.Aeson.ToJSON InvoicesResourcePretaxCreditAmount
data InvoicesResourcePretaxCreditAmountCreditBalanceTransaction'NonNullableVariants
instance Show InvoicesResourcePretaxCreditAmountCreditBalanceTransaction'NonNullableVariants
instance Eq InvoicesResourcePretaxCreditAmountCreditBalanceTransaction'NonNullableVariants
instance Data.Aeson.FromJSON InvoicesResourcePretaxCreditAmountCreditBalanceTransaction'NonNullableVariants
instance Data.Aeson.ToJSON InvoicesResourcePretaxCreditAmountCreditBalanceTransaction'NonNullableVariants
data InvoicesResourcePretaxCreditAmountDiscount'Variants
instance Show InvoicesResourcePretaxCreditAmountDiscount'Variants
instance Eq InvoicesResourcePretaxCreditAmountDiscount'Variants
instance Data.Aeson.FromJSON InvoicesResourcePretaxCreditAmountDiscount'Variants
instance Data.Aeson.ToJSON InvoicesResourcePretaxCreditAmountDiscount'Variants
data InvoicesResourcePretaxCreditAmountType'
instance Show InvoicesResourcePretaxCreditAmountType'
instance Eq InvoicesResourcePretaxCreditAmountType'
instance Data.Aeson.FromJSON InvoicesResourcePretaxCreditAmountType'
instance Data.Aeson.ToJSON InvoicesResourcePretaxCreditAmountType'
