module StripeAPI.Types.IssuingTransactionFleetData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingTransactionFleetData
instance Show IssuingTransactionFleetData
instance Eq IssuingTransactionFleetData
instance Data.Aeson.FromJSON IssuingTransactionFleetData
instance Data.Aeson.ToJSON IssuingTransactionFleetData
data IssuingTransactionFleetDataCardholderPromptData'NonNullable
instance Show IssuingTransactionFleetDataCardholderPromptData'NonNullable
instance Eq IssuingTransactionFleetDataCardholderPromptData'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionFleetDataCardholderPromptData'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionFleetDataCardholderPromptData'NonNullable
data IssuingTransactionFleetDataReportedBreakdown'NonNullable
instance Show IssuingTransactionFleetDataReportedBreakdown'NonNullable
instance Eq IssuingTransactionFleetDataReportedBreakdown'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionFleetDataReportedBreakdown'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionFleetDataReportedBreakdown'NonNullable
data IssuingTransactionFleetDataReportedBreakdown'NonNullableFuel'NonNullable
instance Show IssuingTransactionFleetDataReportedBreakdown'NonNullableFuel'NonNullable
instance Eq IssuingTransactionFleetDataReportedBreakdown'NonNullableFuel'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionFleetDataReportedBreakdown'NonNullableFuel'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionFleetDataReportedBreakdown'NonNullableFuel'NonNullable
data IssuingTransactionFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
instance Show IssuingTransactionFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
instance Eq IssuingTransactionFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
data IssuingTransactionFleetDataReportedBreakdown'NonNullableTax'NonNullable
instance Show IssuingTransactionFleetDataReportedBreakdown'NonNullableTax'NonNullable
instance Eq IssuingTransactionFleetDataReportedBreakdown'NonNullableTax'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionFleetDataReportedBreakdown'NonNullableTax'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionFleetDataReportedBreakdown'NonNullableTax'NonNullable
