module StripeAPI.Types.IssuingTransactionPurchaseDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingTransactionPurchaseDetails
instance Show IssuingTransactionPurchaseDetails
instance Eq IssuingTransactionPurchaseDetails
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetails
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetails
data IssuingTransactionPurchaseDetailsFleet'NonNullable
instance Show IssuingTransactionPurchaseDetailsFleet'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFleet'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsFleet'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsFleet'NonNullable
data IssuingTransactionPurchaseDetailsFleet'NonNullableCardholderPromptData'NonNullable
instance Show IssuingTransactionPurchaseDetailsFleet'NonNullableCardholderPromptData'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFleet'NonNullableCardholderPromptData'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsFleet'NonNullableCardholderPromptData'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsFleet'NonNullableCardholderPromptData'NonNullable
data IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullable
instance Show IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullable
data IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableFuel'NonNullable
instance Show IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableFuel'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableFuel'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableFuel'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableFuel'NonNullable
data IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableNonFuel'NonNullable
instance Show IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableNonFuel'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableNonFuel'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableNonFuel'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableNonFuel'NonNullable
data IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableTax'NonNullable
instance Show IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableTax'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableTax'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableTax'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsFleet'NonNullableReportedBreakdown'NonNullableTax'NonNullable
data IssuingTransactionPurchaseDetailsFlight'NonNullable
instance Show IssuingTransactionPurchaseDetailsFlight'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFlight'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsFlight'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsFlight'NonNullable
data IssuingTransactionPurchaseDetailsFuel'NonNullable
instance Show IssuingTransactionPurchaseDetailsFuel'NonNullable
instance Eq IssuingTransactionPurchaseDetailsFuel'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsFuel'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsFuel'NonNullable
data IssuingTransactionPurchaseDetailsLodging'NonNullable
instance Show IssuingTransactionPurchaseDetailsLodging'NonNullable
instance Eq IssuingTransactionPurchaseDetailsLodging'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionPurchaseDetailsLodging'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionPurchaseDetailsLodging'NonNullable
