module StripeAPI.Types.IssuingCardholderIndividual where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingCardholderIndividual
instance Show IssuingCardholderIndividual
instance Eq IssuingCardholderIndividual
instance Data.Aeson.FromJSON IssuingCardholderIndividual
instance Data.Aeson.ToJSON IssuingCardholderIndividual
data IssuingCardholderIndividualCardIssuing'NonNullable
instance Show IssuingCardholderIndividualCardIssuing'NonNullable
instance Eq IssuingCardholderIndividualCardIssuing'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderIndividualCardIssuing'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderIndividualCardIssuing'NonNullable
data IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
instance Show IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
instance Eq IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderIndividualCardIssuing'NonNullableUserTermsAcceptance'NonNullable
data IssuingCardholderIndividualDob'NonNullable
instance Show IssuingCardholderIndividualDob'NonNullable
instance Eq IssuingCardholderIndividualDob'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderIndividualDob'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderIndividualDob'NonNullable
data IssuingCardholderIndividualVerification'NonNullable
instance Show IssuingCardholderIndividualVerification'NonNullable
instance Eq IssuingCardholderIndividualVerification'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderIndividualVerification'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderIndividualVerification'NonNullable
data IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
instance Show IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
instance Eq IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullable
data IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
instance Show IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
instance Eq IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
instance Data.Aeson.FromJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
instance Data.Aeson.ToJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableBack'NonNullableVariants
data IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
instance Show IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
instance Eq IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
instance Data.Aeson.FromJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
instance Data.Aeson.ToJSON IssuingCardholderIndividualVerification'NonNullableDocument'NonNullableFront'NonNullableVariants
