module StripeAPI.Types.IssuingCardholderAuthorizationControls where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingCardholderAuthorizationControls
instance Show IssuingCardholderAuthorizationControls
instance Eq IssuingCardholderAuthorizationControls
instance Data.Aeson.FromJSON IssuingCardholderAuthorizationControls
instance Data.Aeson.ToJSON IssuingCardholderAuthorizationControls
data IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
instance Show IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
instance Eq IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderAuthorizationControlsAllowedCategories'NonNullable
data IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
instance Show IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
instance Eq IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderAuthorizationControlsBlockedCategories'NonNullable
