module StripeAPI.Types.IssuingDisputeDuplicateEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingDisputeDuplicateEvidence
instance Show IssuingDisputeDuplicateEvidence
instance Eq IssuingDisputeDuplicateEvidence
instance Data.Aeson.FromJSON IssuingDisputeDuplicateEvidence
instance Data.Aeson.ToJSON IssuingDisputeDuplicateEvidence
data IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeDuplicateEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
instance Show IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
instance Eq IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeDuplicateEvidenceCardStatement'NonNullableVariants
data IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
instance Show IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
instance Eq IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeDuplicateEvidenceCashReceipt'NonNullableVariants
data IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
instance Show IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
instance Eq IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeDuplicateEvidenceCheckImage'NonNullableVariants
