module StripeAPI.Types.IssuingDisputeOtherEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingDisputeOtherEvidence
instance Show IssuingDisputeOtherEvidence
instance Eq IssuingDisputeOtherEvidence
instance Data.Aeson.FromJSON IssuingDisputeOtherEvidence
instance Data.Aeson.ToJSON IssuingDisputeOtherEvidence
data IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeOtherEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeOtherEvidenceProductType'NonNullable
instance Show IssuingDisputeOtherEvidenceProductType'NonNullable
instance Eq IssuingDisputeOtherEvidenceProductType'NonNullable
instance Data.Aeson.FromJSON IssuingDisputeOtherEvidenceProductType'NonNullable
instance Data.Aeson.ToJSON IssuingDisputeOtherEvidenceProductType'NonNullable
