module StripeAPI.Types.IssuingAuthorizationVerificationData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingAuthorizationVerificationData
instance Show IssuingAuthorizationVerificationData
instance Eq IssuingAuthorizationVerificationData
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationData
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationData
data IssuingAuthorizationVerificationDataAddressLine1Check'
instance Show IssuingAuthorizationVerificationDataAddressLine1Check'
instance Eq IssuingAuthorizationVerificationDataAddressLine1Check'
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataAddressLine1Check'
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataAddressLine1Check'
data IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance Show IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance Eq IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataAddressPostalCodeCheck'
data IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
instance Show IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
instance Eq IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullable
data IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
instance Show IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
instance Eq IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableClaimedBy'
data IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
instance Show IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
instance Eq IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataAuthenticationExemption'NonNullableType'
data IssuingAuthorizationVerificationDataCvcCheck'
instance Show IssuingAuthorizationVerificationDataCvcCheck'
instance Eq IssuingAuthorizationVerificationDataCvcCheck'
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataCvcCheck'
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataCvcCheck'
data IssuingAuthorizationVerificationDataExpiryCheck'
instance Show IssuingAuthorizationVerificationDataExpiryCheck'
instance Eq IssuingAuthorizationVerificationDataExpiryCheck'
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataExpiryCheck'
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataExpiryCheck'
data IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
instance Show IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
instance Eq IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataThreeDSecure'NonNullable
data IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
instance Show IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
instance Eq IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
instance Data.Aeson.FromJSON IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
instance Data.Aeson.ToJSON IssuingAuthorizationVerificationDataThreeDSecure'NonNullableResult'
