module StripeAPI.Types.IssuingCardholderRequirements where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingCardholderRequirements
instance Show IssuingCardholderRequirements
instance Eq IssuingCardholderRequirements
instance Data.Aeson.FromJSON IssuingCardholderRequirements
instance Data.Aeson.ToJSON IssuingCardholderRequirements
data IssuingCardholderRequirementsDisabledReason'NonNullable
instance Show IssuingCardholderRequirementsDisabledReason'NonNullable
instance Eq IssuingCardholderRequirementsDisabledReason'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderRequirementsDisabledReason'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderRequirementsDisabledReason'NonNullable
data IssuingCardholderRequirementsPastDue'NonNullable
instance Show IssuingCardholderRequirementsPastDue'NonNullable
instance Eq IssuingCardholderRequirementsPastDue'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderRequirementsPastDue'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderRequirementsPastDue'NonNullable
