module StripeAPI.Types.IssuingTransactionAmountDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingTransactionAmountDetails
instance Show IssuingTransactionAmountDetails
instance Eq IssuingTransactionAmountDetails
instance Data.Aeson.FromJSON IssuingTransactionAmountDetails
instance Data.Aeson.ToJSON IssuingTransactionAmountDetails
