module StripeAPI.Types.IssuingAuthorizationFraudChallenge where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingAuthorizationFraudChallenge
instance Show IssuingAuthorizationFraudChallenge
instance Eq IssuingAuthorizationFraudChallenge
instance Data.Aeson.FromJSON IssuingAuthorizationFraudChallenge
instance Data.Aeson.ToJSON IssuingAuthorizationFraudChallenge
data IssuingAuthorizationFraudChallengeStatus'
instance Show IssuingAuthorizationFraudChallengeStatus'
instance Eq IssuingAuthorizationFraudChallengeStatus'
instance Data.Aeson.FromJSON IssuingAuthorizationFraudChallengeStatus'
instance Data.Aeson.ToJSON IssuingAuthorizationFraudChallengeStatus'
data IssuingAuthorizationFraudChallengeUndeliverableReason'NonNullable
instance Show IssuingAuthorizationFraudChallengeUndeliverableReason'NonNullable
instance Eq IssuingAuthorizationFraudChallengeUndeliverableReason'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFraudChallengeUndeliverableReason'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFraudChallengeUndeliverableReason'NonNullable
