module StripeAPI.Types.IssuingAuthorizationPendingRequest where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingAuthorizationPendingRequest
instance Show IssuingAuthorizationPendingRequest
instance Eq IssuingAuthorizationPendingRequest
instance Data.Aeson.FromJSON IssuingAuthorizationPendingRequest
instance Data.Aeson.ToJSON IssuingAuthorizationPendingRequest
data IssuingAuthorizationPendingRequestAmountDetails'NonNullable
instance Show IssuingAuthorizationPendingRequestAmountDetails'NonNullable
instance Eq IssuingAuthorizationPendingRequestAmountDetails'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationPendingRequestAmountDetails'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationPendingRequestAmountDetails'NonNullable
