module StripeAPI.Types.IssuingDisputeNoValidAuthorizationEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingDisputeNoValidAuthorizationEvidence
instance Show IssuingDisputeNoValidAuthorizationEvidence
instance Eq IssuingDisputeNoValidAuthorizationEvidence
instance Data.Aeson.FromJSON IssuingDisputeNoValidAuthorizationEvidence
instance Data.Aeson.ToJSON IssuingDisputeNoValidAuthorizationEvidence
data IssuingDisputeNoValidAuthorizationEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeNoValidAuthorizationEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeNoValidAuthorizationEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeNoValidAuthorizationEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeNoValidAuthorizationEvidenceAdditionalDocumentation'NonNullableVariants
