module StripeAPI.Types.IssuingDisputeMerchandiseNotAsDescribedEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingDisputeMerchandiseNotAsDescribedEvidence
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidence
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidence
instance Data.Aeson.FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidence
instance Data.Aeson.ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidence
data IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
instance Show IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
instance Eq IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
instance Data.Aeson.FromJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
instance Data.Aeson.ToJSON IssuingDisputeMerchandiseNotAsDescribedEvidenceReturnStatus'NonNullable
