module StripeAPI.Types.IssuingNetworkTokenWalletProvider where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingNetworkTokenWalletProvider
instance Show IssuingNetworkTokenWalletProvider
instance Eq IssuingNetworkTokenWalletProvider
instance Data.Aeson.FromJSON IssuingNetworkTokenWalletProvider
instance Data.Aeson.ToJSON IssuingNetworkTokenWalletProvider
data IssuingNetworkTokenWalletProviderCardNumberSource'
instance Show IssuingNetworkTokenWalletProviderCardNumberSource'
instance Eq IssuingNetworkTokenWalletProviderCardNumberSource'
instance Data.Aeson.FromJSON IssuingNetworkTokenWalletProviderCardNumberSource'
instance Data.Aeson.ToJSON IssuingNetworkTokenWalletProviderCardNumberSource'
data IssuingNetworkTokenWalletProviderReasonCodes'
instance Show IssuingNetworkTokenWalletProviderReasonCodes'
instance Eq IssuingNetworkTokenWalletProviderReasonCodes'
instance Data.Aeson.FromJSON IssuingNetworkTokenWalletProviderReasonCodes'
instance Data.Aeson.ToJSON IssuingNetworkTokenWalletProviderReasonCodes'
data IssuingNetworkTokenWalletProviderSuggestedDecision'
instance Show IssuingNetworkTokenWalletProviderSuggestedDecision'
instance Eq IssuingNetworkTokenWalletProviderSuggestedDecision'
instance Data.Aeson.FromJSON IssuingNetworkTokenWalletProviderSuggestedDecision'
instance Data.Aeson.ToJSON IssuingNetworkTokenWalletProviderSuggestedDecision'
