module StripeAPI.Types.IssuingDisputeCanceledEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingDisputeCanceledEvidence
instance Show IssuingDisputeCanceledEvidence
instance Eq IssuingDisputeCanceledEvidence
instance Data.Aeson.FromJSON IssuingDisputeCanceledEvidence
instance Data.Aeson.ToJSON IssuingDisputeCanceledEvidence
data IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeCanceledEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeCanceledEvidenceProductType'NonNullable
instance Show IssuingDisputeCanceledEvidenceProductType'NonNullable
instance Eq IssuingDisputeCanceledEvidenceProductType'NonNullable
instance Data.Aeson.FromJSON IssuingDisputeCanceledEvidenceProductType'NonNullable
instance Data.Aeson.ToJSON IssuingDisputeCanceledEvidenceProductType'NonNullable
data IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
instance Show IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
instance Eq IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
instance Data.Aeson.FromJSON IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
instance Data.Aeson.ToJSON IssuingDisputeCanceledEvidenceReturnStatus'NonNullable
