module StripeAPI.Types.IssuingCardholderCardIssuing where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingCardholderCardIssuing
instance Show IssuingCardholderCardIssuing
instance Eq IssuingCardholderCardIssuing
instance Data.Aeson.FromJSON IssuingCardholderCardIssuing
instance Data.Aeson.ToJSON IssuingCardholderCardIssuing
data IssuingCardholderCardIssuingUserTermsAcceptance'NonNullable
instance Show IssuingCardholderCardIssuingUserTermsAcceptance'NonNullable
instance Eq IssuingCardholderCardIssuingUserTermsAcceptance'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderCardIssuingUserTermsAcceptance'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderCardIssuingUserTermsAcceptance'NonNullable
