module StripeAPI.Types.IssuingCardAuthorizationControls where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingCardAuthorizationControls
instance Show IssuingCardAuthorizationControls
instance Eq IssuingCardAuthorizationControls
instance Data.Aeson.FromJSON IssuingCardAuthorizationControls
instance Data.Aeson.ToJSON IssuingCardAuthorizationControls
data IssuingCardAuthorizationControlsAllowedCategories'NonNullable
instance Show IssuingCardAuthorizationControlsAllowedCategories'NonNullable
instance Eq IssuingCardAuthorizationControlsAllowedCategories'NonNullable
instance Data.Aeson.FromJSON IssuingCardAuthorizationControlsAllowedCategories'NonNullable
instance Data.Aeson.ToJSON IssuingCardAuthorizationControlsAllowedCategories'NonNullable
data IssuingCardAuthorizationControlsBlockedCategories'NonNullable
instance Show IssuingCardAuthorizationControlsBlockedCategories'NonNullable
instance Eq IssuingCardAuthorizationControlsBlockedCategories'NonNullable
instance Data.Aeson.FromJSON IssuingCardAuthorizationControlsBlockedCategories'NonNullable
instance Data.Aeson.ToJSON IssuingCardAuthorizationControlsBlockedCategories'NonNullable
