module StripeAPI.Types.IssuingCardShippingAddressValidation where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingCardShippingAddressValidation
instance Show IssuingCardShippingAddressValidation
instance Eq IssuingCardShippingAddressValidation
instance Data.Aeson.FromJSON IssuingCardShippingAddressValidation
instance Data.Aeson.ToJSON IssuingCardShippingAddressValidation
data IssuingCardShippingAddressValidationMode'
instance Show IssuingCardShippingAddressValidationMode'
instance Eq IssuingCardShippingAddressValidationMode'
instance Data.Aeson.FromJSON IssuingCardShippingAddressValidationMode'
instance Data.Aeson.ToJSON IssuingCardShippingAddressValidationMode'
data IssuingCardShippingAddressValidationNormalizedAddress'NonNullable
instance Show IssuingCardShippingAddressValidationNormalizedAddress'NonNullable
instance Eq IssuingCardShippingAddressValidationNormalizedAddress'NonNullable
instance Data.Aeson.FromJSON IssuingCardShippingAddressValidationNormalizedAddress'NonNullable
instance Data.Aeson.ToJSON IssuingCardShippingAddressValidationNormalizedAddress'NonNullable
data IssuingCardShippingAddressValidationResult'NonNullable
instance Show IssuingCardShippingAddressValidationResult'NonNullable
instance Eq IssuingCardShippingAddressValidationResult'NonNullable
instance Data.Aeson.FromJSON IssuingCardShippingAddressValidationResult'NonNullable
instance Data.Aeson.ToJSON IssuingCardShippingAddressValidationResult'NonNullable
