module StripeAPI.Types.IssuingPersonalizationDesignRejectionReasons where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingPersonalizationDesignRejectionReasons
instance Show IssuingPersonalizationDesignRejectionReasons
instance Eq IssuingPersonalizationDesignRejectionReasons
instance Data.Aeson.FromJSON IssuingPersonalizationDesignRejectionReasons
instance Data.Aeson.ToJSON IssuingPersonalizationDesignRejectionReasons
data IssuingPersonalizationDesignRejectionReasonsCardLogo'NonNullable
instance Show IssuingPersonalizationDesignRejectionReasonsCardLogo'NonNullable
instance Eq IssuingPersonalizationDesignRejectionReasonsCardLogo'NonNullable
instance Data.Aeson.FromJSON IssuingPersonalizationDesignRejectionReasonsCardLogo'NonNullable
instance Data.Aeson.ToJSON IssuingPersonalizationDesignRejectionReasonsCardLogo'NonNullable
data IssuingPersonalizationDesignRejectionReasonsCarrierText'NonNullable
instance Show IssuingPersonalizationDesignRejectionReasonsCarrierText'NonNullable
instance Eq IssuingPersonalizationDesignRejectionReasonsCarrierText'NonNullable
instance Data.Aeson.FromJSON IssuingPersonalizationDesignRejectionReasonsCarrierText'NonNullable
instance Data.Aeson.ToJSON IssuingPersonalizationDesignRejectionReasonsCarrierText'NonNullable
