module StripeAPI.Types.IssuingTransactionFleetReportedBreakdown where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingTransactionFleetReportedBreakdown
instance Show IssuingTransactionFleetReportedBreakdown
instance Eq IssuingTransactionFleetReportedBreakdown
instance Data.Aeson.FromJSON IssuingTransactionFleetReportedBreakdown
instance Data.Aeson.ToJSON IssuingTransactionFleetReportedBreakdown
data IssuingTransactionFleetReportedBreakdownFuel'NonNullable
instance Show IssuingTransactionFleetReportedBreakdownFuel'NonNullable
instance Eq IssuingTransactionFleetReportedBreakdownFuel'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionFleetReportedBreakdownFuel'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionFleetReportedBreakdownFuel'NonNullable
data IssuingTransactionFleetReportedBreakdownNonFuel'NonNullable
instance Show IssuingTransactionFleetReportedBreakdownNonFuel'NonNullable
instance Eq IssuingTransactionFleetReportedBreakdownNonFuel'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionFleetReportedBreakdownNonFuel'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionFleetReportedBreakdownNonFuel'NonNullable
data IssuingTransactionFleetReportedBreakdownTax'NonNullable
instance Show IssuingTransactionFleetReportedBreakdownTax'NonNullable
instance Eq IssuingTransactionFleetReportedBreakdownTax'NonNullable
instance Data.Aeson.FromJSON IssuingTransactionFleetReportedBreakdownTax'NonNullable
instance Data.Aeson.ToJSON IssuingTransactionFleetReportedBreakdownTax'NonNullable
