module StripeAPI.Types.IssuingAuthorizationAuthenticationExemption where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingAuthorizationAuthenticationExemption
instance Show IssuingAuthorizationAuthenticationExemption
instance Eq IssuingAuthorizationAuthenticationExemption
instance Data.Aeson.FromJSON IssuingAuthorizationAuthenticationExemption
instance Data.Aeson.ToJSON IssuingAuthorizationAuthenticationExemption
data IssuingAuthorizationAuthenticationExemptionClaimedBy'
instance Show IssuingAuthorizationAuthenticationExemptionClaimedBy'
instance Eq IssuingAuthorizationAuthenticationExemptionClaimedBy'
instance Data.Aeson.FromJSON IssuingAuthorizationAuthenticationExemptionClaimedBy'
instance Data.Aeson.ToJSON IssuingAuthorizationAuthenticationExemptionClaimedBy'
data IssuingAuthorizationAuthenticationExemptionType'
instance Show IssuingAuthorizationAuthenticationExemptionType'
instance Eq IssuingAuthorizationAuthenticationExemptionType'
instance Data.Aeson.FromJSON IssuingAuthorizationAuthenticationExemptionType'
instance Data.Aeson.ToJSON IssuingAuthorizationAuthenticationExemptionType'
