module StripeAPI.Types.IssuingDisputeFraudulentEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingDisputeFraudulentEvidence
instance Show IssuingDisputeFraudulentEvidence
instance Eq IssuingDisputeFraudulentEvidence
instance Data.Aeson.FromJSON IssuingDisputeFraudulentEvidence
instance Data.Aeson.ToJSON IssuingDisputeFraudulentEvidence
data IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeFraudulentEvidenceAdditionalDocumentation'NonNullableVariants
