module StripeAPI.Types.IssuingDisputeNotReceivedEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingDisputeNotReceivedEvidence
instance Show IssuingDisputeNotReceivedEvidence
instance Eq IssuingDisputeNotReceivedEvidence
instance Data.Aeson.FromJSON IssuingDisputeNotReceivedEvidence
instance Data.Aeson.ToJSON IssuingDisputeNotReceivedEvidence
data IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeNotReceivedEvidenceAdditionalDocumentation'NonNullableVariants
data IssuingDisputeNotReceivedEvidenceProductType'NonNullable
instance Show IssuingDisputeNotReceivedEvidenceProductType'NonNullable
instance Eq IssuingDisputeNotReceivedEvidenceProductType'NonNullable
instance Data.Aeson.FromJSON IssuingDisputeNotReceivedEvidenceProductType'NonNullable
instance Data.Aeson.ToJSON IssuingDisputeNotReceivedEvidenceProductType'NonNullable
