module StripeAPI.Types.IssuingAuthorizationFleetData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingAuthorizationFleetData
instance Show IssuingAuthorizationFleetData
instance Eq IssuingAuthorizationFleetData
instance Data.Aeson.FromJSON IssuingAuthorizationFleetData
instance Data.Aeson.ToJSON IssuingAuthorizationFleetData
data IssuingAuthorizationFleetDataCardholderPromptData'NonNullable
instance Show IssuingAuthorizationFleetDataCardholderPromptData'NonNullable
instance Eq IssuingAuthorizationFleetDataCardholderPromptData'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetDataCardholderPromptData'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetDataCardholderPromptData'NonNullable
data IssuingAuthorizationFleetDataPurchaseType'NonNullable
instance Show IssuingAuthorizationFleetDataPurchaseType'NonNullable
instance Eq IssuingAuthorizationFleetDataPurchaseType'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetDataPurchaseType'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetDataPurchaseType'NonNullable
data IssuingAuthorizationFleetDataReportedBreakdown'NonNullable
instance Show IssuingAuthorizationFleetDataReportedBreakdown'NonNullable
instance Eq IssuingAuthorizationFleetDataReportedBreakdown'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetDataReportedBreakdown'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetDataReportedBreakdown'NonNullable
data IssuingAuthorizationFleetDataReportedBreakdown'NonNullableFuel'NonNullable
instance Show IssuingAuthorizationFleetDataReportedBreakdown'NonNullableFuel'NonNullable
instance Eq IssuingAuthorizationFleetDataReportedBreakdown'NonNullableFuel'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetDataReportedBreakdown'NonNullableFuel'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetDataReportedBreakdown'NonNullableFuel'NonNullable
data IssuingAuthorizationFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
instance Show IssuingAuthorizationFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
instance Eq IssuingAuthorizationFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetDataReportedBreakdown'NonNullableNonFuel'NonNullable
data IssuingAuthorizationFleetDataReportedBreakdown'NonNullableTax'NonNullable
instance Show IssuingAuthorizationFleetDataReportedBreakdown'NonNullableTax'NonNullable
instance Eq IssuingAuthorizationFleetDataReportedBreakdown'NonNullableTax'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetDataReportedBreakdown'NonNullableTax'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetDataReportedBreakdown'NonNullableTax'NonNullable
data IssuingAuthorizationFleetDataServiceType'NonNullable
instance Show IssuingAuthorizationFleetDataServiceType'NonNullable
instance Eq IssuingAuthorizationFleetDataServiceType'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetDataServiceType'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetDataServiceType'NonNullable
