module StripeAPI.Types.IssuingAuthorizationTreasury where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingAuthorizationTreasury
instance Show IssuingAuthorizationTreasury
instance Eq IssuingAuthorizationTreasury
instance Data.Aeson.FromJSON IssuingAuthorizationTreasury
instance Data.Aeson.ToJSON IssuingAuthorizationTreasury
