module StripeAPI.Types.IssuingDisputeServiceNotAsDescribedEvidence where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingDisputeServiceNotAsDescribedEvidence
instance Show IssuingDisputeServiceNotAsDescribedEvidence
instance Eq IssuingDisputeServiceNotAsDescribedEvidence
instance Data.Aeson.FromJSON IssuingDisputeServiceNotAsDescribedEvidence
instance Data.Aeson.ToJSON IssuingDisputeServiceNotAsDescribedEvidence
data IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Show IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Eq IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.FromJSON IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
instance Data.Aeson.ToJSON IssuingDisputeServiceNotAsDescribedEvidenceAdditionalDocumentation'NonNullableVariants
