module StripeAPI.Types.IssuingCardholderVerification where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingCardholderVerification
instance Show IssuingCardholderVerification
instance Eq IssuingCardholderVerification
instance Data.Aeson.FromJSON IssuingCardholderVerification
instance Data.Aeson.ToJSON IssuingCardholderVerification
data IssuingCardholderVerificationDocument'NonNullable
instance Show IssuingCardholderVerificationDocument'NonNullable
instance Eq IssuingCardholderVerificationDocument'NonNullable
instance Data.Aeson.FromJSON IssuingCardholderVerificationDocument'NonNullable
instance Data.Aeson.ToJSON IssuingCardholderVerificationDocument'NonNullable
data IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
instance Show IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
instance Eq IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
instance Data.Aeson.FromJSON IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
instance Data.Aeson.ToJSON IssuingCardholderVerificationDocument'NonNullableBack'NonNullableVariants
data IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
instance Show IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
instance Eq IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
instance Data.Aeson.FromJSON IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
instance Data.Aeson.ToJSON IssuingCardholderVerificationDocument'NonNullableFront'NonNullableVariants
