module StripeAPI.Types.IssuingAuthorizationFleetReportedBreakdown where
import qualified Data.Aeson
import qualified StripeAPI.Common
data IssuingAuthorizationFleetReportedBreakdown
instance Show IssuingAuthorizationFleetReportedBreakdown
instance Eq IssuingAuthorizationFleetReportedBreakdown
instance Data.Aeson.FromJSON IssuingAuthorizationFleetReportedBreakdown
instance Data.Aeson.ToJSON IssuingAuthorizationFleetReportedBreakdown
data IssuingAuthorizationFleetReportedBreakdownFuel'NonNullable
instance Show IssuingAuthorizationFleetReportedBreakdownFuel'NonNullable
instance Eq IssuingAuthorizationFleetReportedBreakdownFuel'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetReportedBreakdownFuel'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetReportedBreakdownFuel'NonNullable
data IssuingAuthorizationFleetReportedBreakdownNonFuel'NonNullable
instance Show IssuingAuthorizationFleetReportedBreakdownNonFuel'NonNullable
instance Eq IssuingAuthorizationFleetReportedBreakdownNonFuel'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetReportedBreakdownNonFuel'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetReportedBreakdownNonFuel'NonNullable
data IssuingAuthorizationFleetReportedBreakdownTax'NonNullable
instance Show IssuingAuthorizationFleetReportedBreakdownTax'NonNullable
instance Eq IssuingAuthorizationFleetReportedBreakdownTax'NonNullable
instance Data.Aeson.FromJSON IssuingAuthorizationFleetReportedBreakdownTax'NonNullable
instance Data.Aeson.ToJSON IssuingAuthorizationFleetReportedBreakdownTax'NonNullable
