module StripeAPI.Types.LegalEntityPersonVerification where
import qualified Data.Aeson
import qualified StripeAPI.Common
data LegalEntityPersonVerification
instance Show LegalEntityPersonVerification
instance Eq LegalEntityPersonVerification
instance Data.Aeson.FromJSON LegalEntityPersonVerification
instance Data.Aeson.ToJSON LegalEntityPersonVerification
data LegalEntityPersonVerificationAdditionalDocument'NonNullable
instance Show LegalEntityPersonVerificationAdditionalDocument'NonNullable
instance Eq LegalEntityPersonVerificationAdditionalDocument'NonNullable
instance Data.Aeson.FromJSON LegalEntityPersonVerificationAdditionalDocument'NonNullable
instance Data.Aeson.ToJSON LegalEntityPersonVerificationAdditionalDocument'NonNullable
data LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
instance Show LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
instance Eq LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
instance Data.Aeson.FromJSON LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
instance Data.Aeson.ToJSON LegalEntityPersonVerificationAdditionalDocument'NonNullableBack'NonNullableVariants
data LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
instance Show LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
instance Eq LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
instance Data.Aeson.FromJSON LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
instance Data.Aeson.ToJSON LegalEntityPersonVerificationAdditionalDocument'NonNullableFront'NonNullableVariants
