module StripeAPI.Types.LegalEntityCompanyVerificationDocument where
import qualified Data.Aeson
import qualified StripeAPI.Common
data LegalEntityCompanyVerificationDocument
instance Show LegalEntityCompanyVerificationDocument
instance Eq LegalEntityCompanyVerificationDocument
instance Data.Aeson.FromJSON LegalEntityCompanyVerificationDocument
instance Data.Aeson.ToJSON LegalEntityCompanyVerificationDocument
data LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
instance Show LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
instance Eq LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
instance Data.Aeson.FromJSON LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
instance Data.Aeson.ToJSON LegalEntityCompanyVerificationDocumentBack'NonNullableVariants
data LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
instance Show LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
instance Eq LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
instance Data.Aeson.FromJSON LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
instance Data.Aeson.ToJSON LegalEntityCompanyVerificationDocumentFront'NonNullableVariants
