module StripeAPI.Types.LegalEntityPersonVerificationDocument where
import qualified Data.Aeson
import qualified StripeAPI.Common
data LegalEntityPersonVerificationDocument
instance Show LegalEntityPersonVerificationDocument
instance Eq LegalEntityPersonVerificationDocument
instance Data.Aeson.FromJSON LegalEntityPersonVerificationDocument
instance Data.Aeson.ToJSON LegalEntityPersonVerificationDocument
data LegalEntityPersonVerificationDocumentBack'NonNullableVariants
instance Show LegalEntityPersonVerificationDocumentBack'NonNullableVariants
instance Eq LegalEntityPersonVerificationDocumentBack'NonNullableVariants
instance Data.Aeson.FromJSON LegalEntityPersonVerificationDocumentBack'NonNullableVariants
instance Data.Aeson.ToJSON LegalEntityPersonVerificationDocumentBack'NonNullableVariants
data LegalEntityPersonVerificationDocumentFront'NonNullableVariants
instance Show LegalEntityPersonVerificationDocumentFront'NonNullableVariants
instance Eq LegalEntityPersonVerificationDocumentFront'NonNullableVariants
instance Data.Aeson.FromJSON LegalEntityPersonVerificationDocumentFront'NonNullableVariants
instance Data.Aeson.ToJSON LegalEntityPersonVerificationDocumentFront'NonNullableVariants
