module StripeAPI.Types.PaymentMethodDetailsPaypal where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsPaypal
instance Show PaymentMethodDetailsPaypal
instance Eq PaymentMethodDetailsPaypal
instance Data.Aeson.FromJSON PaymentMethodDetailsPaypal
instance Data.Aeson.ToJSON PaymentMethodDetailsPaypal
data PaymentMethodDetailsPaypalSellerProtection'NonNullable
instance Show PaymentMethodDetailsPaypalSellerProtection'NonNullable
instance Eq PaymentMethodDetailsPaypalSellerProtection'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsPaypalSellerProtection'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsPaypalSellerProtection'NonNullable
data PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
instance Show PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
instance Eq PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsPaypalSellerProtection'NonNullableDisputeCategories'NonNullable
data PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
instance Show PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
instance Eq PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
instance Data.Aeson.FromJSON PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
instance Data.Aeson.ToJSON PaymentMethodDetailsPaypalSellerProtection'NonNullableStatus'
