module StripeAPI.Types.PaymentMethodCardWalletMasterpass where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodCardWalletMasterpass
instance Show PaymentMethodCardWalletMasterpass
instance Eq PaymentMethodCardWalletMasterpass
instance Data.Aeson.FromJSON PaymentMethodCardWalletMasterpass
instance Data.Aeson.ToJSON PaymentMethodCardWalletMasterpass
data PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
instance Show PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
instance Eq PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodCardWalletMasterpassBillingAddress'NonNullable
data PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
instance Show PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
instance Eq PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodCardWalletMasterpassShippingAddress'NonNullable
