module StripeAPI.Types.PaymentLinksResourceCompletionBehaviorConfirmationPage where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceCompletionBehaviorConfirmationPage
instance Show PaymentLinksResourceCompletionBehaviorConfirmationPage
instance Eq PaymentLinksResourceCompletionBehaviorConfirmationPage
instance Data.Aeson.FromJSON PaymentLinksResourceCompletionBehaviorConfirmationPage
instance Data.Aeson.ToJSON PaymentLinksResourceCompletionBehaviorConfirmationPage
