module StripeAPI.Types.PaymentMethodOptionsCardPresentRouting where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsCardPresentRouting
instance Show PaymentMethodOptionsCardPresentRouting
instance Eq PaymentMethodOptionsCardPresentRouting
instance Data.Aeson.FromJSON PaymentMethodOptionsCardPresentRouting
instance Data.Aeson.ToJSON PaymentMethodOptionsCardPresentRouting
data PaymentMethodOptionsCardPresentRoutingRequestedPriority'NonNullable
instance Show PaymentMethodOptionsCardPresentRoutingRequestedPriority'NonNullable
instance Eq PaymentMethodOptionsCardPresentRoutingRequestedPriority'NonNullable
instance Data.Aeson.FromJSON PaymentMethodOptionsCardPresentRoutingRequestedPriority'NonNullable
instance Data.Aeson.ToJSON PaymentMethodOptionsCardPresentRoutingRequestedPriority'NonNullable
