module StripeAPI.Types.PaymentLinksResourceInvoiceSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceInvoiceSettings
instance Show PaymentLinksResourceInvoiceSettings
instance Eq PaymentLinksResourceInvoiceSettings
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceSettings
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceSettings
data PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Show PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Eq PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceSettingsAccountTaxIds'NonNullableVariants
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
instance Show PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
instance Eq PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullable
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Show PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Eq PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableAccount'Variants
data PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
instance Show PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
instance Eq PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceSettingsIssuer'NonNullableType'
data PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance Show PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance Eq PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceSettingsRenderingOptions'NonNullable
