module StripeAPI.Types.PaymentIntentPaymentMethodOptionsBlik where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsBlik
instance Show PaymentIntentPaymentMethodOptionsBlik
instance Eq PaymentIntentPaymentMethodOptionsBlik
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsBlik
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsBlik
data PaymentIntentPaymentMethodOptionsBlikSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsBlikSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsBlikSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsBlikSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsBlikSetupFutureUsage'
