module StripeAPI.Types.PaymentMethodCardGeneratedCard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodCardGeneratedCard
instance Show PaymentMethodCardGeneratedCard
instance Eq PaymentMethodCardGeneratedCard
instance Data.Aeson.FromJSON PaymentMethodCardGeneratedCard
instance Data.Aeson.ToJSON PaymentMethodCardGeneratedCard
data PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
instance Show PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
instance Eq PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
instance Data.Aeson.FromJSON PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
instance Data.Aeson.ToJSON PaymentMethodCardGeneratedCardPaymentMethodDetails'NonNullable
data PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
instance Show PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
instance Eq PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
instance Data.Aeson.FromJSON PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
instance Data.Aeson.ToJSON PaymentMethodCardGeneratedCardSetupAttempt'NonNullableVariants
