module StripeAPI.Types.PaymentIntentPaymentMethodOptionsNzBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsNzBankAccount
instance Show PaymentIntentPaymentMethodOptionsNzBankAccount
instance Eq PaymentIntentPaymentMethodOptionsNzBankAccount
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsNzBankAccount
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsNzBankAccount
data PaymentIntentPaymentMethodOptionsNzBankAccountSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsNzBankAccountSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsNzBankAccountSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsNzBankAccountSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsNzBankAccountSetupFutureUsage'
