module StripeAPI.Types.PaymentMethodSepaDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodSepaDebit
instance Show PaymentMethodSepaDebit
instance Eq PaymentMethodSepaDebit
instance Data.Aeson.FromJSON PaymentMethodSepaDebit
instance Data.Aeson.ToJSON PaymentMethodSepaDebit
data PaymentMethodSepaDebitGeneratedFrom'NonNullable
instance Show PaymentMethodSepaDebitGeneratedFrom'NonNullable
instance Eq PaymentMethodSepaDebitGeneratedFrom'NonNullable
instance Data.Aeson.FromJSON PaymentMethodSepaDebitGeneratedFrom'NonNullable
instance Data.Aeson.ToJSON PaymentMethodSepaDebitGeneratedFrom'NonNullable
data PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
instance Show PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
instance Eq PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
instance Data.Aeson.FromJSON PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
instance Data.Aeson.ToJSON PaymentMethodSepaDebitGeneratedFrom'NonNullableCharge'NonNullableVariants
data PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
instance Show PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
instance Eq PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
instance Data.Aeson.FromJSON PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
instance Data.Aeson.ToJSON PaymentMethodSepaDebitGeneratedFrom'NonNullableSetupAttempt'NonNullableVariants
