module StripeAPI.Types.PaymentLinksResourceOptionalItem where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceOptionalItem
instance Show PaymentLinksResourceOptionalItem
instance Eq PaymentLinksResourceOptionalItem
instance Data.Aeson.FromJSON PaymentLinksResourceOptionalItem
instance Data.Aeson.ToJSON PaymentLinksResourceOptionalItem
data PaymentLinksResourceOptionalItemAdjustableQuantity'NonNullable
instance Show PaymentLinksResourceOptionalItemAdjustableQuantity'NonNullable
instance Eq PaymentLinksResourceOptionalItemAdjustableQuantity'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceOptionalItemAdjustableQuantity'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceOptionalItemAdjustableQuantity'NonNullable
