module StripeAPI.Types.PaymentPagesCheckoutSessionPermissions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionPermissions
instance Show PaymentPagesCheckoutSessionPermissions
instance Eq PaymentPagesCheckoutSessionPermissions
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionPermissions
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionPermissions
data PaymentPagesCheckoutSessionPermissionsUpdateShippingDetails'NonNullable
instance Show PaymentPagesCheckoutSessionPermissionsUpdateShippingDetails'NonNullable
instance Eq PaymentPagesCheckoutSessionPermissionsUpdateShippingDetails'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionPermissionsUpdateShippingDetails'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionPermissionsUpdateShippingDetails'NonNullable
