module StripeAPI.Types.PaymentMethodConfigBizPaymentMethodConfigurationDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodConfigBizPaymentMethodConfigurationDetails
instance Show PaymentMethodConfigBizPaymentMethodConfigurationDetails
instance Eq PaymentMethodConfigBizPaymentMethodConfigurationDetails
instance Data.Aeson.FromJSON PaymentMethodConfigBizPaymentMethodConfigurationDetails
instance Data.Aeson.ToJSON PaymentMethodConfigBizPaymentMethodConfigurationDetails
