module StripeAPI.Types.PaymentPagesCheckoutSessionAutomaticTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionAutomaticTax
instance Show PaymentPagesCheckoutSessionAutomaticTax
instance Eq PaymentPagesCheckoutSessionAutomaticTax
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionAutomaticTax
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionAutomaticTax
data PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
instance Show PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
instance Eq PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullable
data PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
instance Show PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableAccount'Variants
data PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
instance Show PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
instance Eq PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionAutomaticTaxLiability'NonNullableType'
data PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance Show PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance Eq PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionAutomaticTaxStatus'NonNullable
