module StripeAPI.Types.PaymentPagesCheckoutSessionInvoiceSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionInvoiceSettings
instance Show PaymentPagesCheckoutSessionInvoiceSettings
instance Eq PaymentPagesCheckoutSessionInvoiceSettings
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionInvoiceSettings
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionInvoiceSettings
data PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Show PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsAccountTaxIds'NonNullableVariants
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
instance Show PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullable
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Show PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableAccount'Variants
data PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
instance Show PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsIssuer'NonNullableType'
data PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance Show PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance Eq PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionInvoiceSettingsRenderingOptions'NonNullable
