module StripeAPI.Types.PaymentLinksResourceCustomFieldsText where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceCustomFieldsText
instance Show PaymentLinksResourceCustomFieldsText
instance Eq PaymentLinksResourceCustomFieldsText
instance Data.Aeson.FromJSON PaymentLinksResourceCustomFieldsText
instance Data.Aeson.ToJSON PaymentLinksResourceCustomFieldsText
