module StripeAPI.Types.PaymentMethodDetailsSofort where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsSofort
instance Show PaymentMethodDetailsSofort
instance Eq PaymentMethodDetailsSofort
instance Data.Aeson.FromJSON PaymentMethodDetailsSofort
instance Data.Aeson.ToJSON PaymentMethodDetailsSofort
data PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Show PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Eq PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.FromJSON PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.ToJSON PaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
data PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Show PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Eq PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.FromJSON PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.ToJSON PaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
data PaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Show PaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Eq PaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsSofortPreferredLanguage'NonNullable
