module StripeAPI.Types.PaymentLinksResourceConsentCollection where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceConsentCollection
instance Show PaymentLinksResourceConsentCollection
instance Eq PaymentLinksResourceConsentCollection
instance Data.Aeson.FromJSON PaymentLinksResourceConsentCollection
instance Data.Aeson.ToJSON PaymentLinksResourceConsentCollection
data PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Show PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Eq PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullable
data PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Show PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Eq PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Data.Aeson.FromJSON PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Data.Aeson.ToJSON PaymentLinksResourceConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
data PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance Show PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance Eq PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceConsentCollectionPromotions'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceConsentCollectionPromotions'NonNullable
data PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
instance Show PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
instance Eq PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceConsentCollectionTermsOfService'NonNullable
