module StripeAPI.Types.PaymentLinksResourceShippingAddressCollection where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceShippingAddressCollection
instance Show PaymentLinksResourceShippingAddressCollection
instance Eq PaymentLinksResourceShippingAddressCollection
instance Data.Aeson.FromJSON PaymentLinksResourceShippingAddressCollection
instance Data.Aeson.ToJSON PaymentLinksResourceShippingAddressCollection
data PaymentLinksResourceShippingAddressCollectionAllowedCountries'
instance Show PaymentLinksResourceShippingAddressCollectionAllowedCountries'
instance Eq PaymentLinksResourceShippingAddressCollectionAllowedCountries'
instance Data.Aeson.FromJSON PaymentLinksResourceShippingAddressCollectionAllowedCountries'
instance Data.Aeson.ToJSON PaymentLinksResourceShippingAddressCollectionAllowedCountries'
