module StripeAPI.Types.PaymentMethodDetailsLink where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsLink
instance Show PaymentMethodDetailsLink
instance Eq PaymentMethodDetailsLink
instance Data.Aeson.FromJSON PaymentMethodDetailsLink
instance Data.Aeson.ToJSON PaymentMethodDetailsLink
