module StripeAPI.Types.PaymentPagesCheckoutSessionPaymentMethodReuseAgreement where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
instance Show PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
instance Eq PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionPaymentMethodReuseAgreement
data PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
instance Show PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
instance Eq PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionPaymentMethodReuseAgreementPosition'
