module StripeAPI.Types.PaymentMethodDetailsBancontact where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsBancontact
instance Show PaymentMethodDetailsBancontact
instance Eq PaymentMethodDetailsBancontact
instance Data.Aeson.FromJSON PaymentMethodDetailsBancontact
instance Data.Aeson.ToJSON PaymentMethodDetailsBancontact
data PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Show PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Eq PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.FromJSON PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.ToJSON PaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
data PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Show PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Eq PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.FromJSON PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.ToJSON PaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
data PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Show PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Eq PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsBancontactPreferredLanguage'NonNullable
