module StripeAPI.Types.PaymentLinksResourcePaymentIntentData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourcePaymentIntentData
instance Show PaymentLinksResourcePaymentIntentData
instance Eq PaymentLinksResourcePaymentIntentData
instance Data.Aeson.FromJSON PaymentLinksResourcePaymentIntentData
instance Data.Aeson.ToJSON PaymentLinksResourcePaymentIntentData
data PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
instance Show PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
instance Eq PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourcePaymentIntentDataCaptureMethod'NonNullable
data PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
instance Show PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
instance Eq PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourcePaymentIntentDataSetupFutureUsage'NonNullable
