module StripeAPI.Types.PaymentLinksResourceInvoiceCreation where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceInvoiceCreation
instance Show PaymentLinksResourceInvoiceCreation
instance Eq PaymentLinksResourceInvoiceCreation
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceCreation
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceCreation
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullable
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableAccountTaxIds'NonNullableVariants
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullable
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableAccount'Variants
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableIssuer'NonNullableType'
data PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
instance Show PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
instance Eq PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceInvoiceCreationInvoiceData'NonNullableRenderingOptions'NonNullable
