{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PaymentLinksResourceOptionalItemAdjustableQuantity
module StripeAPI.Types.PaymentLinksResourceOptionalItemAdjustableQuantity where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.payment_links_resource_optional_item_adjustable_quantity@ in the specification.
data PaymentLinksResourceOptionalItemAdjustableQuantity = PaymentLinksResourceOptionalItemAdjustableQuantity
  { -- | enabled: Set to true if the quantity can be adjusted to any non-negative integer.
    paymentLinksResourceOptionalItemAdjustableQuantityEnabled :: GHC.Types.Bool,
    -- | maximum: The maximum quantity of this item the customer can purchase. By default this value is 99.
    paymentLinksResourceOptionalItemAdjustableQuantityMaximum :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable GHC.Types.Int)),
    -- | minimum: The minimum quantity of this item the customer must purchase, if they choose to purchase it. Because this item is optional, the customer will always be able to remove it from their order, even if the \`minimum\` configured here is greater than 0. By default this value is 0.
    paymentLinksResourceOptionalItemAdjustableQuantityMinimum :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable GHC.Types.Int))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaymentLinksResourceOptionalItemAdjustableQuantity where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= paymentLinksResourceOptionalItemAdjustableQuantityEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("maximum" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceOptionalItemAdjustableQuantityMaximum obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("minimum" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceOptionalItemAdjustableQuantityMinimum obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= paymentLinksResourceOptionalItemAdjustableQuantityEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("maximum" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceOptionalItemAdjustableQuantityMaximum obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("minimum" Data.Aeson.Types.ToJSON..=)) (paymentLinksResourceOptionalItemAdjustableQuantityMinimum obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PaymentLinksResourceOptionalItemAdjustableQuantity where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentLinksResourceOptionalItemAdjustableQuantity" (\obj -> ((GHC.Base.pure PaymentLinksResourceOptionalItemAdjustableQuantity GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "enabled")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "maximum")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "minimum"))

-- | Create a new 'PaymentLinksResourceOptionalItemAdjustableQuantity' with all required fields.
mkPaymentLinksResourceOptionalItemAdjustableQuantity ::
  -- | 'paymentLinksResourceOptionalItemAdjustableQuantityEnabled'
  GHC.Types.Bool ->
  PaymentLinksResourceOptionalItemAdjustableQuantity
mkPaymentLinksResourceOptionalItemAdjustableQuantity paymentLinksResourceOptionalItemAdjustableQuantityEnabled =
  PaymentLinksResourceOptionalItemAdjustableQuantity
    { paymentLinksResourceOptionalItemAdjustableQuantityEnabled = paymentLinksResourceOptionalItemAdjustableQuantityEnabled,
      paymentLinksResourceOptionalItemAdjustableQuantityMaximum = GHC.Maybe.Nothing,
      paymentLinksResourceOptionalItemAdjustableQuantityMinimum = GHC.Maybe.Nothing
    }
