module StripeAPI.Types.PaymentIntentPaymentMethodOptionsSepaDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsSepaDebit
instance Show PaymentIntentPaymentMethodOptionsSepaDebit
instance Eq PaymentIntentPaymentMethodOptionsSepaDebit
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsSepaDebit
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsSepaDebit
data PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsSepaDebitSetupFutureUsage'
