module StripeAPI.Types.PaymentPagesCheckoutSessionConsent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionConsent
instance Show PaymentPagesCheckoutSessionConsent
instance Eq PaymentPagesCheckoutSessionConsent
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionConsent
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionConsent
data PaymentPagesCheckoutSessionConsentPromotions'NonNullable
instance Show PaymentPagesCheckoutSessionConsentPromotions'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentPromotions'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionConsentPromotions'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionConsentPromotions'NonNullable
data PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
instance Show PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionConsentTermsOfService'NonNullable
