module StripeAPI.Types.PaymentIntentNextActionVerifyWithMicrodeposits where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentNextActionVerifyWithMicrodeposits
instance Show PaymentIntentNextActionVerifyWithMicrodeposits
instance Eq PaymentIntentNextActionVerifyWithMicrodeposits
instance Data.Aeson.FromJSON PaymentIntentNextActionVerifyWithMicrodeposits
instance Data.Aeson.ToJSON PaymentIntentNextActionVerifyWithMicrodeposits
data PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Show PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Eq PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Data.Aeson.FromJSON PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Data.Aeson.ToJSON PaymentIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
