module StripeAPI.Types.PaymentPagesCheckoutSessionCustomerDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionCustomerDetails
instance Show PaymentPagesCheckoutSessionCustomerDetails
instance Eq PaymentPagesCheckoutSessionCustomerDetails
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCustomerDetails
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCustomerDetails
data PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
instance Show PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCustomerDetailsAddress'NonNullable
data PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
instance Show PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCustomerDetailsTaxExempt'NonNullable
