module StripeAPI.Types.PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
data PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
