module StripeAPI.Types.PaymentPagesCheckoutSessionTaxIdCollection where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionTaxIdCollection
instance Show PaymentPagesCheckoutSessionTaxIdCollection
instance Eq PaymentPagesCheckoutSessionTaxIdCollection
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionTaxIdCollection
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionTaxIdCollection
data PaymentPagesCheckoutSessionTaxIdCollectionRequired'
instance Show PaymentPagesCheckoutSessionTaxIdCollectionRequired'
instance Eq PaymentPagesCheckoutSessionTaxIdCollectionRequired'
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionTaxIdCollectionRequired'
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionTaxIdCollectionRequired'
