module StripeAPI.Types.PaymentMethodDetailsCardWalletMasterpass where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsCardWalletMasterpass
instance Show PaymentMethodDetailsCardWalletMasterpass
instance Eq PaymentMethodDetailsCardWalletMasterpass
instance Data.Aeson.FromJSON PaymentMethodDetailsCardWalletMasterpass
instance Data.Aeson.ToJSON PaymentMethodDetailsCardWalletMasterpass
data PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
instance Show PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
instance Eq PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardWalletMasterpassBillingAddress'NonNullable
data PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
instance Show PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
instance Eq PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardWalletMasterpassShippingAddress'NonNullable
