module StripeAPI.Types.PaymentFlowsAutomaticPaymentMethodsPaymentIntent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsAutomaticPaymentMethodsPaymentIntent
instance Show PaymentFlowsAutomaticPaymentMethodsPaymentIntent
instance Eq PaymentFlowsAutomaticPaymentMethodsPaymentIntent
instance Data.Aeson.FromJSON PaymentFlowsAutomaticPaymentMethodsPaymentIntent
instance Data.Aeson.ToJSON PaymentFlowsAutomaticPaymentMethodsPaymentIntent
data PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
instance Show PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
instance Eq PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
instance Data.Aeson.FromJSON PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
instance Data.Aeson.ToJSON PaymentFlowsAutomaticPaymentMethodsPaymentIntentAllowRedirects'
