module StripeAPI.Types.PaymentIntentTypeSpecificPaymentMethodOptionsClient where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentTypeSpecificPaymentMethodOptionsClient
instance Show PaymentIntentTypeSpecificPaymentMethodOptionsClient
instance Eq PaymentIntentTypeSpecificPaymentMethodOptionsClient
instance Data.Aeson.FromJSON PaymentIntentTypeSpecificPaymentMethodOptionsClient
instance Data.Aeson.ToJSON PaymentIntentTypeSpecificPaymentMethodOptionsClient
data PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
instance Show PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
instance Eq PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
instance Data.Aeson.FromJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
instance Data.Aeson.ToJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientCaptureMethod'
data PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
instance Show PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
instance Eq PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientSetupFutureUsage'
data PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Show PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Eq PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Data.Aeson.FromJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Data.Aeson.ToJSON PaymentIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
