module StripeAPI.Types.PaymentPagesCheckoutSessionAfterExpiration where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionAfterExpiration
instance Show PaymentPagesCheckoutSessionAfterExpiration
instance Eq PaymentPagesCheckoutSessionAfterExpiration
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionAfterExpiration
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionAfterExpiration
data PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
instance Show PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
instance Eq PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionAfterExpirationRecovery'NonNullable
