module StripeAPI.Types.PaymentIntentPaymentMethodOptionsAcssDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsAcssDebit
instance Show PaymentIntentPaymentMethodOptionsAcssDebit
instance Eq PaymentIntentPaymentMethodOptionsAcssDebit
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsAcssDebit
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsAcssDebit
data PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsAcssDebitSetupFutureUsage'
data PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Show PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Eq PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsAcssDebitVerificationMethod'
