module StripeAPI.Types.PaymentMethodOptionsCustomerBalanceBankTransfer where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsCustomerBalanceBankTransfer
instance Show PaymentMethodOptionsCustomerBalanceBankTransfer
instance Eq PaymentMethodOptionsCustomerBalanceBankTransfer
instance Data.Aeson.FromJSON PaymentMethodOptionsCustomerBalanceBankTransfer
instance Data.Aeson.ToJSON PaymentMethodOptionsCustomerBalanceBankTransfer
data PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
instance Show PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
instance Eq PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
instance Data.Aeson.FromJSON PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
instance Data.Aeson.ToJSON PaymentMethodOptionsCustomerBalanceBankTransferRequestedAddressTypes'
data PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
instance Show PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
instance Eq PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
instance Data.Aeson.FromJSON PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
instance Data.Aeson.ToJSON PaymentMethodOptionsCustomerBalanceBankTransferType'NonNullable
