module StripeAPI.Types.PaymentIntentNextActionKonbiniSeicomart where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentNextActionKonbiniSeicomart
instance Show PaymentIntentNextActionKonbiniSeicomart
instance Eq PaymentIntentNextActionKonbiniSeicomart
instance Data.Aeson.FromJSON PaymentIntentNextActionKonbiniSeicomart
instance Data.Aeson.ToJSON PaymentIntentNextActionKonbiniSeicomart
