module StripeAPI.Types.PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity
instance Show PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity
instance Eq PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity
