module StripeAPI.Types.PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
instance Show PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
instance Eq PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
instance Data.Aeson.FromJSON PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
instance Data.Aeson.ToJSON PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode
