module StripeAPI.Types.PaymentPagesCheckoutSessionDiscount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionDiscount
instance Show PaymentPagesCheckoutSessionDiscount
instance Eq PaymentPagesCheckoutSessionDiscount
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionDiscount
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionDiscount
data PaymentPagesCheckoutSessionDiscountCoupon'NonNullableVariants
instance Show PaymentPagesCheckoutSessionDiscountCoupon'NonNullableVariants
instance Eq PaymentPagesCheckoutSessionDiscountCoupon'NonNullableVariants
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionDiscountCoupon'NonNullableVariants
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionDiscountCoupon'NonNullableVariants
data PaymentPagesCheckoutSessionDiscountPromotionCode'NonNullableVariants
instance Show PaymentPagesCheckoutSessionDiscountPromotionCode'NonNullableVariants
instance Eq PaymentPagesCheckoutSessionDiscountPromotionCode'NonNullableVariants
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionDiscountPromotionCode'NonNullableVariants
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionDiscountPromotionCode'NonNullableVariants
