module StripeAPI.Types.PaymentMethodOptionsPromptpay where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsPromptpay
instance Show PaymentMethodOptionsPromptpay
instance Eq PaymentMethodOptionsPromptpay
instance Data.Aeson.FromJSON PaymentMethodOptionsPromptpay
instance Data.Aeson.ToJSON PaymentMethodOptionsPromptpay
data PaymentMethodOptionsPromptpaySetupFutureUsage'
instance Show PaymentMethodOptionsPromptpaySetupFutureUsage'
instance Eq PaymentMethodOptionsPromptpaySetupFutureUsage'
instance Data.Aeson.FromJSON PaymentMethodOptionsPromptpaySetupFutureUsage'
instance Data.Aeson.ToJSON PaymentMethodOptionsPromptpaySetupFutureUsage'
