module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
instance Show PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
instance Eq PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture
data PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
instance Show PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
instance Eq PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticaptureStatus'
