module StripeAPI.Types.PaymentIntentPaymentMethodOptionsAuBecsDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsAuBecsDebit
instance Show PaymentIntentPaymentMethodOptionsAuBecsDebit
instance Eq PaymentIntentPaymentMethodOptionsAuBecsDebit
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsAuBecsDebit
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsAuBecsDebit
data PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsAuBecsDebitSetupFutureUsage'
