module StripeAPI.Types.PaymentMethodOptionsUsBankAccountMandateOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsUsBankAccountMandateOptions
instance Show PaymentMethodOptionsUsBankAccountMandateOptions
instance Eq PaymentMethodOptionsUsBankAccountMandateOptions
instance Data.Aeson.FromJSON PaymentMethodOptionsUsBankAccountMandateOptions
instance Data.Aeson.ToJSON PaymentMethodOptionsUsBankAccountMandateOptions
data PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
instance Show PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
instance Eq PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
instance Data.Aeson.FromJSON PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
instance Data.Aeson.ToJSON PaymentMethodOptionsUsBankAccountMandateOptionsCollectionMethod'
