module StripeAPI.Types.PaymentPagesCheckoutSessionShippingCost where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionShippingCost
instance Show PaymentPagesCheckoutSessionShippingCost
instance Eq PaymentPagesCheckoutSessionShippingCost
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionShippingCost
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionShippingCost
data PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
instance Show PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
instance Eq PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionShippingCostShippingRate'NonNullableVariants
