module StripeAPI.Types.PaymentMethodDetailsKlarna where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsKlarna
instance Show PaymentMethodDetailsKlarna
instance Eq PaymentMethodDetailsKlarna
instance Data.Aeson.FromJSON PaymentMethodDetailsKlarna
instance Data.Aeson.ToJSON PaymentMethodDetailsKlarna
data PaymentMethodDetailsKlarnaPayerDetails'NonNullable
instance Show PaymentMethodDetailsKlarnaPayerDetails'NonNullable
instance Eq PaymentMethodDetailsKlarnaPayerDetails'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsKlarnaPayerDetails'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsKlarnaPayerDetails'NonNullable
data PaymentMethodDetailsKlarnaPayerDetails'NonNullableAddress'NonNullable
instance Show PaymentMethodDetailsKlarnaPayerDetails'NonNullableAddress'NonNullable
instance Eq PaymentMethodDetailsKlarnaPayerDetails'NonNullableAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsKlarnaPayerDetails'NonNullableAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsKlarnaPayerDetails'NonNullableAddress'NonNullable
