module StripeAPI.Types.PaymentIntentNextActionWechatPayRedirectToAndroidApp where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentNextActionWechatPayRedirectToAndroidApp
instance Show PaymentIntentNextActionWechatPayRedirectToAndroidApp
instance Eq PaymentIntentNextActionWechatPayRedirectToAndroidApp
instance Data.Aeson.FromJSON PaymentIntentNextActionWechatPayRedirectToAndroidApp
instance Data.Aeson.ToJSON PaymentIntentNextActionWechatPayRedirectToAndroidApp
