module StripeAPI.Types.PaymentMethodCardWalletVisaCheckout where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodCardWalletVisaCheckout
instance Show PaymentMethodCardWalletVisaCheckout
instance Eq PaymentMethodCardWalletVisaCheckout
instance Data.Aeson.FromJSON PaymentMethodCardWalletVisaCheckout
instance Data.Aeson.ToJSON PaymentMethodCardWalletVisaCheckout
data PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
instance Show PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
instance Eq PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodCardWalletVisaCheckoutBillingAddress'NonNullable
data PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
instance Show PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
instance Eq PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodCardWalletVisaCheckoutShippingAddress'NonNullable
