module StripeAPI.Types.PaymentPagesCheckoutSessionConsentCollection where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionConsentCollection
instance Show PaymentPagesCheckoutSessionConsentCollection
instance Eq PaymentPagesCheckoutSessionConsentCollection
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionConsentCollection
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionConsentCollection
data PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Show PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullable
data PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Show PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Eq PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionConsentCollectionPaymentMethodReuseAgreement'NonNullablePosition'
data PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance Show PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionConsentCollectionPromotions'NonNullable
data PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
instance Show PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
instance Eq PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionConsentCollectionTermsOfService'NonNullable
