module StripeAPI.Types.PaymentPagesCheckoutSessionShippingOption where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionShippingOption
instance Show PaymentPagesCheckoutSessionShippingOption
instance Eq PaymentPagesCheckoutSessionShippingOption
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionShippingOption
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionShippingOption
data PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
instance Show PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
instance Eq PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionShippingOptionShippingRate'Variants
