{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.payment_flows_private_payment_methods_card_present_common_wallet@ in the specification.
data PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet = PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
  { -- | type: The type of mobile wallet, one of \`apple_pay\`, \`google_pay\`, \`samsung_pay\`, or \`unknown\`.
    paymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType :: PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["type" Data.Aeson.Types.ToJSON..= paymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType obj] : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["type" Data.Aeson.Types.ToJSON..= paymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType obj] : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet" (\obj -> GHC.Base.pure PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))

-- | Create a new 'PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet' with all required fields.
mkPaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet ::
  -- | 'paymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'
  PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType' ->
  PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
mkPaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet paymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType = PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet {paymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType = paymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType}

-- | Defines the enum schema located at @components.schemas.payment_flows_private_payment_methods_card_present_common_wallet.properties.type@ in the specification.
--
-- The type of mobile wallet, one of \`apple_pay\`, \`google_pay\`, \`samsung_pay\`, or \`unknown\`.
data PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"apple_pay"@
    PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumApplePay
  | -- | Represents the JSON value @"google_pay"@
    PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumGooglePay
  | -- | Represents the JSON value @"samsung_pay"@
    PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumSamsungPay
  | -- | Represents the JSON value @"unknown"@
    PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumUnknown
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType' where
  toJSON (PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'Other val) = val
  toJSON (PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumApplePay) = "apple_pay"
  toJSON (PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumGooglePay) = "google_pay"
  toJSON (PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumSamsungPay) = "samsung_pay"
  toJSON (PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumUnknown) = "unknown"

instance Data.Aeson.Types.FromJSON.FromJSON PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "apple_pay" -> PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumApplePay
          | val GHC.Classes.== "google_pay" -> PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumGooglePay
          | val GHC.Classes.== "samsung_pay" -> PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumSamsungPay
          | val GHC.Classes.== "unknown" -> PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'EnumUnknown
          | GHC.Base.otherwise -> PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'Other val
      )
