module StripeAPI.Types.PaymentMethodOptionsAfterpayClearpay where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsAfterpayClearpay
instance Show PaymentMethodOptionsAfterpayClearpay
instance Eq PaymentMethodOptionsAfterpayClearpay
instance Data.Aeson.FromJSON PaymentMethodOptionsAfterpayClearpay
instance Data.Aeson.ToJSON PaymentMethodOptionsAfterpayClearpay
data PaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance Show PaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance Eq PaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance Data.Aeson.FromJSON PaymentMethodOptionsAfterpayClearpayCaptureMethod'
instance Data.Aeson.ToJSON PaymentMethodOptionsAfterpayClearpayCaptureMethod'
data PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance Show PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance Eq PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance Data.Aeson.FromJSON PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
instance Data.Aeson.ToJSON PaymentMethodOptionsAfterpayClearpaySetupFutureUsage'
