module StripeAPI.Types.PaymentIntentPaymentMethodOptionsMobilepay where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsMobilepay
instance Show PaymentIntentPaymentMethodOptionsMobilepay
instance Eq PaymentIntentPaymentMethodOptionsMobilepay
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsMobilepay
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsMobilepay
data PaymentIntentPaymentMethodOptionsMobilepayCaptureMethod'
instance Show PaymentIntentPaymentMethodOptionsMobilepayCaptureMethod'
instance Eq PaymentIntentPaymentMethodOptionsMobilepayCaptureMethod'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsMobilepayCaptureMethod'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsMobilepayCaptureMethod'
data PaymentIntentPaymentMethodOptionsMobilepaySetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsMobilepaySetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsMobilepaySetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsMobilepaySetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsMobilepaySetupFutureUsage'
