module StripeAPI.Types.PaymentIntentNextActionDisplayBankTransferInstructions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentNextActionDisplayBankTransferInstructions
instance Show PaymentIntentNextActionDisplayBankTransferInstructions
instance Eq PaymentIntentNextActionDisplayBankTransferInstructions
instance Data.Aeson.FromJSON PaymentIntentNextActionDisplayBankTransferInstructions
instance Data.Aeson.ToJSON PaymentIntentNextActionDisplayBankTransferInstructions
data PaymentIntentNextActionDisplayBankTransferInstructionsType'
instance Show PaymentIntentNextActionDisplayBankTransferInstructionsType'
instance Eq PaymentIntentNextActionDisplayBankTransferInstructionsType'
instance Data.Aeson.FromJSON PaymentIntentNextActionDisplayBankTransferInstructionsType'
instance Data.Aeson.ToJSON PaymentIntentNextActionDisplayBankTransferInstructionsType'
