{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.payment_flows_private_payment_methods_naver_pay_payment_method_options@ in the specification.
data PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions = PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
  { -- | capture_method: Controls when the funds will be captured from the customer\'s account.
    paymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod :: (GHC.Maybe.Maybe PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'),
    -- | setup_future_usage: Indicates that you intend to make future payments with this PaymentIntent\'s payment method.
    --
    -- If you provide a Customer with the PaymentIntent, you can use this parameter to [attach the payment method](\/payments\/save-during-payment) to the Customer after the PaymentIntent is confirmed and the customer completes any required actions. If you don\'t provide a Customer, you can still [attach](\/api\/payment_methods\/attach) the payment method to a Customer after the transaction completes.
    --
    -- If the payment method is \`card_present\` and isn\'t a digital wallet, Stripe creates and attaches a [generated_card](\/api\/charges\/object\#charge_object-payment_method_details-card_present-generated_card) payment method representing the card to the Customer instead.
    --
    -- When processing card payments, Stripe uses \`setup_future_usage\` to help you comply with regional legislation and network rules, such as [SCA](\/strong-customer-authentication).
    paymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage :: (GHC.Maybe.Maybe PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage')
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("capture_method" Data.Aeson.Types.ToJSON..=)) (paymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("setup_future_usage" Data.Aeson.Types.ToJSON..=)) (paymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("capture_method" Data.Aeson.Types.ToJSON..=)) (paymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("setup_future_usage" Data.Aeson.Types.ToJSON..=)) (paymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions" (\obj -> (GHC.Base.pure PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "capture_method")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "setup_future_usage"))

-- | Create a new 'PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions' with all required fields.
mkPaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions :: PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
mkPaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions =
  PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
    { paymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod = GHC.Maybe.Nothing,
      paymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage = GHC.Maybe.Nothing
    }

-- | Defines the enum schema located at @components.schemas.payment_flows_private_payment_methods_naver_pay_payment_method_options.properties.capture_method@ in the specification.
--
-- Controls when the funds will be captured from the customer\'s account.
data PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"manual"@
    PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'EnumManual
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod' where
  toJSON (PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'Other val) = val
  toJSON (PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'EnumManual) = "manual"

instance Data.Aeson.Types.FromJSON.FromJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "manual" -> PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'EnumManual
          | GHC.Base.otherwise -> PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'Other val
      )

-- | Defines the enum schema located at @components.schemas.payment_flows_private_payment_methods_naver_pay_payment_method_options.properties.setup_future_usage@ in the specification.
--
-- Indicates that you intend to make future payments with this PaymentIntent\'s payment method.
--
-- If you provide a Customer with the PaymentIntent, you can use this parameter to [attach the payment method](\/payments\/save-during-payment) to the Customer after the PaymentIntent is confirmed and the customer completes any required actions. If you don\'t provide a Customer, you can still [attach](\/api\/payment_methods\/attach) the payment method to a Customer after the transaction completes.
--
-- If the payment method is \`card_present\` and isn\'t a digital wallet, Stripe creates and attaches a [generated_card](\/api\/charges\/object\#charge_object-payment_method_details-card_present-generated_card) payment method representing the card to the Customer instead.
--
-- When processing card payments, Stripe uses \`setup_future_usage\` to help you comply with regional legislation and network rules, such as [SCA](\/strong-customer-authentication).
data PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'Other Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'Typed Data.Text.Internal.Text
  | -- | Represents the JSON value @"none"@
    PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'EnumNone
  | -- | Represents the JSON value @"off_session"@
    PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'EnumOffSession
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage' where
  toJSON (PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'Other val) = val
  toJSON (PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'Typed val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'EnumNone) = "none"
  toJSON (PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'EnumOffSession) = "off_session"

instance Data.Aeson.Types.FromJSON.FromJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage' where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "none" -> PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'EnumNone
          | val GHC.Classes.== "off_session" -> PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'EnumOffSession
          | GHC.Base.otherwise -> PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'Other val
      )
