module StripeAPI.Types.PaymentLinksResourceAutomaticTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceAutomaticTax
instance Show PaymentLinksResourceAutomaticTax
instance Eq PaymentLinksResourceAutomaticTax
instance Data.Aeson.FromJSON PaymentLinksResourceAutomaticTax
instance Data.Aeson.ToJSON PaymentLinksResourceAutomaticTax
data PaymentLinksResourceAutomaticTaxLiability'NonNullable
instance Show PaymentLinksResourceAutomaticTaxLiability'NonNullable
instance Eq PaymentLinksResourceAutomaticTaxLiability'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceAutomaticTaxLiability'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceAutomaticTaxLiability'NonNullable
data PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Show PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.FromJSON PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.ToJSON PaymentLinksResourceAutomaticTaxLiability'NonNullableAccount'Variants
data PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
instance Show PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
instance Eq PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.FromJSON PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.ToJSON PaymentLinksResourceAutomaticTaxLiability'NonNullableType'
