{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PaymentPagesCheckoutSessionCollectedInformation
module StripeAPI.Types.PaymentPagesCheckoutSessionCollectedInformation where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import {-# SOURCE #-} StripeAPI.Types.Address
import {-# SOURCE #-} StripeAPI.Types.PaymentPagesCheckoutSessionCheckoutAddressDetails
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.payment_pages_checkout_session_collected_information@ in the specification.
data PaymentPagesCheckoutSessionCollectedInformation = PaymentPagesCheckoutSessionCollectedInformation
  { -- | shipping_details: Shipping information for this Checkout Session.
    paymentPagesCheckoutSessionCollectedInformationShippingDetails :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionCollectedInformation where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("shipping_details" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionCollectedInformationShippingDetails obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("shipping_details" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionCollectedInformationShippingDetails obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionCollectedInformation where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentPagesCheckoutSessionCollectedInformation" (\obj -> GHC.Base.pure PaymentPagesCheckoutSessionCollectedInformation GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "shipping_details"))

-- | Create a new 'PaymentPagesCheckoutSessionCollectedInformation' with all required fields.
mkPaymentPagesCheckoutSessionCollectedInformation :: PaymentPagesCheckoutSessionCollectedInformation
mkPaymentPagesCheckoutSessionCollectedInformation = PaymentPagesCheckoutSessionCollectedInformation {paymentPagesCheckoutSessionCollectedInformationShippingDetails = GHC.Maybe.Nothing}

-- | Defines the object schema located at @components.schemas.payment_pages_checkout_session_collected_information.properties.shipping_details.anyOf@ in the specification.
--
-- Shipping information for this Checkout Session.
data PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable = PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable
  { -- | address:
    paymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullableAddress :: (GHC.Maybe.Maybe Address),
    -- | name: Customer name.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    paymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullableName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("address" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullableAddress obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullableName obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("address" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullableAddress obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullableName obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable" (\obj -> (GHC.Base.pure PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "address")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name"))

-- | Create a new 'PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable' with all required fields.
mkPaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable :: PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable
mkPaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable =
  PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable
    { paymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullableAddress = GHC.Maybe.Nothing,
      paymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullableName = GHC.Maybe.Nothing
    }
