module StripeAPI.Types.PaymentMethodDetailsAfterpayClearpay where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsAfterpayClearpay
instance Show PaymentMethodDetailsAfterpayClearpay
instance Eq PaymentMethodDetailsAfterpayClearpay
instance Data.Aeson.FromJSON PaymentMethodDetailsAfterpayClearpay
instance Data.Aeson.ToJSON PaymentMethodDetailsAfterpayClearpay
