module StripeAPI.Types.PaymentMethodOptionsCustomerBalance where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsCustomerBalance
instance Show PaymentMethodOptionsCustomerBalance
instance Eq PaymentMethodOptionsCustomerBalance
instance Data.Aeson.FromJSON PaymentMethodOptionsCustomerBalance
instance Data.Aeson.ToJSON PaymentMethodOptionsCustomerBalance
data PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Show PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Eq PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Data.Aeson.FromJSON PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
instance Data.Aeson.ToJSON PaymentMethodOptionsCustomerBalanceFundingType'NonNullable
data PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
instance Show PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
instance Eq PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentMethodOptionsCustomerBalanceSetupFutureUsage'
