module StripeAPI.Types.PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictions
instance Show PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictions
instance Eq PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictions
instance Data.Aeson.FromJSON PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictions
instance Data.Aeson.ToJSON PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictions
data PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictionsBrandsBlocked'
instance Show PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictionsBrandsBlocked'
instance Eq PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictionsBrandsBlocked'
instance Data.Aeson.FromJSON PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictionsBrandsBlocked'
instance Data.Aeson.ToJSON PaymentPagesPrivateCardPaymentMethodOptionsResourceRestrictionsBrandsBlocked'
