module StripeAPI.Types.PaymentMethodDetailsCardNetworkToken where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsCardNetworkToken
instance Show PaymentMethodDetailsCardNetworkToken
instance Eq PaymentMethodDetailsCardNetworkToken
instance Data.Aeson.FromJSON PaymentMethodDetailsCardNetworkToken
instance Data.Aeson.ToJSON PaymentMethodDetailsCardNetworkToken
