module StripeAPI.Types.PaymentLinksResourceCustomText where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceCustomText
instance Show PaymentLinksResourceCustomText
instance Eq PaymentLinksResourceCustomText
instance Data.Aeson.FromJSON PaymentLinksResourceCustomText
instance Data.Aeson.ToJSON PaymentLinksResourceCustomText
data PaymentLinksResourceCustomTextAfterSubmit'NonNullable
instance Show PaymentLinksResourceCustomTextAfterSubmit'NonNullable
instance Eq PaymentLinksResourceCustomTextAfterSubmit'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceCustomTextAfterSubmit'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceCustomTextAfterSubmit'NonNullable
data PaymentLinksResourceCustomTextShippingAddress'NonNullable
instance Show PaymentLinksResourceCustomTextShippingAddress'NonNullable
instance Eq PaymentLinksResourceCustomTextShippingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceCustomTextShippingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceCustomTextShippingAddress'NonNullable
data PaymentLinksResourceCustomTextSubmit'NonNullable
instance Show PaymentLinksResourceCustomTextSubmit'NonNullable
instance Eq PaymentLinksResourceCustomTextSubmit'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceCustomTextSubmit'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceCustomTextSubmit'NonNullable
data PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
instance Show PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
instance Eq PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceCustomTextTermsOfServiceAcceptance'NonNullable
