module StripeAPI.Types.PaymentMethodDetailsAcssDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsAcssDebit
instance Show PaymentMethodDetailsAcssDebit
instance Eq PaymentMethodDetailsAcssDebit
instance Data.Aeson.FromJSON PaymentMethodDetailsAcssDebit
instance Data.Aeson.ToJSON PaymentMethodDetailsAcssDebit
