module StripeAPI.Types.PaymentIntentPaymentMethodOptionsMandateOptionsSepaDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsMandateOptionsSepaDebit
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsSepaDebit
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsSepaDebit
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsSepaDebit
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsSepaDebit
