module StripeAPI.Types.PaymentIntentPaymentMethodOptionsMandateOptionsBacsDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsMandateOptionsBacsDebit
instance Show PaymentIntentPaymentMethodOptionsMandateOptionsBacsDebit
instance Eq PaymentIntentPaymentMethodOptionsMandateOptionsBacsDebit
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsMandateOptionsBacsDebit
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsMandateOptionsBacsDebit
