module StripeAPI.Types.PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
instance Show PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
instance Eq PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionTotalDetailsResourceBreakdown
