module StripeAPI.Types.PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode
instance Show PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode
instance Eq PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode
instance Data.Aeson.FromJSON PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode
instance Data.Aeson.ToJSON PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode
