{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema PaymentPagesCheckoutSessionSavedPaymentMethodOptions
module StripeAPI.Types.PaymentPagesCheckoutSessionSavedPaymentMethodOptions where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.payment_pages_checkout_session_saved_payment_method_options@ in the specification.
data PaymentPagesCheckoutSessionSavedPaymentMethodOptions = PaymentPagesCheckoutSessionSavedPaymentMethodOptions
  { -- | allow_redisplay_filters: Uses the \`allow_redisplay\` value of each saved payment method to filter the set presented to a returning customer. By default, only saved payment methods with ’allow_redisplay: ‘always’ are shown in Checkout.
    paymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable [PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable])),
    -- | payment_method_remove: Enable customers to choose if they wish to remove their saved payment methods. Disabled by default.
    paymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable)),
    -- | payment_method_save: Enable customers to choose if they wish to save their payment method for future use. Disabled by default.
    paymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave :: (GHC.Maybe.Maybe (StripeAPI.Common.Nullable PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable))
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptions where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("allow_redisplay_filters" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_remove" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_save" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("allow_redisplay_filters" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_remove" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_save" Data.Aeson.Types.ToJSON..=)) (paymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptions where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "PaymentPagesCheckoutSessionSavedPaymentMethodOptions" (\obj -> ((GHC.Base.pure PaymentPagesCheckoutSessionSavedPaymentMethodOptions GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "allow_redisplay_filters")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_remove")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_save"))

-- | Create a new 'PaymentPagesCheckoutSessionSavedPaymentMethodOptions' with all required fields.
mkPaymentPagesCheckoutSessionSavedPaymentMethodOptions :: PaymentPagesCheckoutSessionSavedPaymentMethodOptions
mkPaymentPagesCheckoutSessionSavedPaymentMethodOptions =
  PaymentPagesCheckoutSessionSavedPaymentMethodOptions
    { paymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters = GHC.Maybe.Nothing,
      paymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove = GHC.Maybe.Nothing,
      paymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave = GHC.Maybe.Nothing
    }

-- | Defines the enum schema located at @components.schemas.payment_pages_checkout_session_saved_payment_method_options.properties.allow_redisplay_filters.items@ in the specification.
data PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableOther Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableTyped Data.Text.Internal.Text
  | -- | Represents the JSON value @"always"@
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumAlways
  | -- | Represents the JSON value @"limited"@
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumLimited
  | -- | Represents the JSON value @"unspecified"@
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumUnspecified
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable where
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableOther val) = val
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumAlways) = "always"
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumLimited) = "limited"
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumUnspecified) = "unspecified"

instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "always" -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumAlways
          | val GHC.Classes.== "limited" -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumLimited
          | val GHC.Classes.== "unspecified" -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableEnumUnspecified
          | GHC.Base.otherwise -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullableOther val
      )

-- | Defines the enum schema located at @components.schemas.payment_pages_checkout_session_saved_payment_method_options.properties.payment_method_remove@ in the specification.
--
-- Enable customers to choose if they wish to remove their saved payment methods. Disabled by default.
data PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableOther Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableTyped Data.Text.Internal.Text
  | -- | Represents the JSON value @"disabled"@
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableEnumDisabled
  | -- | Represents the JSON value @"enabled"@
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableEnumEnabled
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable where
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableOther val) = val
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableEnumDisabled) = "disabled"
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableEnumEnabled) = "enabled"

instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "disabled" -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableEnumDisabled
          | val GHC.Classes.== "enabled" -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableEnumEnabled
          | GHC.Base.otherwise -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullableOther val
      )

-- | Defines the enum schema located at @components.schemas.payment_pages_checkout_session_saved_payment_method_options.properties.payment_method_save@ in the specification.
--
-- Enable customers to choose if they wish to save their payment method for future use. Disabled by default.
data PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable
  = -- | This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableOther Data.Aeson.Types.Internal.Value
  | -- | This constructor can be used to send values to the server which are not present in the specification yet.
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableTyped Data.Text.Internal.Text
  | -- | Represents the JSON value @"disabled"@
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableEnumDisabled
  | -- | Represents the JSON value @"enabled"@
    PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableEnumEnabled
  deriving (GHC.Show.Show, GHC.Classes.Eq)

instance Data.Aeson.Types.ToJSON.ToJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable where
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableOther val) = val
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableEnumDisabled) = "disabled"
  toJSON (PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableEnumEnabled) = "enabled"

instance Data.Aeson.Types.FromJSON.FromJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable where
  parseJSON val =
    GHC.Base.pure
      ( if
          | val GHC.Classes.== "disabled" -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableEnumDisabled
          | val GHC.Classes.== "enabled" -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableEnumEnabled
          | GHC.Base.otherwise -> PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullableOther val
      )
