module StripeAPI.Types.PaymentMethodOptionsCardMandateOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsCardMandateOptions
instance Show PaymentMethodOptionsCardMandateOptions
instance Eq PaymentMethodOptionsCardMandateOptions
instance Data.Aeson.FromJSON PaymentMethodOptionsCardMandateOptions
instance Data.Aeson.ToJSON PaymentMethodOptionsCardMandateOptions
data PaymentMethodOptionsCardMandateOptionsAmountType'
instance Show PaymentMethodOptionsCardMandateOptionsAmountType'
instance Eq PaymentMethodOptionsCardMandateOptionsAmountType'
instance Data.Aeson.FromJSON PaymentMethodOptionsCardMandateOptionsAmountType'
instance Data.Aeson.ToJSON PaymentMethodOptionsCardMandateOptionsAmountType'
data PaymentMethodOptionsCardMandateOptionsInterval'
instance Show PaymentMethodOptionsCardMandateOptionsInterval'
instance Eq PaymentMethodOptionsCardMandateOptionsInterval'
instance Data.Aeson.FromJSON PaymentMethodOptionsCardMandateOptionsInterval'
instance Data.Aeson.ToJSON PaymentMethodOptionsCardMandateOptionsInterval'
data PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Show PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Eq PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Data.Aeson.FromJSON PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Data.Aeson.ToJSON PaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
