module StripeAPI.Types.PaymentMethodDetailsCardInstallmentsPlan where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsCardInstallmentsPlan
instance Show PaymentMethodDetailsCardInstallmentsPlan
instance Eq PaymentMethodDetailsCardInstallmentsPlan
instance Data.Aeson.FromJSON PaymentMethodDetailsCardInstallmentsPlan
instance Data.Aeson.ToJSON PaymentMethodDetailsCardInstallmentsPlan
data PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
instance Show PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
instance Eq PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardInstallmentsPlanInterval'NonNullable
data PaymentMethodDetailsCardInstallmentsPlanType'
instance Show PaymentMethodDetailsCardInstallmentsPlanType'
instance Eq PaymentMethodDetailsCardInstallmentsPlanType'
instance Data.Aeson.FromJSON PaymentMethodDetailsCardInstallmentsPlanType'
instance Data.Aeson.ToJSON PaymentMethodDetailsCardInstallmentsPlanType'
