module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
instance Show PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
instance Eq PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet
data PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'
instance Show PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'
instance Eq PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsCardPresentCommonWalletType'
