module StripeAPI.Types.PaymentMethodDetailsCardWalletVisaCheckout where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsCardWalletVisaCheckout
instance Show PaymentMethodDetailsCardWalletVisaCheckout
instance Eq PaymentMethodDetailsCardWalletVisaCheckout
instance Data.Aeson.FromJSON PaymentMethodDetailsCardWalletVisaCheckout
instance Data.Aeson.ToJSON PaymentMethodDetailsCardWalletVisaCheckout
data PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
instance Show PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
instance Eq PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardWalletVisaCheckoutBillingAddress'NonNullable
data PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
instance Show PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
instance Eq PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardWalletVisaCheckoutShippingAddress'NonNullable
