module StripeAPI.Types.PaymentMethodOptionsAffirm where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsAffirm
instance Show PaymentMethodOptionsAffirm
instance Eq PaymentMethodOptionsAffirm
instance Data.Aeson.FromJSON PaymentMethodOptionsAffirm
instance Data.Aeson.ToJSON PaymentMethodOptionsAffirm
data PaymentMethodOptionsAffirmCaptureMethod'
instance Show PaymentMethodOptionsAffirmCaptureMethod'
instance Eq PaymentMethodOptionsAffirmCaptureMethod'
instance Data.Aeson.FromJSON PaymentMethodOptionsAffirmCaptureMethod'
instance Data.Aeson.ToJSON PaymentMethodOptionsAffirmCaptureMethod'
data PaymentMethodOptionsAffirmSetupFutureUsage'
instance Show PaymentMethodOptionsAffirmSetupFutureUsage'
instance Eq PaymentMethodOptionsAffirmSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentMethodOptionsAffirmSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentMethodOptionsAffirmSetupFutureUsage'
