module StripeAPI.Types.PaymentPagesCheckoutSessionSavedPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionSavedPaymentMethodOptions
instance Show PaymentPagesCheckoutSessionSavedPaymentMethodOptions
instance Eq PaymentPagesCheckoutSessionSavedPaymentMethodOptions
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptions
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptions
data PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable
instance Show PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable
instance Eq PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsAllowRedisplayFilters'NonNullable
data PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable
instance Show PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable
instance Eq PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodRemove'NonNullable
data PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable
instance Show PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable
instance Eq PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionSavedPaymentMethodOptionsPaymentMethodSave'NonNullable
