module StripeAPI.Types.PaymentIntentPaymentMethodOptionsLink where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsLink
instance Show PaymentIntentPaymentMethodOptionsLink
instance Eq PaymentIntentPaymentMethodOptionsLink
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsLink
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsLink
data PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
instance Show PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
instance Eq PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsLinkCaptureMethod'
data PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsLinkSetupFutureUsage'
