module StripeAPI.Types.PaymentIntentPaymentMethodOptionsSwish where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsSwish
instance Show PaymentIntentPaymentMethodOptionsSwish
instance Eq PaymentIntentPaymentMethodOptionsSwish
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsSwish
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsSwish
data PaymentIntentPaymentMethodOptionsSwishSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsSwishSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsSwishSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsSwishSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsSwishSetupFutureUsage'
