module StripeAPI.Types.PaymentMethodDetailsCardInstallments where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsCardInstallments
instance Show PaymentMethodDetailsCardInstallments
instance Eq PaymentMethodDetailsCardInstallments
instance Data.Aeson.FromJSON PaymentMethodDetailsCardInstallments
instance Data.Aeson.ToJSON PaymentMethodDetailsCardInstallments
data PaymentMethodDetailsCardInstallmentsPlan'NonNullable
instance Show PaymentMethodDetailsCardInstallmentsPlan'NonNullable
instance Eq PaymentMethodDetailsCardInstallmentsPlan'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullable
data PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Show PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Eq PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullableInterval'NonNullable
data PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
instance Show PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
instance Eq PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
instance Data.Aeson.FromJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
instance Data.Aeson.ToJSON PaymentMethodDetailsCardInstallmentsPlan'NonNullableType'
