module StripeAPI.Types.PaymentMethodOptionsCustomerBalanceEuBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsCustomerBalanceEuBankAccount
instance Show PaymentMethodOptionsCustomerBalanceEuBankAccount
instance Eq PaymentMethodOptionsCustomerBalanceEuBankAccount
instance Data.Aeson.FromJSON PaymentMethodOptionsCustomerBalanceEuBankAccount
instance Data.Aeson.ToJSON PaymentMethodOptionsCustomerBalanceEuBankAccount
data PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
instance Show PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
instance Eq PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
instance Data.Aeson.FromJSON PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
instance Data.Aeson.ToJSON PaymentMethodOptionsCustomerBalanceEuBankAccountCountry'
