module StripeAPI.Types.PaymentLinksResourceSubscriptionDataInvoiceSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceSubscriptionDataInvoiceSettings
instance Show PaymentLinksResourceSubscriptionDataInvoiceSettings
instance Eq PaymentLinksResourceSubscriptionDataInvoiceSettings
instance Data.Aeson.FromJSON PaymentLinksResourceSubscriptionDataInvoiceSettings
instance Data.Aeson.ToJSON PaymentLinksResourceSubscriptionDataInvoiceSettings
