module StripeAPI.Types.PaymentMethodUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodUsBankAccount
instance Show PaymentMethodUsBankAccount
instance Eq PaymentMethodUsBankAccount
instance Data.Aeson.FromJSON PaymentMethodUsBankAccount
instance Data.Aeson.ToJSON PaymentMethodUsBankAccount
data PaymentMethodUsBankAccountAccountHolderType'NonNullable
instance Show PaymentMethodUsBankAccountAccountHolderType'NonNullable
instance Eq PaymentMethodUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.FromJSON PaymentMethodUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.ToJSON PaymentMethodUsBankAccountAccountHolderType'NonNullable
data PaymentMethodUsBankAccountAccountType'NonNullable
instance Show PaymentMethodUsBankAccountAccountType'NonNullable
instance Eq PaymentMethodUsBankAccountAccountType'NonNullable
instance Data.Aeson.FromJSON PaymentMethodUsBankAccountAccountType'NonNullable
instance Data.Aeson.ToJSON PaymentMethodUsBankAccountAccountType'NonNullable
data PaymentMethodUsBankAccountNetworks'NonNullable
instance Show PaymentMethodUsBankAccountNetworks'NonNullable
instance Eq PaymentMethodUsBankAccountNetworks'NonNullable
instance Data.Aeson.FromJSON PaymentMethodUsBankAccountNetworks'NonNullable
instance Data.Aeson.ToJSON PaymentMethodUsBankAccountNetworks'NonNullable
data PaymentMethodUsBankAccountNetworks'NonNullableSupported'
instance Show PaymentMethodUsBankAccountNetworks'NonNullableSupported'
instance Eq PaymentMethodUsBankAccountNetworks'NonNullableSupported'
instance Data.Aeson.FromJSON PaymentMethodUsBankAccountNetworks'NonNullableSupported'
instance Data.Aeson.ToJSON PaymentMethodUsBankAccountNetworks'NonNullableSupported'
data PaymentMethodUsBankAccountStatusDetails'NonNullable
instance Show PaymentMethodUsBankAccountStatusDetails'NonNullable
instance Eq PaymentMethodUsBankAccountStatusDetails'NonNullable
instance Data.Aeson.FromJSON PaymentMethodUsBankAccountStatusDetails'NonNullable
instance Data.Aeson.ToJSON PaymentMethodUsBankAccountStatusDetails'NonNullable
