module StripeAPI.Types.PaymentIntentPaymentMethodOptionsUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsUsBankAccount
instance Show PaymentIntentPaymentMethodOptionsUsBankAccount
instance Eq PaymentIntentPaymentMethodOptionsUsBankAccount
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsUsBankAccount
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsUsBankAccount
data PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
instance Show PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
instance Eq PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsUsBankAccountPreferredSettlementSpeed'
data PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsUsBankAccountSetupFutureUsage'
data PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Show PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Eq PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
