module StripeAPI.Types.PaymentPagesCheckoutSessionOptionalItem where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionOptionalItem
instance Show PaymentPagesCheckoutSessionOptionalItem
instance Eq PaymentPagesCheckoutSessionOptionalItem
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionOptionalItem
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionOptionalItem
data PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity'NonNullable
instance Show PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity'NonNullable
instance Eq PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionOptionalItemAdjustableQuantity'NonNullable
