module StripeAPI.Types.PaymentPagesCheckoutSessionCustomText where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionCustomText
instance Show PaymentPagesCheckoutSessionCustomText
instance Eq PaymentPagesCheckoutSessionCustomText
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCustomText
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCustomText
data PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
instance Show PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCustomTextAfterSubmit'NonNullable
data PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
instance Show PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCustomTextShippingAddress'NonNullable
data PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
instance Show PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCustomTextSubmit'NonNullable
data PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
instance Show PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
instance Eq PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCustomTextTermsOfServiceAcceptance'NonNullable
