module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptions
instance Show PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptions
instance Eq PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptions
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptions
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptions
data PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsCaptureMethod'
instance Show PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsCaptureMethod'
instance Eq PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsCaptureMethod'
data PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsSetupFutureUsage'
instance Show PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsSetupFutureUsage'
instance Eq PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsKakaoPayPaymentMethodOptionsSetupFutureUsage'
