module StripeAPI.Types.PaymentIntentPaymentMethodOptionsBacsDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentPaymentMethodOptionsBacsDebit
instance Show PaymentIntentPaymentMethodOptionsBacsDebit
instance Eq PaymentIntentPaymentMethodOptionsBacsDebit
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsBacsDebit
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsBacsDebit
data PaymentIntentPaymentMethodOptionsBacsDebitSetupFutureUsage'
instance Show PaymentIntentPaymentMethodOptionsBacsDebitSetupFutureUsage'
instance Eq PaymentIntentPaymentMethodOptionsBacsDebitSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentIntentPaymentMethodOptionsBacsDebitSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentIntentPaymentMethodOptionsBacsDebitSetupFutureUsage'
