module StripeAPI.Types.PaymentLinksResourcePaymentMethodReuseAgreement where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourcePaymentMethodReuseAgreement
instance Show PaymentLinksResourcePaymentMethodReuseAgreement
instance Eq PaymentLinksResourcePaymentMethodReuseAgreement
instance Data.Aeson.FromJSON PaymentLinksResourcePaymentMethodReuseAgreement
instance Data.Aeson.ToJSON PaymentLinksResourcePaymentMethodReuseAgreement
data PaymentLinksResourcePaymentMethodReuseAgreementPosition'
instance Show PaymentLinksResourcePaymentMethodReuseAgreementPosition'
instance Eq PaymentLinksResourcePaymentMethodReuseAgreementPosition'
instance Data.Aeson.FromJSON PaymentLinksResourcePaymentMethodReuseAgreementPosition'
instance Data.Aeson.ToJSON PaymentLinksResourcePaymentMethodReuseAgreementPosition'
