module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptions
instance Show PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptions
instance Eq PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptions
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptions
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptions
data PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptionsCaptureMethod'
instance Show PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptionsCaptureMethod'
instance Eq PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptionsCaptureMethod'
