module StripeAPI.Types.PaymentLinksResourceSubscriptionData where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentLinksResourceSubscriptionData
instance Show PaymentLinksResourceSubscriptionData
instance Eq PaymentLinksResourceSubscriptionData
instance Data.Aeson.FromJSON PaymentLinksResourceSubscriptionData
instance Data.Aeson.ToJSON PaymentLinksResourceSubscriptionData
data PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
instance Show PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
instance Eq PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
instance Data.Aeson.FromJSON PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
instance Data.Aeson.ToJSON PaymentLinksResourceSubscriptionDataTrialSettings'NonNullable
