module StripeAPI.Types.PaymentMethodDetailsAuBecsDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsAuBecsDebit
instance Show PaymentMethodDetailsAuBecsDebit
instance Eq PaymentMethodDetailsAuBecsDebit
instance Data.Aeson.FromJSON PaymentMethodDetailsAuBecsDebit
instance Data.Aeson.ToJSON PaymentMethodDetailsAuBecsDebit
