module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptions
instance Show PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptions
instance Eq PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptions
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptions
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptions
data PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptionsCaptureMethod'
instance Show PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptionsCaptureMethod'
instance Eq PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptionsCaptureMethod'
