module StripeAPI.Types.PaymentIntentNextActionKonbiniStores where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentNextActionKonbiniStores
instance Show PaymentIntentNextActionKonbiniStores
instance Eq PaymentIntentNextActionKonbiniStores
instance Data.Aeson.FromJSON PaymentIntentNextActionKonbiniStores
instance Data.Aeson.ToJSON PaymentIntentNextActionKonbiniStores
data PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
instance Show PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
instance Eq PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
instance Data.Aeson.FromJSON PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
instance Data.Aeson.ToJSON PaymentIntentNextActionKonbiniStoresFamilymart'NonNullable
data PaymentIntentNextActionKonbiniStoresLawson'NonNullable
instance Show PaymentIntentNextActionKonbiniStoresLawson'NonNullable
instance Eq PaymentIntentNextActionKonbiniStoresLawson'NonNullable
instance Data.Aeson.FromJSON PaymentIntentNextActionKonbiniStoresLawson'NonNullable
instance Data.Aeson.ToJSON PaymentIntentNextActionKonbiniStoresLawson'NonNullable
data PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
instance Show PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
instance Eq PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
instance Data.Aeson.FromJSON PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
instance Data.Aeson.ToJSON PaymentIntentNextActionKonbiniStoresMinistop'NonNullable
data PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
instance Show PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
instance Eq PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
instance Data.Aeson.FromJSON PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
instance Data.Aeson.ToJSON PaymentIntentNextActionKonbiniStoresSeicomart'NonNullable
