module StripeAPI.Types.PaymentMethodOptionsFpx where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsFpx
instance Show PaymentMethodOptionsFpx
instance Eq PaymentMethodOptionsFpx
instance Data.Aeson.FromJSON PaymentMethodOptionsFpx
instance Data.Aeson.ToJSON PaymentMethodOptionsFpx
data PaymentMethodOptionsFpxSetupFutureUsage'
instance Show PaymentMethodOptionsFpxSetupFutureUsage'
instance Eq PaymentMethodOptionsFpxSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentMethodOptionsFpxSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentMethodOptionsFpxSetupFutureUsage'
