module StripeAPI.Types.PaymentMethodDetailsKonbiniStore where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsKonbiniStore
instance Show PaymentMethodDetailsKonbiniStore
instance Eq PaymentMethodDetailsKonbiniStore
instance Data.Aeson.FromJSON PaymentMethodDetailsKonbiniStore
instance Data.Aeson.ToJSON PaymentMethodDetailsKonbiniStore
data PaymentMethodDetailsKonbiniStoreChain'NonNullable
instance Show PaymentMethodDetailsKonbiniStoreChain'NonNullable
instance Eq PaymentMethodDetailsKonbiniStoreChain'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsKonbiniStoreChain'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsKonbiniStoreChain'NonNullable
