module StripeAPI.Types.PaymentMethodDetailsInteracPresent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsInteracPresent
instance Show PaymentMethodDetailsInteracPresent
instance Eq PaymentMethodDetailsInteracPresent
instance Data.Aeson.FromJSON PaymentMethodDetailsInteracPresent
instance Data.Aeson.ToJSON PaymentMethodDetailsInteracPresent
data PaymentMethodDetailsInteracPresentReadMethod'NonNullable
instance Show PaymentMethodDetailsInteracPresentReadMethod'NonNullable
instance Eq PaymentMethodDetailsInteracPresentReadMethod'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsInteracPresentReadMethod'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsInteracPresentReadMethod'NonNullable
data PaymentMethodDetailsInteracPresentReceipt'NonNullable
instance Show PaymentMethodDetailsInteracPresentReceipt'NonNullable
instance Eq PaymentMethodDetailsInteracPresentReceipt'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsInteracPresentReceipt'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsInteracPresentReceipt'NonNullable
data PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
instance Show PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
instance Eq PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
instance Data.Aeson.FromJSON PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
instance Data.Aeson.ToJSON PaymentMethodDetailsInteracPresentReceipt'NonNullableAccountType'
