module StripeAPI.Types.PaymentMethodDetailsInteracPresentReceipt where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsInteracPresentReceipt
instance Show PaymentMethodDetailsInteracPresentReceipt
instance Eq PaymentMethodDetailsInteracPresentReceipt
instance Data.Aeson.FromJSON PaymentMethodDetailsInteracPresentReceipt
instance Data.Aeson.ToJSON PaymentMethodDetailsInteracPresentReceipt
data PaymentMethodDetailsInteracPresentReceiptAccountType'
instance Show PaymentMethodDetailsInteracPresentReceiptAccountType'
instance Eq PaymentMethodDetailsInteracPresentReceiptAccountType'
instance Data.Aeson.FromJSON PaymentMethodDetailsInteracPresentReceiptAccountType'
instance Data.Aeson.ToJSON PaymentMethodDetailsInteracPresentReceiptAccountType'
