module StripeAPI.Types.PaymentMethodOptionsCardInstallments where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsCardInstallments
instance Show PaymentMethodOptionsCardInstallments
instance Eq PaymentMethodOptionsCardInstallments
instance Data.Aeson.FromJSON PaymentMethodOptionsCardInstallments
instance Data.Aeson.ToJSON PaymentMethodOptionsCardInstallments
data PaymentMethodOptionsCardInstallmentsPlan'NonNullable
instance Show PaymentMethodOptionsCardInstallmentsPlan'NonNullable
instance Eq PaymentMethodOptionsCardInstallmentsPlan'NonNullable
instance Data.Aeson.FromJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullable
instance Data.Aeson.ToJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullable
data PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Show PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Eq PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Data.Aeson.FromJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
instance Data.Aeson.ToJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullableInterval'NonNullable
data PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
instance Show PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
instance Eq PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
instance Data.Aeson.FromJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
instance Data.Aeson.ToJSON PaymentMethodOptionsCardInstallmentsPlan'NonNullableType'
