module StripeAPI.Types.PaymentFlowsAutomaticPaymentMethodsSetupIntent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsAutomaticPaymentMethodsSetupIntent
instance Show PaymentFlowsAutomaticPaymentMethodsSetupIntent
instance Eq PaymentFlowsAutomaticPaymentMethodsSetupIntent
instance Data.Aeson.FromJSON PaymentFlowsAutomaticPaymentMethodsSetupIntent
instance Data.Aeson.ToJSON PaymentFlowsAutomaticPaymentMethodsSetupIntent
data PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
instance Show PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
instance Eq PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
instance Data.Aeson.FromJSON PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
instance Data.Aeson.ToJSON PaymentFlowsAutomaticPaymentMethodsSetupIntentAllowRedirects'
