module StripeAPI.Types.PaymentMethodDetailsCardPresent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsCardPresent
instance Show PaymentMethodDetailsCardPresent
instance Eq PaymentMethodDetailsCardPresent
instance Data.Aeson.FromJSON PaymentMethodDetailsCardPresent
instance Data.Aeson.ToJSON PaymentMethodDetailsCardPresent
data PaymentMethodDetailsCardPresentOffline'NonNullable
instance Show PaymentMethodDetailsCardPresentOffline'NonNullable
instance Eq PaymentMethodDetailsCardPresentOffline'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardPresentOffline'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardPresentOffline'NonNullable
data PaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
instance Show PaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
instance Eq PaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
data PaymentMethodDetailsCardPresentReadMethod'NonNullable
instance Show PaymentMethodDetailsCardPresentReadMethod'NonNullable
instance Eq PaymentMethodDetailsCardPresentReadMethod'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardPresentReadMethod'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardPresentReadMethod'NonNullable
data PaymentMethodDetailsCardPresentReceipt'NonNullable
instance Show PaymentMethodDetailsCardPresentReceipt'NonNullable
instance Eq PaymentMethodDetailsCardPresentReceipt'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsCardPresentReceipt'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsCardPresentReceipt'NonNullable
data PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
instance Show PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
instance Eq PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
instance Data.Aeson.FromJSON PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
instance Data.Aeson.ToJSON PaymentMethodDetailsCardPresentReceipt'NonNullableAccountType'
