module StripeAPI.Types.PaymentPagesCheckoutSessionShippingAddressCollection where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionShippingAddressCollection
instance Show PaymentPagesCheckoutSessionShippingAddressCollection
instance Eq PaymentPagesCheckoutSessionShippingAddressCollection
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionShippingAddressCollection
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionShippingAddressCollection
data PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
instance Show PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
instance Eq PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionShippingAddressCollectionAllowedCountries'
