module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
instance Show PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
instance Eq PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptions
data PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'
instance Show PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'
instance Eq PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsCaptureMethod'
data PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'
instance Show PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'
instance Eq PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsNaverPayPaymentMethodOptionsSetupFutureUsage'
