module StripeAPI.Types.PaymentMethodUsBankAccountBlocked where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodUsBankAccountBlocked
instance Show PaymentMethodUsBankAccountBlocked
instance Eq PaymentMethodUsBankAccountBlocked
instance Data.Aeson.FromJSON PaymentMethodUsBankAccountBlocked
instance Data.Aeson.ToJSON PaymentMethodUsBankAccountBlocked
data PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
instance Show PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
instance Eq PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
instance Data.Aeson.FromJSON PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
instance Data.Aeson.ToJSON PaymentMethodUsBankAccountBlockedNetworkCode'NonNullable
data PaymentMethodUsBankAccountBlockedReason'NonNullable
instance Show PaymentMethodUsBankAccountBlockedReason'NonNullable
instance Eq PaymentMethodUsBankAccountBlockedReason'NonNullable
instance Data.Aeson.FromJSON PaymentMethodUsBankAccountBlockedReason'NonNullable
instance Data.Aeson.ToJSON PaymentMethodUsBankAccountBlockedReason'NonNullable
