module StripeAPI.Types.PaymentPagesCheckoutSessionCollectedInformation where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentPagesCheckoutSessionCollectedInformation
instance Show PaymentPagesCheckoutSessionCollectedInformation
instance Eq PaymentPagesCheckoutSessionCollectedInformation
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCollectedInformation
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCollectedInformation
data PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable
instance Show PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable
instance Eq PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable
instance Data.Aeson.FromJSON PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable
instance Data.Aeson.ToJSON PaymentPagesCheckoutSessionCollectedInformationShippingDetails'NonNullable
