module StripeAPI.Types.PaymentFlowsPrivatePaymentMethodsKlarnaDob where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentFlowsPrivatePaymentMethodsKlarnaDob
instance Show PaymentFlowsPrivatePaymentMethodsKlarnaDob
instance Eq PaymentFlowsPrivatePaymentMethodsKlarnaDob
instance Data.Aeson.FromJSON PaymentFlowsPrivatePaymentMethodsKlarnaDob
instance Data.Aeson.ToJSON PaymentFlowsPrivatePaymentMethodsKlarnaDob
