module StripeAPI.Types.PaymentMethodOptionsPaypal where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodOptionsPaypal
instance Show PaymentMethodOptionsPaypal
instance Eq PaymentMethodOptionsPaypal
instance Data.Aeson.FromJSON PaymentMethodOptionsPaypal
instance Data.Aeson.ToJSON PaymentMethodOptionsPaypal
data PaymentMethodOptionsPaypalCaptureMethod'
instance Show PaymentMethodOptionsPaypalCaptureMethod'
instance Eq PaymentMethodOptionsPaypalCaptureMethod'
instance Data.Aeson.FromJSON PaymentMethodOptionsPaypalCaptureMethod'
instance Data.Aeson.ToJSON PaymentMethodOptionsPaypalCaptureMethod'
data PaymentMethodOptionsPaypalSetupFutureUsage'
instance Show PaymentMethodOptionsPaypalSetupFutureUsage'
instance Eq PaymentMethodOptionsPaypalSetupFutureUsage'
instance Data.Aeson.FromJSON PaymentMethodOptionsPaypalSetupFutureUsage'
instance Data.Aeson.ToJSON PaymentMethodOptionsPaypalSetupFutureUsage'
