module StripeAPI.Types.PaymentIntentNextActionRedirectToUrl where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentIntentNextActionRedirectToUrl
instance Show PaymentIntentNextActionRedirectToUrl
instance Eq PaymentIntentNextActionRedirectToUrl
instance Data.Aeson.FromJSON PaymentIntentNextActionRedirectToUrl
instance Data.Aeson.ToJSON PaymentIntentNextActionRedirectToUrl
