module StripeAPI.Types.PaymentMethodDetailsUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PaymentMethodDetailsUsBankAccount
instance Show PaymentMethodDetailsUsBankAccount
instance Eq PaymentMethodDetailsUsBankAccount
instance Data.Aeson.FromJSON PaymentMethodDetailsUsBankAccount
instance Data.Aeson.ToJSON PaymentMethodDetailsUsBankAccount
data PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Show PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Eq PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsUsBankAccountAccountHolderType'NonNullable
data PaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Show PaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Eq PaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Data.Aeson.FromJSON PaymentMethodDetailsUsBankAccountAccountType'NonNullable
instance Data.Aeson.ToJSON PaymentMethodDetailsUsBankAccountAccountType'NonNullable
data PaymentMethodDetailsUsBankAccountMandate'Variants
instance Show PaymentMethodDetailsUsBankAccountMandate'Variants
instance Eq PaymentMethodDetailsUsBankAccountMandate'Variants
instance Data.Aeson.FromJSON PaymentMethodDetailsUsBankAccountMandate'Variants
instance Data.Aeson.ToJSON PaymentMethodDetailsUsBankAccountMandate'Variants
