module StripeAPI.Types.PortalResourceScheduleUpdateAtPeriodEndCondition where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PortalResourceScheduleUpdateAtPeriodEndCondition
instance Show PortalResourceScheduleUpdateAtPeriodEndCondition
instance Eq PortalResourceScheduleUpdateAtPeriodEndCondition
instance Data.Aeson.FromJSON PortalResourceScheduleUpdateAtPeriodEndCondition
instance Data.Aeson.ToJSON PortalResourceScheduleUpdateAtPeriodEndCondition
data PortalResourceScheduleUpdateAtPeriodEndConditionType'
instance Show PortalResourceScheduleUpdateAtPeriodEndConditionType'
instance Eq PortalResourceScheduleUpdateAtPeriodEndConditionType'
instance Data.Aeson.FromJSON PortalResourceScheduleUpdateAtPeriodEndConditionType'
instance Data.Aeson.ToJSON PortalResourceScheduleUpdateAtPeriodEndConditionType'
