module StripeAPI.Types.PortalBusinessProfile where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PortalBusinessProfile
instance Show PortalBusinessProfile
instance Eq PortalBusinessProfile
instance Data.Aeson.FromJSON PortalBusinessProfile
instance Data.Aeson.ToJSON PortalBusinessProfile
