module StripeAPI.Types.PortalFlowsFlow where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PortalFlowsFlow
instance Show PortalFlowsFlow
instance Eq PortalFlowsFlow
instance Data.Aeson.FromJSON PortalFlowsFlow
instance Data.Aeson.ToJSON PortalFlowsFlow
data PortalFlowsFlowSubscriptionCancel'NonNullable
instance Show PortalFlowsFlowSubscriptionCancel'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancel'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionCancel'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionCancel'NonNullable
data PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
instance Show PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullable
data PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
instance Show PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableCouponOffer'NonNullable
data PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
instance Show PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
instance Eq PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionCancel'NonNullableRetention'NonNullableType'
data PortalFlowsFlowSubscriptionUpdate'NonNullable
instance Show PortalFlowsFlowSubscriptionUpdate'NonNullable
instance Eq PortalFlowsFlowSubscriptionUpdate'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionUpdate'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionUpdate'NonNullable
data PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
instance Show PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
instance Eq PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionUpdateConfirm'NonNullable
data PortalFlowsFlowType'
instance Show PortalFlowsFlowType'
instance Eq PortalFlowsFlowType'
instance Data.Aeson.FromJSON PortalFlowsFlowType'
instance Data.Aeson.ToJSON PortalFlowsFlowType'
