module StripeAPI.Types.PortalFlowsFlowSubscriptionCancel where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PortalFlowsFlowSubscriptionCancel
instance Show PortalFlowsFlowSubscriptionCancel
instance Eq PortalFlowsFlowSubscriptionCancel
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionCancel
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionCancel
data PortalFlowsFlowSubscriptionCancelRetention'NonNullable
instance Show PortalFlowsFlowSubscriptionCancelRetention'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancelRetention'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullable
data PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
instance Show PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
instance Eq PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullableCouponOffer'NonNullable
data PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
instance Show PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
instance Eq PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
instance Data.Aeson.FromJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
instance Data.Aeson.ToJSON PortalFlowsFlowSubscriptionCancelRetention'NonNullableType'
