module StripeAPI.Types.PortalFlowsFlowAfterCompletion where
import qualified Data.Aeson
import qualified StripeAPI.Common
data PortalFlowsFlowAfterCompletion
instance Show PortalFlowsFlowAfterCompletion
instance Eq PortalFlowsFlowAfterCompletion
instance Data.Aeson.FromJSON PortalFlowsFlowAfterCompletion
instance Data.Aeson.ToJSON PortalFlowsFlowAfterCompletion
data PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
instance Show PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
instance Eq PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowAfterCompletionHostedConfirmation'NonNullable
data PortalFlowsFlowAfterCompletionRedirect'NonNullable
instance Show PortalFlowsFlowAfterCompletionRedirect'NonNullable
instance Eq PortalFlowsFlowAfterCompletionRedirect'NonNullable
instance Data.Aeson.FromJSON PortalFlowsFlowAfterCompletionRedirect'NonNullable
instance Data.Aeson.ToJSON PortalFlowsFlowAfterCompletionRedirect'NonNullable
data PortalFlowsFlowAfterCompletionType'
instance Show PortalFlowsFlowAfterCompletionType'
instance Eq PortalFlowsFlowAfterCompletionType'
instance Data.Aeson.FromJSON PortalFlowsFlowAfterCompletionType'
instance Data.Aeson.ToJSON PortalFlowsFlowAfterCompletionType'
