module StripeAPI.Types.RadarReviewResourceLocation where
import qualified Data.Aeson
import qualified StripeAPI.Common
data RadarReviewResourceLocation
instance Show RadarReviewResourceLocation
instance Eq RadarReviewResourceLocation
instance Data.Aeson.FromJSON RadarReviewResourceLocation
instance Data.Aeson.ToJSON RadarReviewResourceLocation
