module StripeAPI.Types.RevolutPayUnderlyingPaymentMethodFundingDetails where
import qualified Data.Aeson
import qualified StripeAPI.Common
data RevolutPayUnderlyingPaymentMethodFundingDetails
instance Show RevolutPayUnderlyingPaymentMethodFundingDetails
instance Eq RevolutPayUnderlyingPaymentMethodFundingDetails
instance Data.Aeson.FromJSON RevolutPayUnderlyingPaymentMethodFundingDetails
instance Data.Aeson.ToJSON RevolutPayUnderlyingPaymentMethodFundingDetails
data RevolutPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
instance Show RevolutPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
instance Eq RevolutPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
instance Data.Aeson.FromJSON RevolutPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
instance Data.Aeson.ToJSON RevolutPayUnderlyingPaymentMethodFundingDetailsType'NonNullable
