module StripeAPI.Types.SchedulesPhaseAutomaticTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SchedulesPhaseAutomaticTax
instance Show SchedulesPhaseAutomaticTax
instance Eq SchedulesPhaseAutomaticTax
instance Data.Aeson.FromJSON SchedulesPhaseAutomaticTax
instance Data.Aeson.ToJSON SchedulesPhaseAutomaticTax
data SchedulesPhaseAutomaticTaxDisabledReason'NonNullable
instance Show SchedulesPhaseAutomaticTaxDisabledReason'NonNullable
instance Eq SchedulesPhaseAutomaticTaxDisabledReason'NonNullable
instance Data.Aeson.FromJSON SchedulesPhaseAutomaticTaxDisabledReason'NonNullable
instance Data.Aeson.ToJSON SchedulesPhaseAutomaticTaxDisabledReason'NonNullable
data SchedulesPhaseAutomaticTaxLiability'NonNullable
instance Show SchedulesPhaseAutomaticTaxLiability'NonNullable
instance Eq SchedulesPhaseAutomaticTaxLiability'NonNullable
instance Data.Aeson.FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullable
instance Data.Aeson.ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullable
data SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
instance Show SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullableAccount'Variants
data SchedulesPhaseAutomaticTaxLiability'NonNullableType'
instance Show SchedulesPhaseAutomaticTaxLiability'NonNullableType'
instance Eq SchedulesPhaseAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.FromJSON SchedulesPhaseAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.ToJSON SchedulesPhaseAutomaticTaxLiability'NonNullableType'
