module StripeAPI.Types.SetupAttemptPaymentMethodDetailsCard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsCard
instance Show SetupAttemptPaymentMethodDetailsCard
instance Eq SetupAttemptPaymentMethodDetailsCard
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCard
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCard
data SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardChecks'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableAuthenticationFlow'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableElectronicCommerceIndicator'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResult'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableResultReason'NonNullable
data SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardThreeDSecure'NonNullableVersion'NonNullable
data SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardWallet'NonNullable
data SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
instance Show SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
instance Eq SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardWallet'NonNullableType'
