module StripeAPI.Types.SetupIntentPaymentMethodOptionsCardMandateOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsCardMandateOptions
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions
data SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
instance Show SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardMandateOptionsAmountType'
data SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
instance Show SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardMandateOptionsInterval'
data SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardMandateOptionsSupportedTypes'NonNullable
