module StripeAPI.Types.SetupIntentPaymentMethodOptionsMandateOptionsBacsDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsMandateOptionsBacsDebit
instance Show SetupIntentPaymentMethodOptionsMandateOptionsBacsDebit
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsBacsDebit
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsMandateOptionsBacsDebit
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsMandateOptionsBacsDebit
