module StripeAPI.Types.SetupIntentPaymentMethodOptionsCard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsCard
instance Show SetupIntentPaymentMethodOptionsCard
instance Eq SetupIntentPaymentMethodOptionsCard
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard
data SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullable
data SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableAmountType'
data SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableInterval'
data SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardMandateOptions'NonNullableSupportedTypes'NonNullable
data SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardNetwork'NonNullable
data SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Show SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
