module StripeAPI.Types.SetupIntentTypeSpecificPaymentMethodOptionsClient where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentTypeSpecificPaymentMethodOptionsClient
instance Show SetupIntentTypeSpecificPaymentMethodOptionsClient
instance Eq SetupIntentTypeSpecificPaymentMethodOptionsClient
instance Data.Aeson.FromJSON SetupIntentTypeSpecificPaymentMethodOptionsClient
instance Data.Aeson.ToJSON SetupIntentTypeSpecificPaymentMethodOptionsClient
data SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Show SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Eq SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Data.Aeson.FromJSON SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
instance Data.Aeson.ToJSON SetupIntentTypeSpecificPaymentMethodOptionsClientVerificationMethod'
