module StripeAPI.Types.SetupIntentPaymentMethodOptionsAcssDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsAcssDebit
instance Show SetupIntentPaymentMethodOptionsAcssDebit
instance Eq SetupIntentPaymentMethodOptionsAcssDebit
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsAcssDebit
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsAcssDebit
data SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
instance Show SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
instance Eq SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsAcssDebitCurrency'NonNullable
data SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Show SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsAcssDebitVerificationMethod'
