module StripeAPI.Types.SetupIntentNextActionVerifyWithMicrodeposits where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentNextActionVerifyWithMicrodeposits
instance Show SetupIntentNextActionVerifyWithMicrodeposits
instance Eq SetupIntentNextActionVerifyWithMicrodeposits
instance Data.Aeson.FromJSON SetupIntentNextActionVerifyWithMicrodeposits
instance Data.Aeson.ToJSON SetupIntentNextActionVerifyWithMicrodeposits
data SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Show SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Eq SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Data.Aeson.FromJSON SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
instance Data.Aeson.ToJSON SetupIntentNextActionVerifyWithMicrodepositsMicrodepositType'NonNullable
