module StripeAPI.Types.SetupAttemptPaymentMethodDetailsSofort where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsSofort
instance Show SetupAttemptPaymentMethodDetailsSofort
instance Eq SetupAttemptPaymentMethodDetailsSofort
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsSofort
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsSofort
data SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebit'NonNullableVariants
data SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsSofortGeneratedSepaDebitMandate'NonNullableVariants
data SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Show SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsSofortPreferredLanguage'NonNullable
