module StripeAPI.Types.SetupAttemptPaymentMethodDetailsCardWallet where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsCardWallet
instance Show SetupAttemptPaymentMethodDetailsCardWallet
instance Eq SetupAttemptPaymentMethodDetailsCardWallet
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardWallet
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardWallet
data SetupAttemptPaymentMethodDetailsCardWalletType'
instance Show SetupAttemptPaymentMethodDetailsCardWalletType'
instance Eq SetupAttemptPaymentMethodDetailsCardWalletType'
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardWalletType'
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardWalletType'
