module StripeAPI.Types.SetupAttemptPaymentMethodDetailsCardPresent where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsCardPresent
instance Show SetupAttemptPaymentMethodDetailsCardPresent
instance Eq SetupAttemptPaymentMethodDetailsCardPresent
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardPresent
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardPresent
data SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard'NonNullableVariants
data SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullable
data SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
instance Show SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsCardPresentOffline'NonNullableType'NonNullable
