module StripeAPI.Types.SetupIntentPaymentMethodOptionsUsBankAccount where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsUsBankAccount
instance Show SetupIntentPaymentMethodOptionsUsBankAccount
instance Eq SetupIntentPaymentMethodOptionsUsBankAccount
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsUsBankAccount
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsUsBankAccount
data SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Show SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsUsBankAccountVerificationMethod'
