module StripeAPI.Types.SetupIntentPaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptions
instance Show SetupIntentPaymentMethodOptions
instance Eq SetupIntentPaymentMethodOptions
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptions
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptions
data SetupIntentPaymentMethodOptionsAcssDebit'
instance Show SetupIntentPaymentMethodOptionsAcssDebit'
instance Eq SetupIntentPaymentMethodOptionsAcssDebit'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsAcssDebit'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsAcssDebit'
data SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
instance Show SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
instance Eq SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsAcssDebit'Currency'NonNullable
data SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsAcssDebit'VerificationMethod'
data SetupIntentPaymentMethodOptionsAmazonPay'
instance Show SetupIntentPaymentMethodOptionsAmazonPay'
instance Eq SetupIntentPaymentMethodOptionsAmazonPay'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsAmazonPay'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsAmazonPay'
data SetupIntentPaymentMethodOptionsAmazonPay'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsAmazonPay'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsAmazonPay'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsAmazonPay'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsAmazonPay'VerificationMethod'
data SetupIntentPaymentMethodOptionsBacsDebit'
instance Show SetupIntentPaymentMethodOptionsBacsDebit'
instance Eq SetupIntentPaymentMethodOptionsBacsDebit'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsBacsDebit'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsBacsDebit'
data SetupIntentPaymentMethodOptionsBacsDebit'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsBacsDebit'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsBacsDebit'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsBacsDebit'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsBacsDebit'VerificationMethod'
data SetupIntentPaymentMethodOptionsCard'
instance Show SetupIntentPaymentMethodOptionsCard'
instance Eq SetupIntentPaymentMethodOptionsCard'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard'
data SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullable
instance Show SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullable
data SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableAmountType'
instance Show SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableAmountType'
instance Eq SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableAmountType'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableAmountType'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableAmountType'
data SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableInterval'
instance Show SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableInterval'
instance Eq SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableInterval'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableInterval'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableInterval'
data SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableSupportedTypes'NonNullable
instance Show SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableSupportedTypes'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableSupportedTypes'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableSupportedTypes'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard'MandateOptions'NonNullableSupportedTypes'NonNullable
data SetupIntentPaymentMethodOptionsCard'Network'NonNullable
instance Show SetupIntentPaymentMethodOptionsCard'Network'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCard'Network'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard'Network'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard'Network'NonNullable
data SetupIntentPaymentMethodOptionsCard'RequestThreeDSecure'NonNullable
instance Show SetupIntentPaymentMethodOptionsCard'RequestThreeDSecure'NonNullable
instance Eq SetupIntentPaymentMethodOptionsCard'RequestThreeDSecure'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard'RequestThreeDSecure'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard'RequestThreeDSecure'NonNullable
data SetupIntentPaymentMethodOptionsCard'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsCard'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsCard'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCard'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCard'VerificationMethod'
data SetupIntentPaymentMethodOptionsCardPresent'
instance Show SetupIntentPaymentMethodOptionsCardPresent'
instance Eq SetupIntentPaymentMethodOptionsCardPresent'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardPresent'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardPresent'
data SetupIntentPaymentMethodOptionsCardPresent'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsCardPresent'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsCardPresent'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsCardPresent'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsCardPresent'VerificationMethod'
data SetupIntentPaymentMethodOptionsKlarna'
instance Show SetupIntentPaymentMethodOptionsKlarna'
instance Eq SetupIntentPaymentMethodOptionsKlarna'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsKlarna'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsKlarna'
data SetupIntentPaymentMethodOptionsKlarna'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsKlarna'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsKlarna'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsKlarna'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsKlarna'VerificationMethod'
data SetupIntentPaymentMethodOptionsLink'
instance Show SetupIntentPaymentMethodOptionsLink'
instance Eq SetupIntentPaymentMethodOptionsLink'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsLink'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsLink'
data SetupIntentPaymentMethodOptionsLink'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsLink'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsLink'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsLink'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsLink'VerificationMethod'
data SetupIntentPaymentMethodOptionsPaypal'
instance Show SetupIntentPaymentMethodOptionsPaypal'
instance Eq SetupIntentPaymentMethodOptionsPaypal'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsPaypal'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsPaypal'
data SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsPaypal'VerificationMethod'
data SetupIntentPaymentMethodOptionsSepaDebit'
instance Show SetupIntentPaymentMethodOptionsSepaDebit'
instance Eq SetupIntentPaymentMethodOptionsSepaDebit'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsSepaDebit'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsSepaDebit'
data SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsSepaDebit'VerificationMethod'
data SetupIntentPaymentMethodOptionsUsBankAccount'
instance Show SetupIntentPaymentMethodOptionsUsBankAccount'
instance Eq SetupIntentPaymentMethodOptionsUsBankAccount'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsUsBankAccount'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsUsBankAccount'
data SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
instance Show SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
instance Eq SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsUsBankAccount'VerificationMethod'
