module StripeAPI.Types.SetupAttemptPaymentMethodDetailsBancontact where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsBancontact
instance Show SetupAttemptPaymentMethodDetailsBancontact
instance Eq SetupAttemptPaymentMethodDetailsBancontact
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsBancontact
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsBancontact
data SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit'NonNullableVariants
data SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate'NonNullableVariants
data SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Show SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsBancontactPreferredLanguage'NonNullable
