module StripeAPI.Types.SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitDefaultFor'
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitPaymentSchedule'NonNullable
data SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Show SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsMandateOptionsAcssDebitTransactionType'NonNullable
