module StripeAPI.Types.SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit
instance Show SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit
instance Eq SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit
instance Data.Aeson.FromJSON SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit
instance Data.Aeson.ToJSON SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit
