module StripeAPI.Types.SetupAttemptPaymentMethodDetailsIdeal where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SetupAttemptPaymentMethodDetailsIdeal
instance Show SetupAttemptPaymentMethodDetailsIdeal
instance Eq SetupAttemptPaymentMethodDetailsIdeal
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsIdeal
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsIdeal
data SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
instance Show SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsIdealBank'NonNullable
data SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
instance Show SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
instance Eq SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsIdealBic'NonNullable
data SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebit'NonNullableVariants
data SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
instance Show SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
instance Eq SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.FromJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
instance Data.Aeson.ToJSON SetupAttemptPaymentMethodDetailsIdealGeneratedSepaDebitMandate'NonNullableVariants
