{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains the types generated from the schema SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit
module StripeAPI.Types.SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import StripeAPI.TypeAlias
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines the object schema located at @components.schemas.setup_intent_payment_method_options_mandate_options_sepa_debit@ in the specification.
data SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit = SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit
  { -- | reference_prefix: Prefix used to generate the Mandate reference. Must be at most 12 characters long. Must consist of only uppercase letters, numbers, spaces, or the following special characters: \'\/\', \'_\', \'-\', \'&\', \'.\'. Cannot begin with \'STRIPE\'.
    --
    -- Constraints:
    --
    -- * Maximum length of 5000
    setupIntentPaymentMethodOptionsMandateOptionsSepaDebitReferencePrefix :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  }
  deriving
    ( GHC.Show.Show,
      GHC.Classes.Eq
    )

instance Data.Aeson.Types.ToJSON.ToJSON SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit where
  toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("reference_prefix" Data.Aeson.Types.ToJSON..=)) (setupIntentPaymentMethodOptionsMandateOptionsSepaDebitReferencePrefix obj) : GHC.Base.mempty))
  toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("reference_prefix" Data.Aeson.Types.ToJSON..=)) (setupIntentPaymentMethodOptionsMandateOptionsSepaDebitReferencePrefix obj) : GHC.Base.mempty)))

instance Data.Aeson.Types.FromJSON.FromJSON SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit where
  parseJSON = Data.Aeson.Types.FromJSON.withObject "SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit" (\obj -> GHC.Base.pure SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "reference_prefix"))

-- | Create a new 'SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit' with all required fields.
mkSetupIntentPaymentMethodOptionsMandateOptionsSepaDebit :: SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit
mkSetupIntentPaymentMethodOptionsMandateOptionsSepaDebit = SetupIntentPaymentMethodOptionsMandateOptionsSepaDebit {setupIntentPaymentMethodOptionsMandateOptionsSepaDebitReferencePrefix = GHC.Maybe.Nothing}
