module StripeAPI.Types.ShippingRateDeliveryEstimate where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ShippingRateDeliveryEstimate
instance Show ShippingRateDeliveryEstimate
instance Eq ShippingRateDeliveryEstimate
instance Data.Aeson.FromJSON ShippingRateDeliveryEstimate
instance Data.Aeson.ToJSON ShippingRateDeliveryEstimate
data ShippingRateDeliveryEstimateMaximum'NonNullable
instance Show ShippingRateDeliveryEstimateMaximum'NonNullable
instance Eq ShippingRateDeliveryEstimateMaximum'NonNullable
instance Data.Aeson.FromJSON ShippingRateDeliveryEstimateMaximum'NonNullable
instance Data.Aeson.ToJSON ShippingRateDeliveryEstimateMaximum'NonNullable
data ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
instance Show ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
instance Eq ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
instance Data.Aeson.FromJSON ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
instance Data.Aeson.ToJSON ShippingRateDeliveryEstimateMaximum'NonNullableUnit'
data ShippingRateDeliveryEstimateMinimum'NonNullable
instance Show ShippingRateDeliveryEstimateMinimum'NonNullable
instance Eq ShippingRateDeliveryEstimateMinimum'NonNullable
instance Data.Aeson.FromJSON ShippingRateDeliveryEstimateMinimum'NonNullable
instance Data.Aeson.ToJSON ShippingRateDeliveryEstimateMinimum'NonNullable
data ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
instance Show ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
instance Eq ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
instance Data.Aeson.FromJSON ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
instance Data.Aeson.ToJSON ShippingRateDeliveryEstimateMinimum'NonNullableUnit'
