module StripeAPI.Types.SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStart where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStart
instance Show SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStart
instance Eq SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStart
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStart
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStart
data SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStartType'
instance Show SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStartType'
instance Eq SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStartType'
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStartType'
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStartType'
