module StripeAPI.Types.SubscriptionSchedulePhaseConfiguration where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionSchedulePhaseConfiguration
instance Show SubscriptionSchedulePhaseConfiguration
instance Eq SubscriptionSchedulePhaseConfiguration
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfiguration
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfiguration
data SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationBillingCycleAnchor'NonNullable
data SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationBillingThresholds'NonNullable
data SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationCollectionMethod'NonNullable
data SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
instance Show SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
instance Eq SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationDefaultPaymentMethod'NonNullableVariants
data SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullable
data SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableAccountTaxIds'NonNullableVariants
instance Show SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableAccountTaxIds'NonNullableVariants
instance Eq SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableAccountTaxIds'NonNullableVariants
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableAccountTaxIds'NonNullableVariants
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableAccountTaxIds'NonNullableVariants
data SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullable
data SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableAccount'Variants
instance Show SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableAccount'Variants
instance Eq SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableAccount'Variants
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableAccount'Variants
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableAccount'Variants
data SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableType'
instance Show SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableType'
instance Eq SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableType'
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableType'
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationInvoiceSettings'NonNullableIssuer'NonNullableType'
data SubscriptionSchedulePhaseConfigurationOnBehalfOf'NonNullableVariants
instance Show SubscriptionSchedulePhaseConfigurationOnBehalfOf'NonNullableVariants
instance Eq SubscriptionSchedulePhaseConfigurationOnBehalfOf'NonNullableVariants
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationOnBehalfOf'NonNullableVariants
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationOnBehalfOf'NonNullableVariants
data SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance Show SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance Eq SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationProrationBehavior'
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationProrationBehavior'
data SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
instance Show SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
instance Eq SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationTransferData'NonNullable
data SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
instance Show SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
instance Eq SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
instance Data.Aeson.FromJSON SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
instance Data.Aeson.ToJSON SubscriptionSchedulePhaseConfigurationTransferData'NonNullableDestination'Variants
