module StripeAPI.Types.SubscriptionSchedulesResourceDefaultSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionSchedulesResourceDefaultSettings
instance Show SubscriptionSchedulesResourceDefaultSettings
instance Eq SubscriptionSchedulesResourceDefaultSettings
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettings
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettings
data SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance Show SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance Eq SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsBillingCycleAnchor'
data SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsBillingThresholds'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsCollectionMethod'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
instance Show SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
instance Eq SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsDefaultPaymentMethod'NonNullableVariants
data SubscriptionSchedulesResourceDefaultSettingsOnBehalfOf'NonNullableVariants
instance Show SubscriptionSchedulesResourceDefaultSettingsOnBehalfOf'NonNullableVariants
instance Eq SubscriptionSchedulesResourceDefaultSettingsOnBehalfOf'NonNullableVariants
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsOnBehalfOf'NonNullableVariants
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsOnBehalfOf'NonNullableVariants
data SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
instance Show SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
instance Eq SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsTransferData'NonNullableDestination'Variants
