module StripeAPI.Types.SubscriptionsTrialsResourceEndBehavior where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionsTrialsResourceEndBehavior
instance Show SubscriptionsTrialsResourceEndBehavior
instance Eq SubscriptionsTrialsResourceEndBehavior
instance Data.Aeson.FromJSON SubscriptionsTrialsResourceEndBehavior
instance Data.Aeson.ToJSON SubscriptionsTrialsResourceEndBehavior
data SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
instance Show SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
instance Eq SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
instance Data.Aeson.FromJSON SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
instance Data.Aeson.ToJSON SubscriptionsTrialsResourceEndBehaviorMissingPaymentMethod'
