module StripeAPI.Types.SubscriptionsResourceSubscriptionInvoiceSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionsResourceSubscriptionInvoiceSettings
instance Show SubscriptionsResourceSubscriptionInvoiceSettings
instance Eq SubscriptionsResourceSubscriptionInvoiceSettings
instance Data.Aeson.FromJSON SubscriptionsResourceSubscriptionInvoiceSettings
instance Data.Aeson.ToJSON SubscriptionsResourceSubscriptionInvoiceSettings
data SubscriptionsResourceSubscriptionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Show SubscriptionsResourceSubscriptionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Eq SubscriptionsResourceSubscriptionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Data.Aeson.FromJSON SubscriptionsResourceSubscriptionInvoiceSettingsAccountTaxIds'NonNullableVariants
instance Data.Aeson.ToJSON SubscriptionsResourceSubscriptionInvoiceSettingsAccountTaxIds'NonNullableVariants
