module StripeAPI.Types.SubscriptionSchedulesResourceDefaultSettingsAutomaticTax where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTax
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxDisabledReason'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxDisabledReason'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxDisabledReason'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxDisabledReason'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxDisabledReason'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullable
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableAccount'Variants
data SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
instance Show SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
instance Eq SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceDefaultSettingsAutomaticTaxLiability'NonNullableType'
