module StripeAPI.Types.SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEnd where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEnd
instance Show SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEnd
instance Eq SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEnd
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEnd
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEnd
data SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEndType'
instance Show SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEndType'
instance Eq SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEndType'
instance Data.Aeson.FromJSON SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEndType'
instance Data.Aeson.ToJSON SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEndType'
