module StripeAPI.Types.SubscriptionBillingThresholds where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionBillingThresholds
instance Show SubscriptionBillingThresholds
instance Eq SubscriptionBillingThresholds
instance Data.Aeson.FromJSON SubscriptionBillingThresholds
instance Data.Aeson.ToJSON SubscriptionBillingThresholds
