module StripeAPI.Types.SubscriptionsResourcePaymentMethodOptions where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionsResourcePaymentMethodOptions
instance Show SubscriptionsResourcePaymentMethodOptions
instance Eq SubscriptionsResourcePaymentMethodOptions
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptions
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptions
data SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullable
data SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Show SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Eq SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsAcssDebit'NonNullableVerificationMethod'
data SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullable
data SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Show SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Eq SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsBancontact'NonNullablePreferredLanguage'
data SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullable
data SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullableNetwork'NonNullable
data SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsCard'NonNullableRequestThreeDSecure'NonNullable
data SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullable
data SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsCustomerBalance'NonNullableFundingType'NonNullable
data SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
instance Show SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
instance Eq SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullable
data SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Show SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Eq SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentMethodOptionsUsBankAccount'NonNullableVerificationMethod'
