module StripeAPI.Types.SubscriptionScheduleAddInvoiceItem where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionScheduleAddInvoiceItem
instance Show SubscriptionScheduleAddInvoiceItem
instance Eq SubscriptionScheduleAddInvoiceItem
instance Data.Aeson.FromJSON SubscriptionScheduleAddInvoiceItem
instance Data.Aeson.ToJSON SubscriptionScheduleAddInvoiceItem
data SubscriptionScheduleAddInvoiceItemPrice'Variants
instance Show SubscriptionScheduleAddInvoiceItemPrice'Variants
instance Eq SubscriptionScheduleAddInvoiceItemPrice'Variants
instance Data.Aeson.FromJSON SubscriptionScheduleAddInvoiceItemPrice'Variants
instance Data.Aeson.ToJSON SubscriptionScheduleAddInvoiceItemPrice'Variants
