module StripeAPI.Types.SubscriptionPaymentMethodOptionsCard where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionPaymentMethodOptionsCard
instance Show SubscriptionPaymentMethodOptionsCard
instance Eq SubscriptionPaymentMethodOptionsCard
instance Data.Aeson.FromJSON SubscriptionPaymentMethodOptionsCard
instance Data.Aeson.ToJSON SubscriptionPaymentMethodOptionsCard
data SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
instance Show SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
instance Eq SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
instance Data.Aeson.FromJSON SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
instance Data.Aeson.ToJSON SubscriptionPaymentMethodOptionsCardNetwork'NonNullable
data SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Show SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Eq SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Data.Aeson.FromJSON SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
instance Data.Aeson.ToJSON SubscriptionPaymentMethodOptionsCardRequestThreeDSecure'NonNullable
