module StripeAPI.Types.SubscriptionScheduleConfigurationItem where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionScheduleConfigurationItem
instance Show SubscriptionScheduleConfigurationItem
instance Eq SubscriptionScheduleConfigurationItem
instance Data.Aeson.FromJSON SubscriptionScheduleConfigurationItem
instance Data.Aeson.ToJSON SubscriptionScheduleConfigurationItem
data SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
instance Show SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
instance Eq SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
instance Data.Aeson.FromJSON SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
instance Data.Aeson.ToJSON SubscriptionScheduleConfigurationItemBillingThresholds'NonNullable
data SubscriptionScheduleConfigurationItemPrice'Variants
instance Show SubscriptionScheduleConfigurationItemPrice'Variants
instance Eq SubscriptionScheduleConfigurationItemPrice'Variants
instance Data.Aeson.FromJSON SubscriptionScheduleConfigurationItemPrice'Variants
instance Data.Aeson.ToJSON SubscriptionScheduleConfigurationItemPrice'Variants
