module StripeAPI.Types.SubscriptionsResourcePaymentSettings where
import qualified Data.Aeson
import qualified StripeAPI.Common
data SubscriptionsResourcePaymentSettings
instance Show SubscriptionsResourcePaymentSettings
instance Eq SubscriptionsResourcePaymentSettings
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettings
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettings
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableAcssDebit'NonNullableVerificationMethod'
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableBancontact'NonNullablePreferredLanguage'
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableNetwork'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCard'NonNullableRequestThreeDSecure'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableCustomerBalance'NonNullableFundingType'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullable
data SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodOptions'NonNullableUsBankAccount'NonNullableVerificationMethod'
data SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance Show SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsPaymentMethodTypes'NonNullable
data SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
instance Show SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
instance Eq SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
instance Data.Aeson.FromJSON SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
instance Data.Aeson.ToJSON SubscriptionsResourcePaymentSettingsSaveDefaultPaymentMethod'NonNullable
