module StripeAPI.Types.ThreeDSecureDetailsCharge where
import qualified Data.Aeson
import qualified StripeAPI.Common
data ThreeDSecureDetailsCharge
instance Show ThreeDSecureDetailsCharge
instance Eq ThreeDSecureDetailsCharge
instance Data.Aeson.FromJSON ThreeDSecureDetailsCharge
instance Data.Aeson.ToJSON ThreeDSecureDetailsCharge
data ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
instance Show ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
instance Eq ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
instance Data.Aeson.FromJSON ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
instance Data.Aeson.ToJSON ThreeDSecureDetailsChargeAuthenticationFlow'NonNullable
data ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
instance Show ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
instance Eq ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
instance Data.Aeson.FromJSON ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
instance Data.Aeson.ToJSON ThreeDSecureDetailsChargeElectronicCommerceIndicator'NonNullable
data ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
instance Show ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
instance Eq ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
instance Data.Aeson.FromJSON ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
instance Data.Aeson.ToJSON ThreeDSecureDetailsChargeExemptionIndicator'NonNullable
data ThreeDSecureDetailsChargeResult'NonNullable
instance Show ThreeDSecureDetailsChargeResult'NonNullable
instance Eq ThreeDSecureDetailsChargeResult'NonNullable
instance Data.Aeson.FromJSON ThreeDSecureDetailsChargeResult'NonNullable
instance Data.Aeson.ToJSON ThreeDSecureDetailsChargeResult'NonNullable
data ThreeDSecureDetailsChargeResultReason'NonNullable
instance Show ThreeDSecureDetailsChargeResultReason'NonNullable
instance Eq ThreeDSecureDetailsChargeResultReason'NonNullable
instance Data.Aeson.FromJSON ThreeDSecureDetailsChargeResultReason'NonNullable
instance Data.Aeson.ToJSON ThreeDSecureDetailsChargeResultReason'NonNullable
data ThreeDSecureDetailsChargeVersion'NonNullable
instance Show ThreeDSecureDetailsChargeVersion'NonNullable
instance Eq ThreeDSecureDetailsChargeVersion'NonNullable
instance Data.Aeson.FromJSON ThreeDSecureDetailsChargeVersion'NonNullable
instance Data.Aeson.ToJSON ThreeDSecureDetailsChargeVersion'NonNullable
