{-# LANGUAGE MultiWayIf #-}
-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.
{-# LANGUAGE OverloadedStrings #-}

-- | Contains all types with cyclic dependencies (between each other or to itself)
module StripeAPI.TypeAlias where

import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Functor
import qualified Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified StripeAPI.Common
import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe

-- | Defines an alias for the schema located at @components.schemas.setup_intent_payment_method_options_link@ in the specification.
type SetupIntentPaymentMethodOptionsLink = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_intent_payment_method_options_card_present@ in the specification.
type SetupIntentPaymentMethodOptionsCardPresent = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_intent_payment_method_options_amazon_pay@ in the specification.
type SetupIntentPaymentMethodOptionsAmazonPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_us_bank_account@ in the specification.
type SetupAttemptPaymentMethodDetailsUsBankAccount = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_sepa_debit@ in the specification.
type SetupAttemptPaymentMethodDetailsSepaDebit = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_revolut_pay@ in the specification.
type SetupAttemptPaymentMethodDetailsRevolutPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_paypal@ in the specification.
type SetupAttemptPaymentMethodDetailsPaypal = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_nz_bank_account@ in the specification.
type SetupAttemptPaymentMethodDetailsNzBankAccount = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_link@ in the specification.
type SetupAttemptPaymentMethodDetailsLink = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_kr_card@ in the specification.
type SetupAttemptPaymentMethodDetailsKrCard = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_klarna@ in the specification.
type SetupAttemptPaymentMethodDetailsKlarna = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_kakao_pay@ in the specification.
type SetupAttemptPaymentMethodDetailsKakaoPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_cashapp@ in the specification.
type SetupAttemptPaymentMethodDetailsCashapp = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_boleto@ in the specification.
type SetupAttemptPaymentMethodDetailsBoleto = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_bacs_debit@ in the specification.
type SetupAttemptPaymentMethodDetailsBacsDebit = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_au_becs_debit@ in the specification.
type SetupAttemptPaymentMethodDetailsAuBecsDebit = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_amazon_pay@ in the specification.
type SetupAttemptPaymentMethodDetailsAmazonPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.setup_attempt_payment_method_details_acss_debit@ in the specification.
type SetupAttemptPaymentMethodDetailsAcssDebit = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_zip@ in the specification.
type PaymentMethodZip = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_wechat_pay@ in the specification.
type PaymentMethodWechatPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_twint@ in the specification.
type PaymentMethodTwint = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_swish@ in the specification.
type PaymentMethodSwish = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_satispay@ in the specification.
type PaymentMethodSatispay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_samsung_pay@ in the specification.
type PaymentMethodSamsungPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_revolut_pay@ in the specification.
type PaymentMethodRevolutPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_promptpay@ in the specification.
type PaymentMethodPromptpay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_pix@ in the specification.
type PaymentMethodPix = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_paynow@ in the specification.
type PaymentMethodPaynow = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_payco@ in the specification.
type PaymentMethodPayco = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_pay_by_bank@ in the specification.
type PaymentMethodPayByBank = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_oxxo@ in the specification.
type PaymentMethodOxxo = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_options_pay_by_bank@ in the specification.
type PaymentMethodOptionsPayByBank = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_options_interac_present@ in the specification.
type PaymentMethodOptionsInteracPresent = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_multibanco@ in the specification.
type PaymentMethodMultibanco = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_mobilepay@ in the specification.
type PaymentMethodMobilepay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_konbini@ in the specification.
type PaymentMethodKonbini = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_kakao_pay@ in the specification.
type PaymentMethodKakaoPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_grabpay@ in the specification.
type PaymentMethodGrabpay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_giropay@ in the specification.
type PaymentMethodGiropay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_zip@ in the specification.
type PaymentMethodDetailsZip = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_wechat@ in the specification.
type PaymentMethodDetailsWechat = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_twint@ in the specification.
type PaymentMethodDetailsTwint = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_stripe_account@ in the specification.
type PaymentMethodDetailsStripeAccount = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_pay_by_bank@ in the specification.
type PaymentMethodDetailsPayByBank = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_customer_balance@ in the specification.
type PaymentMethodDetailsCustomerBalance = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_card_wallet_samsung_pay@ in the specification.
type PaymentMethodDetailsCardWalletSamsungPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_card_wallet_link@ in the specification.
type PaymentMethodDetailsCardWalletLink = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_card_wallet_google_pay@ in the specification.
type PaymentMethodDetailsCardWalletGooglePay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_card_wallet_apple_pay@ in the specification.
type PaymentMethodDetailsCardWalletApplePay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_details_card_wallet_amex_express_checkout@ in the specification.
type PaymentMethodDetailsCardWalletAmexExpressCheckout = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_customer_balance@ in the specification.
type PaymentMethodCustomerBalance = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_crypto@ in the specification.
type PaymentMethodCrypto = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_card_wallet_samsung_pay@ in the specification.
type PaymentMethodCardWalletSamsungPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_card_wallet_link@ in the specification.
type PaymentMethodCardWalletLink = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_card_wallet_google_pay@ in the specification.
type PaymentMethodCardWalletGooglePay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_card_wallet_apple_pay@ in the specification.
type PaymentMethodCardWalletApplePay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_card_wallet_amex_express_checkout@ in the specification.
type PaymentMethodCardWalletAmexExpressCheckout = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_blik@ in the specification.
type PaymentMethodBlik = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_billie@ in the specification.
type PaymentMethodBillie = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_bancontact@ in the specification.
type PaymentMethodBancontact = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_amazon_pay@ in the specification.
type PaymentMethodAmazonPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_alma@ in the specification.
type PaymentMethodAlma = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_afterpay_clearpay@ in the specification.
type PaymentMethodAfterpayClearpay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_method_affirm@ in the specification.
type PaymentMethodAffirm = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.payment_flows_private_payment_methods_alipay@ in the specification.
type PaymentFlowsPrivatePaymentMethodsAlipay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.offline_acceptance@ in the specification.
type OfflineAcceptance = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_revolut_pay@ in the specification.
type MandateRevolutPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_nz_bank_account@ in the specification.
type MandateNzBankAccount = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_naver_pay@ in the specification.
type MandateNaverPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_multi_use@ in the specification.
type MandateMultiUse = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_link@ in the specification.
type MandateLink = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_kr_card@ in the specification.
type MandateKrCard = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_klarna@ in the specification.
type MandateKlarna = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_kakao_pay@ in the specification.
type MandateKakaoPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_cashapp@ in the specification.
type MandateCashapp = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.mandate_amazon_pay@ in the specification.
type MandateAmazonPay = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.invoice_payment_method_options_sepa_debit@ in the specification.
type InvoicePaymentMethodOptionsSepaDebit = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.invoice_payment_method_options_konbini@ in the specification.
type InvoicePaymentMethodOptionsKonbini = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.destination_details_unimplemented@ in the specification.
type DestinationDetailsUnimplemented = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.card_mandate_payment_method_details@ in the specification.
type CardMandatePaymentMethodDetails = Data.Aeson.Types.Internal.Object
